### ISSUE TITLE
Zivilisten

### ISSUE THREAD

**Issue by jus61** [Wyqer/kp_liberation#1]
Zivilisten die nicht mehr herumstehen wen geschossen wird.

https://forums.bistudio.com/topic/201304-release-fleeing-civilians/

**Comment by Wyqer** [comment]
Das momentane Verhalten der Zivilisten ist halt, dass sie in Deckung gehen bzw. "weggehen".
Nicht richtig "fliehen", aber ich behalte das Script mal im Hinterkopf.
