### ISSUE TITLE
Resources Overhaul 

### ISSUE THREAD

**Issue by svamp3717** [Wyqer/kp_liberation#10]
Instead of some kind of production system for resources. How about replacing the ammo with something like "political support" or "prestige"?

The mission starts with a set number of prestige.
Every time a player dies a number of prestige is removed.
Every time an friendly AI dies a very small number of prestige is also removed.
Every time a friendly vehicle is destroyed some prestige is removed.
Buying vehicles also cost prestige. The fancy ones are obviously more expensive. Maybe even prestige can be used for "researching" or unlocking them in the first place.
Taking and holding military bases gives the most prestige, towns or radio towers the least. Losing control of a sector would probably cost some prestige as well.

Recycling gives back some of the prestige.

The prestige can go into negative but then no fancy vehicles can be bought, no new FOB's etc. 
Unit caps and vehicle caps could be tied to local buildings in fobs as well but, would have to be bought by prestige. 

It would have to exist more ways of getting prestige since dying and building would make it go away rather fast. Holding sectors after they have been captured should probably give some prestige but may require a more aggressive opfor. Maybe new sidemissions like hearts and minds (deliver food packages to captured towns, clear all of the remaning IEDs etc.).

**Comment by Wyqer** [comment]
I've thought about some of the things you mentioned.
But I thought about adding a kind of "civil supporting" system. Maybe some equals to your suggestion.
Resources should still be the stuff on which building etc. rely on, but I wanted to expand the "hearts and minds" aspect later on, too.
Kill civilians, destroy civil buildings, loose sectors to the enemy, loose soldiers or vehicles, everything that could decrease the civil opinion about your forces should be connected with that.
If the civilians "like" you, you could maybe encounter some guerilla forces, who attack the enemy or join the fight, when you attacking a sector. Also if the civilians "hate" you, you could get some ambushes on your troops, fobs, etc.
But well, there are many ideas and I don't doubt, that it can be implemented. But it will take time, for sure.
