### ISSUE TITLE
Enemies should kill mobile respawns

### ISSUE THREAD

**Issue by CurePindal** [Wyqer/kp_liberation#100]
One thing thats pretty annoying in Liberation is that enemies ignore the mobile respawns. (as long as they are empty) You can drive that thing pretty much right into an occupied town and once nobody is any longer riding the MOB its safe. Thats terrible.
Enemies should take every chance to destroy a mobile respawn. It would be a better, more immersive game flow when players have to take care of their MOB, protect and defend it!

**Comment by Wyqer** [comment]
I even think the whole mobile respawn and mobile arsenal is not immersive, but yeah, I totally agree with this suggestion.
It's normal ArmA behaviour that empty vehicles are no targets for the enemy AI. I'll have a look, if there is a way to let the AI still target empty vehicles which are declared as mobile respawn classnames.

**Comment by k4s0** [comment]
Me and my clan many times the enemy attacks our MOB (if positioned near the sector) obviously if we leave it to 300-400 meters, as we usually do ,they don't attack it

**Comment by Wyqer** [comment]
I've not found a "suitable" solution to let enemy AI attack an empty vehicle without things like "place a invisible drone or something inside the empty vehicle" etc.
If someone has a better solution, post it with explanation and source. Then I'll have a look into it again.
