### ISSUE TITLE
Problem with the build menu 

### ISSUE THREAD

**Issue by evandro-peretti** [Wyqer/kp_liberation#102]
Hi, I sent you a message today in the steam with a problem related to the build menu and as you suggested I will post how to reproduce the error and I am also sent some screenshots to illustrate better.

> Steam message [User GrayFox]: 
> I'm having a problem with the build menu where the scroll bar keeps scrolling up every two seconds as if it were reloading the items and on the support tab I noticed that huron fuel and huron ammo do not appear.

How to reproduce:
[screenshots.zip](https://github.com/Wyqer/kp_liberation/files/1026455/screenshots.zip)

`1 - Downloaded the mission file from Steam Workshop (I did not make any modifications to the files just downloaded from steam)`
` 2 - Opened the game launcher and added the RHS USAF mod from there (RHS downloaded from Steam Workshop)[step_2.jpg]`
`3 - After the game loads I go on MULTIPLAYER -> QUICK PLAY -> HOST SERVER`
`4 - Settings in image [step_4.jpg]`
`5 - In maps option I select Altis and in missions option I select KP Liberation [step_5.jpg]`
`6 - Select platoon leader option and all parameters are set to default value`

I was playing version 0.94 in the same way and this problem did not happen

Thanks for the attention.

**Comment by Wyqer** [comment]
Ok, thanks for the detailed steps. Mainly it was meant to things which you do ingame or concerning starting environment of the mission :)

Is there anything in the server.rpt?
Did you wipe your Save before switching from 0.94 ot 0.95?
