### ISSUE TITLE
UI Logistic

### ISSUE THREAD

**Issue by madpat3** [Wyqer/kp_liberation#104]
only works correctly with UI set to small and very small. otherwise the buttons are overlapping.

**Comment by Wyqer** [comment]
Can you provide comparison screenshots of the different ui settings?
Did you change the ui setting directly InGame or with restarts between?

**Comment by madpat3** [comment]
build is fine. production and logistic not. changed it ingame, but "normal" is my general setting and it doesn't work.
normal:
![20170525084143_1](https://cloud.githubusercontent.com/assets/15272840/26439070/af2d1d4c-4126-11e7-9c30-6e24135d571b.jpg)
![20170525084153_1](https://cloud.githubusercontent.com/assets/15272840/26439074/b160a1ce-4126-11e7-998e-488634367c56.jpg)
small:
![20170525084316_1](https://cloud.githubusercontent.com/assets/15272840/26439079/b8c386a2-4126-11e7-9f61-fa98457db20b.jpg)
![20170525084405_1](https://cloud.githubusercontent.com/assets/15272840/26439086/bf844670-4126-11e7-82d4-34b1a2e73d69.jpg)

**Comment by Wyqer** [comment]
Ok, I'll have a look for a suitable uiscale multiplier for the spacing. Thanks for the report :)
