### ISSUE TITLE
script errors

### ISSUE THREAD

**Issue by madpat3** [Wyqer/kp_liberation#105]
i get several script errors with the sahrani edit.
happens when i manage logistics or production. 
![unbenannt](https://cloud.githubusercontent.com/assets/15272840/26439943/83d6a7a4-412a-11e7-883f-a00b2f97f597.jpg)

**Comment by Wyqer** [comment]
Did you changed anything?
Because the scripts are independent from the map, so if it's a general error you would get it on each map and not only on Sahrani.
Maybe a older save from Sahrani? Changed the Savegame Key in the config?

**Comment by madpat3** [comment]
no thats because i didn't know how the system works. i didn't define a "B" destination for the truck.

**Comment by Wyqer** [comment]
That was the necessary Information (don't defined a B) to solve it in no time.
Well, didn't thought that you've done something which "makes no sense". But sure, I'll should catch even these situations in the code. So thanks for the hint.
