### ISSUE TITLE
Release 0.95 not working correctly

### ISSUE THREAD

**Issue by ShuraITA** [Wyqer/kp_liberation#106]
I've ran the version 0.95 and instead of starting normally I'll see the cinematic and then I spawn in an empty island. With Tanoa map I spawn south east of the aircraft carrier. I don't know if this will be helpfull, but If I go to the editor I will see, for example, the zeus' marker. How can I fix this please?
Thanks in advice.

**Comment by Wyqer** [comment]
Did you wiped the savegame after switching from 0.94 to 0.95?

**Comment by k4s0** [comment]
Did you wipe the data?

**Comment by k4s0** [comment]
hahaha lol @Wyqer

**Comment by ShuraITA** [comment]
Thanks again, sorry for the noob question

**Comment by Wyqer** [comment]
So it was caused by a old savegame?
Glad that we could help you that fast then. Hope you enjoy it :)

**Comment by k4s0** [comment]
if you have any other questions we are here . :)

**Comment by ShuraITA** [comment]
Yes was the .vars.Arma3Profile file ^^
Thanks a lot again

**Comment by k4s0** [comment]
@ShuraITA  where are you from ?
