### ISSUE TITLE
recycling bug

### ISSUE THREAD

**Issue by madpat3** [Wyqer/kp_liberation#111]
i have no option to recycle the bw-mod eagle

and i have option to recycle the vanilla boat, but it ain't working.

script error in do_recycle.sqf
![20170526180939_1](https://cloud.githubusercontent.com/assets/15272840/26502960/287bedea-423f-11e7-88c1-21ba1fb0adca.jpg)
![20170526181010_1](https://cloud.githubusercontent.com/assets/15272840/26502967/2edb83d0-423f-11e7-9e01-e5e694a14e85.jpg)

after reloggin to the server i had the option to recycle the eagle.
the script error for the "rubber-boat" stayed. i built the boat on ground, not on water.
one was logged in as admin, the otherone was logged in as commander, so both had acces to logistic/production interface, all the time.

**Comment by Wyqer** [comment]
Well, yeah the Eagle is in the preset, so there will be a recycle option, but a server restart solved it for you. But sure some kind of weird, but well.... sometimes it seems to be just "ArmA things".

Concerning the boat: Did you edit anything in the preset file on your current pbo?

**Comment by madpat3** [comment]
i didn't restart the server i just logged out. after a few hours i joined the server again and it worked. but not the boat.
the preset is basicly your rhs+bw preset. i changed huron typename to ch53 and opfor ammobox transport to a kamaz5350 truck. yes i defined it, so it can transport boxes.
i changed the classnames of the planes and helis and drones, which changed since the last vanilla update.
and i added the mi-8mt-v3 and mi-28n-vsc to enemies.

**Comment by Wyqer** [comment]
The bug was caused due to the dinghi has no "Hull Hitpoints" and only "Engine Hitpoints". And as the supply amount for recycle is calculated with the remaining hitpoints of hull and enginge he didn't get a number for the calculation for the boat. Added a exception, that the boat only is calculated with the engine hitpoints.
