### ISSUE TITLE
Logistic mission issues

### ISSUE THREAD

**Issue by CurePindal** [Wyqer/kp_liberation#112]
Hey Wyquer,
we talked about the issue on discord when you set values for a logistics mission and the mission replies with "no resources" even when resources are stored at the production site.

Its very easy to reproduce if you enter the values that I used and start the mission:
Pic: https://www.dropbox.com/s/f02ax8djgofpki7/20170526185510_1.jpg?dl=0

Irmi had 1 supply and 7 fuel crates stored at that moment.
Had an equal issue with a production site that had crates of all 3 resources.

Was tested on the unmod. KP server with v.951

**Comment by madpat3** [comment]
the truck is waiting for the ammo crate

**Comment by Wyqer** [comment]
Had a look and I know why it won't work as intended.
Until fixed, stick to one resource if you want to establish a "passive income logistic group" for a sector.

**Comment by Wyqer** [comment]
Tested the changes and now the behaviour works as intended (in all my test cases)

Two Examples:
Sector A has 500 S, 0 A and 200 F

Mission for 1000 S, 1000 A and 1000 F will result in:
100 S, 200 F
300 S
Waiting (Sector has only 100 S)

Mission for 500 S and 200 F will result in:
200 S, 100 F
200 S, 100 F
100 S
Ready again

**Comment by CurePindal** [comment]
Sorry, but I can reproduce this bug on the unmod. KP server 100% (.951, please test yourself):

Shows "no resources"
https://www.dropbox.com/s/sr1y552nriqpkuf/20170527161914_1.jpg?dl=0
Heres the POI:
https://www.dropbox.com/s/vta9n0tvjaxwtop/20170527161928_1.jpg?dl=0

(PS: Jus updated the mission last night ~1am)

**Comment by Wyqer** [comment]
(PS: Jus updated the mission last night ~1am)
vs
Wyqer added a commit that referenced this issue 2 hours ago
