### ISSUE TITLE
building storages 

### ISSUE THREAD

**Issue by madpat3** [Wyqer/kp_liberation#115]
when logged in as admin and someone else is commander, i was able to build multiple starage rooms after liberating a sector

**Comment by Wyqer** [comment]
Everyone with building rights can build storages and facilities at a sector.
For the "multiple storages" there will be a change in the 951 for the sync of the production data between client and server, which should fix that. In general, only one storage is registered for a sector. The second one will be gone after reload.
It could still happen, if the server is under heavy load or there are more players and AI that the server can handle. Then the sync could take some seconds and you'll be able to build again a storage after you've build the first one, but well.... only one counts and it should be very rare after the patch.
