### ISSUE TITLE
0.951 - Unable to build storage area

### ISSUE THREAD

**Issue by ChiefOwens** [Wyqer/kp_liberation#116]
While testing 0.951, I took the first oilfield and was unable to put down a building storage in the sector. The area was Green Plains Oil Field North and was the first sector I took.

I enabled edit objects in zeus to help with testing.
The nearest and only FOB was 1.3 km away.
The mobile spawn vehicle was in the blue capture area of the sector.
Dedicated Server - Windows Root

**Comment by ChiefOwens** [comment]
I took away permissions and reassigned them. I restarted the mission with #mission command and relaunched. Halo'd into Green Plains Oil Field North and was able to place down the sector storage at that time.

**Comment by Wyqer** [comment]
Yeah, basicly everyone with build permissions can build sector things.
But well, seems it was a "just ArmA, so restart once" event for you then ^^

**Comment by ChiefOwens** [comment]
Haven't found anything else out of the ordinary. Once again, great job!
