### ISSUE TITLE
rhs blackhawks

### ISSUE THREAD

**Issue by madpat3** [Wyqer/kp_liberation#117]
the blackhawks can't be build. you get  option to rotade them but not to build. it seems, that the helicopter stands in its own way. "1 object too close"... and that is a helicopter.

**Comment by Wyqer** [comment]
Which ones?
Just tested it after you reported it.
Testes with the Vanilla Ghost Hawk and the RHS Blackhawk and couldn't reproduce a problem with the placing.

**Comment by madpat3** [comment]
hmm, thats odd. i tried the rhs mev and the rhs armed version. both didn't work on sahrani.

**Comment by madpat3** [comment]
it's flickering like hell, like with most of the rhs units:
![20170528121618_1](https://cloud.githubusercontent.com/assets/15272840/26527965/bd79e4fe-439f-11e7-8ec2-4f0ab277c046.jpg)
![20170528121623_1](https://cloud.githubusercontent.com/assets/15272840/26527968/c37f5550-439f-11e7-979f-51f2b34b90f1.jpg)
![20170528121627_1](https://cloud.githubusercontent.com/assets/15272840/26527969/c794efd8-439f-11e7-8723-e1ad387b0d7d.jpg)

**Comment by madpat3** [comment]
see the red x with helicopter. there is no other helicopter than the one i'm trying to build.
![20170528122221_1](https://cloud.githubusercontent.com/assets/15272840/26528000/a67f4d1a-43a0-11e7-991c-22b43913b211.jpg)

**Comment by madpat3** [comment]
in the rtp file i found this:
12:15:26 Ref to nonnetwork object 92e673a040# 639717: uh60m.p3d

**Comment by Wyqer** [comment]
The rpt message is no "error" basicly. It's reported for all "preview" vehicles which you place via build menu, because they don't have activated simulation etc.

I'll check it on Sahrani now also and will report back.
Checked it on Al Rayak and Altis this morning and there where no problem at all with the RHS helicopters. If it really only happens ons Sahrani (only with the helicopters? other vehicles work fine?) it could maybe has something to do with the "ghost_spot" marker.

**Comment by Wyqer** [comment]
Well, tested on Sahrani and also no issues with that, so I can't reproduce it.
Could you maybe send me your savegame?
To do this the admin should run the following via debug console in the server:
```
mysavegame = profileNamespace getVariable GRLIB_save_key;
publicVariable "mysavegame";
```
And in one of the watch lines under the box write `mysavegame`
In the line underneath you will have a very large array. copy the whole array and post it here pls.

**Comment by madpat3** [comment]
[["capture_31","tower_13","capture_30","military_13","factory_12","capture_28","capture_27","capture_29","capture_36","capture_35","tower_5"],[[9250.49,10217,0.00141907]],[["Land_HBarrier_1_F",[9198.71,10198.8,0.0613403],64.4922,false,[0,0,1]],["Land_HBarrier_1_F",[9196.68,10196,0.122299],49.0755,false,[-0.138854,0.250207,0.958184]],["Land_HBarrier_1_F",[9197.93,10194.7,0.122711],38.7356,false,[-0.138854,0.250207,0.958184]],["Land_HBarrierBig_F",[9197.49,10219.1,0.0173492],270,false,[0,0,1]],["Land_HBarrierBig_F",[9196.88,10235.7,0.0459442],268.904,false,[0,0,1]],["Land_HBarrierBig_F",[9197.71,10203.1,0.0158081],268.734,false,[0,0,1]],["Land_HBarrierBig_F",[9197.6,10211.1,0.0110321],270,false,[0,0,1]],["Land_HBarrierBig_F",[9197.19,10227.3,0.0419312],270.633,false,[0,0,1]],["Land_HBarrierBig_F",[9199.8,10250.6,0.021225],317.257,false,[0,0,1]],["Land_HBarrierBig_F",[9196.82,10243.4,0.0122681],270,false,[0,0,1]],["Land_HelipadSquare_F",[9227.76,10111.5,0],89.367,false,[]],["Land_HelipadSquare_F",[9227.65,10133.4,0],88.2094,false,[]],["Land_HelipadCircle_F",[9225.78,10155.8,0],94.8639,false,[0,0,1]],["Land_PortableLight_double_F",[9236.45,10175.9,0.00196838],193.429,false,[0,0,1]],["Land_HBarrierBig_F",[9223.47,10187.8,0.0426788],53.5095,false,[0,0,1]],["Land_HBarrierBig_F",[9214.3,10195.1,0.0922089],0.451125,false,[0,0,1]],["Land_HBarrierBig_F",[9201.5,10197.6,0.240204],41.1593,false,[-0.169001,0.249,0.953644]],["Land_HBarrierBig_F",[9228.02,10182.4,0.076004],54.2808,false,[-0.0599988,0.197148,0.978536]],["Land_HBarrierBig_F",[9218.95,10193.5,0.107941],51.6974,false,[-0.189578,0.110736,0.975601]],["Land_HBarrierBig_F",[9232.48,10176.2,0.00857544],54.8838,false,[0,0.0421753,0.99911]],["Land_HBarrierBig_F",[9207.79,10195.1,0.266083],8.21396,false,[-0.153503,0.263861,0.952268]],["Land_HBarrier_1_F",[9218.19,10196.2,0.03508],53.6744,false,[0,0,1]],["Land_HBarrier_1_F",[9207.69,10195.6,0.070343],10.9494,false,[0,0,1]],["Land_HBarrier_1_F",[9219.33,10188.4,0.0593567],51.8552,false,[-0.0300903,0.197419,0.979857]],["Land_HBarrier_1_F",[9230.86,10179.3,-0.00283813],44.8901,false,[0,0,1]],["Land_HBarrier_1_F",[9205.3,10195.6,0.070282],8.5081,false,[0,0,1]],["Land_HBarrier_1_F",[9226.84,10184.4,0.0247498],46.4059,false,[0,0,1]],["Land_HBarrier_1_F",[9206.49,10195.5,0.0703735],8.5081,false,[0,0,1]],["Land_HBarrier_1_F",[9216.83,10192.3,0.108139],54.408,false,[-0.0296024,0.26691,0.963267]],["Land_HBarrierTower_F",[9238.39,10172.1,-1.52588e-005],1.73481,false,[0,0,1]],["rhsusf_M977A4_AMMO_BKIT_usarmy_wd",[9232.67,10192.4,-0.0310364],75.7306,false,[]],["Land_Cargo_Tower_V1_F",[9216.43,10209.7,0.202652],150.02,false,[0,0,1]],["Flag_RedCrystal_F",[9209.39,10231.9,0.0499115],265.568,false,[0,0,1]],["Land_Medevac_house_V1_F",[9208.56,10235.3,-0.120926],273.166,false,[0,0,1]],["Land_PortableLight_double_F",[9201.53,10201.9,0.0428925],248.539,false,[-0.158694,0.0752972,0.984452]],["ACE_medicalSupplyCrate_advanced",[9205.19,10236.2,1.0379],274.004,false,[]],["rhsusf_M977A4_BKIT_M2_usarmy_wd",[9236.44,10218,0.0300446],324.571,false,[]],["rhsusf_M978A4_BKIT_usarmy_wd",[9229.38,10200.9,-0.0706787],82.7444,false,[]],["Land_PortableLight_double_F",[9233.49,10259.2,0.00263977],350.685,false,[0,0,1]],["Land_PortableLight_double_F",[9202.72,10249.1,0.0923767],348.267,false,[-0.189336,-0.0504784,0.980614]],["Land_HBarrierBig_F",[9211.83,10259.4,0.0261078],0.804349,false,[0,0,1]],["Land_HBarrierBig_F",[9232.84,10265.2,0.00177002],113.431,false,[0,0,1]],["Land_HBarrierBig_F",[9228.17,10262.6,0.0170135],0.608499,false,[0,0,1]],["Land_HBarrierBig_F",[9216.79,10256.6,0.026123],90,false,[0,0,1]],["Land_HBarrierBig_F",[9233.47,10271.5,0.0161896],90,false,[-0.0123294,0.0871651,0.996118]],["Land_HBarrierBig_F",[9225.17,10257.6,0.0139923],270,false,[0,0,1]],["Land_HBarrierBig_F",[9205.38,10256.3,0.020401],315.386,false,[0,0,1]],["Land_HBarrierBig_F",[9233.28,10279.7,0.0032959],90,false,[0,0,1]],["Land_HBarrier_1_F",[9203.44,10253.1,0.0259094],138.53,false,[0,0,1]],["Land_HBarrier_1_F",[9205.48,10261.9,0.0148315],218.248,false,[-0.100707,-0.0105492,0.99486]],["Land_HBarrier_1_F",[9209.62,10254,0.0119476],255.54,false,[0,0,1]],["Land_HBarrier_1_F",[9205.46,10261.8,0.0140228],203.764,false,[-0.100707,-0.0105492,0.99486]],["Land_BarGate_F",[9220.61,10251.7,0.00419617],174.803,false,[0,0,1]],["Land_HBarrierTower_F",[9212.43,10255.1,0.0362396],172.551,false,[0,0,1]],["Land_HBarrierTower_F",[9228.07,10257.9,0.0252228],178.363,false,[0,0,1]],["Land_HBarrierBig_F",[9232.91,10287.9,0.00112915],270,false,[0,0,1]],["Land_HBarrierBig_F",[9236.02,10292.9,0.00247192],180.399,false,[0,0,1]],["Land_HBarrierTower_F",[9236.42,10289.7,0.0020752],178.965,false,[0,0,1]],["Land_Radar_Small_F",[9278.64,10097.6,0],345.403,false,[]],["BWA3_Flag_Ger_F",[9263.48,10175.5,0],193.94,false,[0,0,1]],["Land_HBarrierWall6_F",[9279.78,10173.4,0],187.957,false,[0,0,1]],["Land_HBarrierWall6_F",[9253.87,10173.7,-0.0150146],180.196,false,[-2.21138e-005,-0.00646969,0.999979]],["Land_HBarrierWall6_F",[9261.92,10174.1,0],180.196,false,[0,0,1]],["Land_HBarrierWall6_F",[9245.84,10173.4,0],180.196,false,[0,0,1]],["Land_BarGate_F",[9269.69,10175.6,0],0.846318,false,[0,0,1]],["Land_Sign_WarningMilitaryVehicles_F",[9264.81,10171.6,0],3.84265,false,[0,0,1]],["Land_Sign_WarningMilitaryArea_F",[9278.13,10169.4,0],3.15594,false,[0,0,1]],["Flag_FD_Green_F",[9247.33,10225.2,0.0268402],331.757,false,[0,0,1]],["Flag_FD_Orange_F",[9254.48,10228.5,0.0310669],322.075,false,[0,0,1]],["SignAd_Sponsor_F",[9244.26,10222.2,0.00582886],327.16,false,[0,0,1]],["Land_Cargo_HQ_V1_F",[9243.95,10228.6,-0.0599823],237.246,false,[0,0,1]],["Land_Camping_Light_F",[9244.43,10222,0.000305176],321.769,false,[-0.0664551,0.0347134,0.997185]],["Land_CarService_F",[9259.09,10244.7,0.00320435],328.621,false,[]],["rhsusf_M977A4_REPAIR_BKIT_usarmy_wd",[9266.16,10252.1,-0.0142975],160.757,false,[]],["Land_HBarrierBig_F",[9244.31,10293.3,0.00427246],359.563,false,[0,0,1]],["Land_HBarrierBig_F",[9277.29,10294.4,0.00338745],359.622,false,[0,0,1]],["Land_HBarrierBig_F",[9252.57,10293.6,0.00244141],359.762,false,[0,0,1]],["Land_HBarrierBig_F",[9260.74,10293.9,0.00234985],359.724,false,[0,0,1]],["Land_HBarrierBig_F",[9269.07,10294.2,0.00311279],359.647,false,[0,0,1]],["Land_TentHangar_V1_F",[9305.68,10107.3,0],1.58087,false,[]],["Land_PortableLight_double_F",[9284.38,10184.5,0.0231934],143.055,false,[0,0.109314,0.994007]],["Land_HBarrierBig_F",[9290.71,10187.7,0.00822449],90,false,[0,0,1]],["Land_HBarrierBig_F",[9290.82,10179.8,-0.0040741],90.8953,false,[0,0,1]],["Land_HBarrierBig_F",[9290.41,10195.7,0.0164948],90,false,[0,0,1]],["Land_HBarrier_1_F",[9289.98,10183,0.00515747],270,false,[0,0,1]],["Land_HBarrier_1_F",[9289.8,10191,0.0101929],272.002,false,[0,0,1]],["Land_HBarrier_1_F",[9289.45,10198.7,0.0102844],265.706,false,[0,0,1]],["Land_HBarrierWall6_F",[9288.77,10180,-0.0311279],91.2661,false,[0,0,1]],["Land_HBarrierTower_F",[9287.35,10174.4,0],6.90943,false,[0,0,1]],["Land_HBarrierBig_F",[9290.17,10203.7,0.0188446],89.367,false,[0,0,1]],["Land_HBarrierBig_F",[9289.97,10211.7,0.00285339],90,false,[0,0,1]],["Land_HBarrierBig_F",[9289.39,10228,0.00642395],90,false,[0,0,1]],["Land_HBarrierBig_F",[9289.28,10236.2,0.033905],91.0964,false,[0,0,1]],["Land_HBarrierBig_F",[9289.63,10219.9,0.00285339],90,false,[0,0,1]],["Land_HBarrier_1_F",[9289.13,10207,0.0110626],270,false,[0,0,1]],["Land_HBarrier_1_F",[9288.73,10215.7,0.00292969],268.499,false,[0.0185811,0.0444269,0.99884]],["Land_HBarrier_1_F",[9288.69,10223.5,0.00674438],268.826,false,[-0.0205212,0.0703251,0.997313]],["Land_HBarrierTower_F",[9285.03,10238.2,0.0614624],270.895,false,[0,0,1]],["rhsusf_m113_usarmy_medical",[9283.17,10207,0.0112915],5.91757,false,[]],["Land_PortableLight_double_F",[9282.76,10242.6,0.0080719],82.241,false,[0,0,1]],["Land_HBarrierBig_F",[9290.18,10275,0.00349426],90.633,false,[0,0,1]],["Land_HBarrierBig_F",[9290.68,10242,0.000610352],90.633,false,[0.00899414,0.0127911,0.999878]],["Land_HBarrierBig_F",[9290.56,10250.1,0.00532532],90.8953,false,[0,0,1]],["Land_HBarrierBig_F",[9290.4,10258.4,0.0164185],90.8953,false,[0.0863124,0.0363514,0.995605]],["Land_HBarrierBig_F",[9290.31,10266.7,0.00648499],91.0964,false,[0,0,1]],["Land_HBarrierBig_F",[9290.13,10291.2,0.0027771],90.633,false,[0,0,1]],["Land_HBarrierBig_F",[9285.36,10294.6,0.00143433],179.916,false,[0,0,1]],["Land_HBarrierBig_F",[9290.1,10283.3,0.0138397],91.6749,false,[0,0,1]],["Land_HBarrierTower_F",[9285.43,10290.6,0.012085],268.904,false,[0,0,1]]],0,41,[["ContainmentArea_01_sand_F",[9255.07,10184.9,0.0114746],178.055,950,1070,725,[0.00647744,0.131437,0.991303]],["ContainmentArea_01_sand_F",[9254.44,10207.6,0.00151062],54.9998,850,1750,1225,[-0.0407709,-0.0141098,0.999069]],["ContainmentArea_01_sand_F",[9263.37,10214.1,7.62939e-005],56.2576,658,1884,1334,[0,0,1]]],[["Ambergris","capture_28",0,[[7815.96,9149.79,0],87.5481,[0,0,1]],true,false,false,0,28,200,0,0],["Cedras","capture_27",0,[[7435.39,8835.08,0.000283241],259.449,[0,0,1]],false,true,false,1,26,0,0,0],["Chantico","capture_29",0,[[8277.16,8950.01,0.00115585],349.673,[0.0494414,-1.65049e-005,0.998777]],false,true,true,2,25,0,0,100],["Pesto","capture_35",0,[[10094.1,8392.91,1.52588e-005],342.616,[0,0,1]],false,false,false,3,3,100,0,0],["Playa de Dobermann","capture_30",0,[[8219.1,9669.57,0.012866],290.17,[-0.0510644,0.157476,0.986202]],false,true,false,1,21,0,100,0],["Rashidah","capture_31",0,[[9706.67,11050.4,0.0158224],41.6106,[7.75431e-005,0.183523,0.983015]],true,false,false,0,21,100,0,0],["Verda Fuel Station","factory_12",1,[[11722.8,10213.8,0.104336],240.85,[0.263171,0.358727,0.895576]],true,true,true,0,15,500,0,200],["Yoro","capture_36",0,[[9729.86,8719.91,0.00012207],294.005,[0,0,1]],false,false,false,3,9,0,100,0]],[["Alpha",1,[9713.01,11020.4,0],[9250.49,10217,0.00141907],[96400,0,0],[0,0,0],[0,0,0],1,2,3],["Bravo",1,[8248.8,9630.17,0],[9250.49,10217,0.00141907],[0,96400,0],[0,0,0],[0,0,0],1,2,3],["Charlie",1,[11747.8,10210.2,0],[9250.49,10217,0.00141907],[0,0,97000],[0,0,0],[0,0,0],1,2,3],["Delta",1,[8246.75,8981.72,0],[9250.49,10217,0.00141907],[0,0,98800],[0,0,0],[0,0,0],1,2,3],["Echo",1,[7813.4,9176.44,0],[9250.49,10217,0.00141907],[97600,0,0],[0,0,0],[0,0,0],1,2,3],["Foxtrot",1,[7412.91,8747.92,0],[9250.49,10217,0.00141907],[0,98800,0],[0,0,0],[0,300,0],2,3,0]],[0,0,24,18,1,1,0,0,15,2,0,11,88608,0,0,0,0,4486,1,11,1,4,32,0,0,1,0,41],[38,30,30],[["BWA3_Tiger_RMK_Universal","military_10"],["RHS_A10","military_7"],["rhsusf_m1a2sep1tuskiiwd_usarmy","military_18"],["RHS_AH64D_wd","military_12"],["rhsusf_m1a1aim_tuski_wd","military_3"],["B_UAV_02_dynamicLoadout_F","military_4"],["rhsusf_m109_usarmy","military_15"],["BWA3_Leopard2A6M_Fleck","military_17"],["B_T_VTOL_01_armed_F","military_2"],["B_UAV_05_F","military_1"],["B_Plane_Fighter_01_Stealth_F","military_11"],["rhsusf_mkvsoc","military_19"],["B_Plane_Fighter_01_F","military_13"],["B_T_UAV_03_dynamicLoadout_F","military_6"],["BWA3_Puma_Fleck","military"]],[],[],4,[]]

**Comment by Wyqer** [comment]
Ok, tested it with your savegame (where did you get so many resources? :D)
But well, can't reproduce the issue. I can build a RHS Blackhawk inside the base or on the runway without problems.
