### ISSUE TITLE
Add halo to respawn menu

### ISSUE THREAD

**Issue by steelbrain** [Wyqer/kp_liberation#12]
It's repetitive work to respawn somewhere, then go into the halo jump menu. It would be wonderful to have halo jump as a respawn option

**Comment by Wyqer** [comment]
But then you could only use saved loadouts.
I'll check it.

**Comment by steelbrain** [comment]
I personally used saved loadouts anyway, just set the default loadout once and it works great throughout the game

**Comment by Wyqer** [comment]
Same here. But it's something to keep in mind.
