### ISSUE TITLE
Cant use spartan on tanoa

### ISSUE THREAD

**Issue by amunoz20** [Wyqer/kp_liberation#120]
### Basic informations
**Mission version:**
0.951
**Map:**
Tanoa
**Used mods:**
RHS, CUP, Blastcore, advanced ai command towing and rapel, enhanced soundscape and dyno sound, f18, and other vest mods
**Dedicated or local game:**
Local
**GitHub or Workshop missionfile:**
Workshop

### Individual things
**Did you edit anything in the missionfile?**
No

**If yes, what did you edit exactly?**

### Short issue description
When i start a campaing in tanoa I cant use the spartan to hook FOB container, the helicopter says that is part of the paíd jet dlc and i need to buy it in order to use it

### Expected behaviour
Being able to fly the spartan

### Steps to reproduce the issue
Start a New campaing on tanoa

### Screenshots, serverlog or any other helpful things
I have tried several times and wont work even if I wipe progress. I think it May be related to the fact that in tanoa mission you dont need any mods something May be broken when mission detects other mods, or maybe has something to do with the uss freedom.. To confirm this theory i could try to start a fresh campaing on altis and report the behaviour

**Comment by Applejakerie** [comment]
The Spartan is the Huron, from the Helicopters DLC previously. Do you own that DLC?

**Comment by amunoz20** [comment]
Thanks for the fast response. Yes is the Huron, No I dont own that DLC

**Comment by Applejakerie** [comment]
You need that DLC to use the Huron. Your options are to use the RHS preset, as you're using RHS anyways. This will make Spartan a Chinook from RHS, or to have someone who owns the DLC to lift and land the container, or to start the campaign with the first FOB placed already via the mission parameters from lobby. :))

**Comment by amunoz20** [comment]
Ok so its normal behaviour then, I would need to change the preset manually or start with the FOB built. Ok stupid question alert, i have seen some missiona that say "if you own apex you will have diferent gear" is it possible to implement such thing here? Like if you dont own that dlc you start with a diferent vehicle or if it detects you have Rhs etc... Is it possible or am I high atm?

**Comment by Applejakerie** [comment]
I'm not sure what you mean by different gear to be honest. 

If you're using the Steam Workshop Tanoa Liberation mission it'll be set to use 1 of a few presets that control gameplay constants such as friendly and enemy forces. The preset you'll be using is the Tanoan preset so anything that has an APEX version, will be that instead of the original vanilla. If you load the server (so your client mods if local) to have RHS and/or BWMod, those vehicles are also included and will show for anyone who also has either/or those mods.

**Comment by Applejakerie** [comment]
The RHS and BWMod do not cross over to the enemy on this preset as that's what keeps the preset "APEX only". If there were enemy RHS, then RHS would be mandatory for everyone on the server. As they're not, you can decide which you want by loading either/or etc. Note that anyone without APEX can see/hear and sit in any APEX vehicle, they just cannot drive/pilot them. The map Tanoa however makes the mod mandatory to have by everyone tho.

**Comment by amunoz20** [comment]
Ok I understand, it seemed weird that the message whenever i try to pilot the Huron say "you need to buy jets dlc",  not helicopter dlc, it says jets... But maybe thats an error of the game itself.
Well thanks for the help! I'll try to fix it as you told me :)

**Comment by Applejakerie** [comment]
Aye that would definitely be an error on behalf of BIS, someone should maybe report that. :) Or maybe they've merged the two DLC, I don't know but that would seem unlikely. Happy playing. :)

**Comment by amunoz20** [comment]
Hi @Applejakerie I just wanted to point out that this is what I meant the other day when I said "spawn specific gear if the user owns certain DLC". It would work something like this:

if ((395180 in (getDLCs 1))) then{
	//Spawn Huron
}
else {
	//Spawn something else
};

In this particular example the if statement is checking if APEX (which is 395180) is in the list of DLCs (getDLCs) owned by the user (indicated by the parameter 1)

My idea is this:
In Tanoa, if the user has Helicopters DLC you spawn him a Huron in the USS Freedom deck, If not, you can either spawn him a V-44 Blackfish (which is alrady in Apex and sicne you are in Tanoa you need to have Apex) or somehow "force" the first FOB to spawn by itslef.

The complete list of DLCs in numeric value are this:
275700 - Arma 3 Zeus
249860 - Arma 3 Soundtrack
304400 - Arma 3 DLC Bundle
249861 - Arma 3 Maps
249862 - Arma 3 Tactical Guide
288520 - Arma 3 Karts
304380 - Arma 3 Helicopters
332350 - Arma 3 Marksmen
395180 - Arma 3 Apex

Following this example, it also may be possible (MAAAYBEEE) to check for certain mods to be loaded on the PC when the mission starts. Which means that you could check for example: if RHS is loaded use the constant preset 1 you guys configured for Liberation. This would be a dynamic set of constant preset based on the mods and dlcs that the user has. (sounds cool righ??)

I dont know if I explain myself. Yeah its true that everyone can edit the config file to add/remove the things they want but Im talking about user experience here.

If you think this idea could be interesting and need me to explain it better, feel free to hit me up on Steam: jettfiremachine

Have a great day! :)

------
References:
*For DLCs
https://community.bistudio.com/wiki/getDLCs
*Check the answer posted by nigal on August 12, 2016:
https://forums.bistudio.com/forums/topic/192495-questions-about-how-dlcapex-works-in-scenarios-for-non-owners/
*For Mods
https://community.bistudio.com/wiki/configSourceModList
https://forums.bistudio.com/forums/topic/136275-check-if-a-modaddon-is-enabled/

**Comment by Wyqer** [comment]
The Check for mods is already part of Liberation.
https://github.com/Wyqer/kp_liberation/blob/master/Missionframework/scripts/shared/functions/F_filterMods.sqf
https://github.com/Wyqer/kp_liberation/blob/master/Missionframework/scripts/shared/functions/F_checkClass.sqf

The custom.sqf and apex_tanoa.sqf unit presets are already adapt automaticly to the used mods concerning buildable vehicles etc.

> if RHS is loaded use the constant preset 1
This would restrict players too much in my opinion. As the custom.sqf is adapting to the units it would make a "you use rhs, then you have to use preset 1" and cut the possibility for the user to decide what he wants.

**Comment by amunoz20** [comment]
Thank you @Wyqer I really love this mission and I feel like doing anything to improve it. 

This whole idea of automatic presets came from the fact that I dont have Helicopters DLC, nor Jets DLC so Tanoa mission wont let me fly the damn Huron thing, and that prevents me from manually place the initiall FOB (which I think is a very importante decision, at least for me)

Replacing the Huron with the V-44 Blackfish seemed like a good choice. :)

Again thanks for you support and effort of the whole team. I have tons of ideas to improve this mission but most likely oriented to SP, the primary problem is my lack of knowledge in arma scripts... shame on me cuz Im a software developer lol

Have a good one!

**Comment by Wyqer** [comment]
For the "first FOB" issue....
People which don't have the helicopters DLC can just activate the mission parameter for starting the campaign with the first FOB already build. From there they can also build FOB trucks to establish new FOBs.
