### ISSUE TITLE
MK V SOC can't be build

### ISSUE THREAD

**Issue by madpat3** [Wyqer/kp_liberation#124]
### Basic Information
**95.1**
**Sarani**
**ACE,RHS,BW,TFAR**
**Dedicated**
**GitHub**

### Individual Things
**well, quite a lot ;)**

**custom.sqf, added some classes to build.sqf, as well as to savemanager.sqf, added an array in the kp_liberation_config.sqf, added an admin zeus**

### Short Issue Description
can't build the rhs mk v soc on water. it's flickering from red to green saying object in the way. that object is "Roadway [MkV]". Maybe the Static weapons that RHS placed on the ship.

### Expected Behaviour
should be able to be build

### Steps to Reproduce the Issue
try to build that ship

### Screenshots, Serverlog or any other helpful Information
![20170531173311_1](https://cloud.githubusercontent.com/assets/15272840/26640724/cd6f0fd4-4628-11e7-9528-79da182f73fb.jpg)
![20170531173313_1](https://cloud.githubusercontent.com/assets/15272840/26640737/d4300044-4628-11e7-8669-d8787d45ec29.jpg)

**Comment by Wyqer** [comment]
Could be the mounted HMGs, yes.
I'll have a closer look into that issue.

**Comment by Wyqer** [comment]
Tested it and don't have any issues with building the MK V SOC on land or on water.

**Comment by Applejakerie** [comment]
I have ran into this before. 

What I found was shallow water, was the cause. When trying to build the MK V SOC in deeper water, I had no issues, in shallow water the 'preview' would flicker between not being there, being there and just fine or being there but with the boat bow under water and the stern up, in the air. 

Just my input from seeing this and remembering the issue before.

**Comment by madpat3** [comment]
shallow water couldt be the cause. (only testet it on sahrani in shallow water).

**Comment by madpat3** [comment]
no, testet it also in deep water. makes no difference either in deep, shallow nor on land. cannot build it. i'll wait for the next update. maybe i made a mistake in some of the sqf's.
