### ISSUE TITLE
0.951 - Production sites not showing up in Logistics

### ISSUE THREAD

**Issue by ChiefOwens** [Wyqer/kp_liberation#125]
Went in this morning to manage logistics and I had no storage. I built new storage and went back to manage logistics. I noticed that Destination A was not visible on the trucks I had already set up. I stopped one truck to try and reassign it. I am not able to to select any of the Production sites to pick up from. The FOBS still show up.

I rebooted the mission and applied the same steps and I am still unable to select any of the Production sites but can select FOBs.

Dedicated Server
0.951

**Comment by ChiefOwens** [comment]
Taking a new sector did not fix the logistics. I can still not see production sites in Logistics.

**Comment by Wyqer** [comment]
Please provide the informations from the template, because that's all information I would ask afterwards, as I need them.

**Comment by ChiefOwens** [comment]
Sorry, didn't get the email for the request more info. Looked on Discord and seen what you posted and checked here. I can't reproduce it but I was able to fix the error.
