### ISSUE TITLE
Two markers, with the same name 

### ISSUE THREAD

**Issue by madpat3** [Wyqer/kp_liberation#127]
### Basic Information
**952:**
**Sahrani:**
**The required ones:**
**Dedicated**
**GitHub**

### Individual Things
**no**

**%**

### Short Issue Description
Marker Tiberis is doubled on map. and as a suggestion, since you turned the fuelstations into a factory, you could use a factory marker, instead of fuelstation markers.

### Expected Behaviour
%

### Steps to Reproduce the Issue
start the mission, look on map southwest and the little isle far southwest. two markers named tiberia

### Screenshots, Serverlog or any other helpful Information
%

**Comment by Wyqer** [comment]
Oh, you're right. Thanks for the hint.
