### ISSUE TITLE
Static Defenses cannot be built

### ISSUE THREAD

**Issue by Vastiny** [Wyqer/kp_liberation#129]
**### Basic Information**
**Mission version:** v0.952
**Map used:** Tanoa
**Mods used:**
**Dedicated or local game?:** Dedicated
**GitHub or Workshop mission file?** Github

**### Individual Things**

**Did you edit anything within the mission files?**
No.

**If yes, what did you edit exactly?**

**### Short Issue Description**
ALL Static defenses (HMG, GMG, mortar, etc) are unable to be placed due to the "safezone" circle constantly being too close to the player when trying to place it down.

**### Expected Behaviour**
Expected to be able to build Static defense turrets

**### Steps to Reproduce the Issue**
Open the Build menu and attempt to place any Static defense turret.

**### Screenshots, Serverlog or any other helpful Information**

**Comment by Vastiny** [comment]
Also a separate suggestion, I'll put it here since it's related to turrets.
Allowing people to build turrets "inside" other objects would be benficial to placing turrets inside of sandbag bunkers and stuff like that.

**Comment by Wyqer** [comment]
I can't reproduce the issue. Placing statics works fine without any conflict with the player who places it.
Maybe you can provide a server.rpt with activated debug messages (mission parameter).

About the turrets, I'll have a look for the next version to implement an exception for them.
Until then it is still possible to drag and carry them with for example ACE. Or in Vanilla you can disassemble them into two backbacks, lay one backpack on the ground where you want the static, carry the other there and while you've the other one on your back you can assemble them via action menu.

**Comment by Vastiny** [comment]
Strange. It's probably just something on my end related to lag then perhaps as I'm playing on a US ran server, I don't have access to the server logs. ACE would help, but an exception to placement like that would be absolutely grand!
