### ISSUE TITLE
V-44 X Blackfish (Armed)

### ISSUE THREAD

**Issue by Applejakerie** [Wyqer/kp_liberation#135]
V-44 X Blackfish (Armed) does not exist in the build menu on rhs.sqf but does exist in the elite "unlockable" menu. ^^' Maybe so for some other presets where it previously existed and we removed it from the build lists? Or vice versa? Would make the edits but I wasn't sure if you wanted them removed or added.

**Comment by amunoz20** [comment]
+1 lol I noticed this a week ago when adding new vehicles... ended up adding it cuz V-44 is SO DAMN COOL!
