### ISSUE TITLE
Continuous Exploding Vehicles

### ISSUE THREAD

**Issue by Amustillo** [Wyqer/kp_liberation#136]
### Basic Information
**Mission version:**
0.951
**Map used:**
Altis 
**Mods used:**
None
**Dedicated or local game?**
Dedicated
**GitHub or Workshop mission file?**
Workshop

### Individual Things
**Did you edit anything within the mission files?**
No

**If yes, what did you edit exactly?**

### Short Issue Description
After shooting vehicles with an RPG, the vehicle explodes and continues to explode until server is restarted. with the vehicle continuously exploding causes nothing to be accomplished until server restart... no town capping, resource gathering, and not able to build. Not Entirely sure if this is Liberation or Arma3 itself.

### Steps to Reproduce the Issue\
Shoot RPG's of any type at vehicles until 1 continuously explodes 

### Screenshots, Serverlog or any other helpful Information
Shadowplay Recording

https://youtu.be/o5NeyeIplis

**Comment by Wyqer** [comment]
Hrm, can't say why that happens. Also as you're not using any mods.
Beside of that, why are you using 951 and not 952? ;)

If you would use ACE for example there is a "cook off" on vehicles etc, but without the mod I've never seen a behaviour like that. Can you provide a log of the sessions where that happened?

But basicly I would say that's no Liberation related issue. 🤔

**Comment by Applejakerie** [comment]
We had this also, indefinitely exploding vehicles sometimes 3 or 4 times a day - have to restart to remove wreck and in turn remove the performance killer. No log error but I do think it's something new to Arma and not Liberation also. 😞

**Comment by Amustillo** [comment]
it may be possible its with the new arma 3 jets dlc update but haven't tested it. reason for not updating im not server owner just a friend. we may be going back to old liberation due to dislike of the new supply system. we usually use mods was just playing without them to get a new guy to arma series up to speed how the game works and what not. usually use RHS/CUPs mods we dont like ACE
