### ISSUE TITLE
v0.952 Production change doesnt update?

### ISSUE THREAD

**Issue by CurePindal** [Wyqer/kp_liberation#137]
### Basic Information
**Mission version: v0.952
**Map used: Altis
**Mods used: none
**Dedicated or local game? dedi KP, non-mod (also Veteran-gaming server)
**GitHub or Workshop mission file? KP server file

### Individual Things
**Did you edit anything within the mission files? no

### Short Issue Description
Product change doesnt update
Production change doesnt update 
Update only shows when re-entering the production screen

### Expected Behaviour
Production change shown when changed and confirmed.

**Comment by Wyqer** [comment]
already reported and fixed
#134
