### ISSUE TITLE
v0.952 Floating placables after reload

### ISSUE THREAD

**Issue by CurePindal** [Wyqer/kp_liberation#138]
v0.952 KP server, unmodded. No client mods.

Just entered the server and ported to FOB Alpha.
Most of the walls are floating and misaligned. Wasnt like that the last time I was on.

Pic: 
https://steamuserimages-a.akamaihd.net/ugc/841458808195679882/77E2ED28CF1F6EF48F31FDE25FC6F1EA06778ED2/

**Comment by Wyqer** [comment]
Misalignmend was always an issue in Liberation and until now there is no fix for that. There is also no real way to directly reproduce this issue. All I know is, that it happens between load and save. So from saving until loading all is as it should. After loading some of the positions in the next save are slightly changed sometimes.
If someone has a good idea or a solution, it has to be placed in the save_manager.sqf, where you also should have a look inside if you want to investigate it.

https://github.com/Wyqer/kp_liberation/blob/v0.953/Missionframework/scripts/server/game/save_manager.sqf

**Comment by Applejakerie** [comment]
Floating is new tho, we've never seen that before on our server. 🤔

**Comment by Wyqer** [comment]
Closed for now, as it's something Liberation has dealt always with and looking for a solution is a permanent task here.
