### ISSUE TITLE
suggestion: color-coding in Production screen

### ISSUE THREAD

**Issue by CurePindal** [Wyqer/kp_liberation#140]
Hello Wyqer!
I would like to suggest a color-coding for the POIs in the production screen.
Once the mission gets into the midgame the production screen becomes messy so a bit help for a better overview would be really appreciated.

A first, small enhancement would be to color-code the POIs e.g.: 
- white name for POIs with production capability 
- grey for POIs without production. 
- (optional: yellow for production POIs with placed storages)

Thanks for concidering! 
Keep up the great work!

**Comment by Wyqer** [comment]
Sounds like a good idea. Maybe like that:
* grey -> no production possible / no storage
* white -> production possible / no storage
* green -> supply production
* red -> ammo production
* yellow -> fuel production

**Comment by CurePindal** [comment]
Even better, indeed! Smart.
