### ISSUE TITLE
Suggestion: Time essential tasks

### ISSUE THREAD

**Issue by SondreBakken** [Wyqer/kp_liberation#146]
Adding on my other suggestion another things that can make things a bit more random is randomly appearing missions that has to be done within a certain time. 

So after recieving some intel you could say that one of the prisoners revealed that an officer is currently in a city, or being transported from a to b and killing him would lower opfor aggresivity by 10% but he will leave the area within 10 minutes

**Comment by Wyqer** [comment]
I like the idea. Will add some of this kind for sure. Thanks for the suggestion :)
