### ISSUE TITLE
Suggestion: Crappy infantery is crappy, but also free. No more two man army 

### ISSUE THREAD

**Issue by SondreBakken** [Wyqer/kp_liberation#150]
I play with only 3-4 friends which made the start very hard. 

I edited the files to make the most basic infantry free (short sleeves, caps and I think some of them even fought in slippers). 

So the free infantry is as bad as possible, but it helped against me and my buddy feeling like a two man army (which is not how arma is supposed to feel) for the two first hours.

Also I made two lorries free. One for carrying supplies and one for transporting people

**Comment by Wyqer** [comment]
Hrm....
personally I won't like that kind of "free stuff".
Adding it as some kind of mission parameter optional thing would be something which would work.
Maybe opinions from other players on that?

**Comment by amunoz20** [comment]
He has a point, the begining of a campaign is really hard for small groups of players (or solo players like me ohoho) 

But taking in consideration that this mission is designed for large groups of players, prices are not that bad... Options that come into my mind:

-Reduce/rebalance prices
-Add some sort of dificult parameter when game starts so it begins with more supplies 
-Add "free" units with really basic gear

Personally I found myself stuck in Altis 'cause I didnt has a transport to move resources from one place to another and neither had enough resources for a logistic truck... I had to steal a truck from a civi by killing him which was not good at all...

**Comment by Applejakerie** [comment]
I don't like the idea of trained infantry being a freeby either lol, in my eyes if the server host wants to play with free infantry, the edit is fairly easy to make and can be made whenever. I don't think a parameter or any kind of "multiple code changes" should be made for something this broken. Small or large groups, you should work for your infantry. You can get some with your starting resources and if you aim for a factory first, that's your resource production setup.

Remember, the starting helicopters are free, respawn when destroyed and lift multiple resources.

**Comment by Applejakerie** [comment]
Oh, a good tactic for those struggling to take a sector by themselves, look on Discord for people looking for a server, land/park a mobile respawn within the sector 1km circle (empty vehicles keep the sector active still as you can respawn on them almost instantly), or use a drone above the the sector to keep it active. :)

**Comment by CurePindal** [comment]
I think free infantry is good for the mission. At least as a parameter.

The Arma AI can be so damn uncontrollable and stubborn that a whole team can be wiped without a failure by the player. Thats very frustrating and the free Inv in the earlier versions really helped to reduced the frustration from this. 
Would be nice to consider adding an option for us solo players.
Thanks.

**Comment by Wyqer** [comment]
Basicly it would be more work to implement a full parameter which affects the infantry prices as the work for the one who want it to set the prices in his preset file all to 0 for the infantry.

I'll keep this suggestion still open, to give others the possibility to state their opinion on this.
