### ISSUE TITLE
Artillery support

### ISSUE THREAD

**Issue by SondreBakken** [Wyqer/kp_liberation#151]
When the commander uses the crew button to buy artillery it should add artillery support under the support tab in the menu.

I was hoping Advanced Command Ai mod would have support for this but it dont. 

Maybe one should also add an option under permissions so you could choose who could call for infantry

**Comment by Wyqer** [comment]
If you're the commander and enter zeus you can select the artillery unit, set a waypoint and switch the waypoint to "fire mission". The unit will fire artillery shells on that position until you delete the waypoint.

Beside of this method I'll have a look into that. Done that once for another mission and I remember that the support modules from BI are very strange in their behaviour sometimes.

**Comment by amunoz20** [comment]
Hi, at this time im working on the possibility to sync some units with ALiVE combat support module so it would be possible to call in for CAS attack runs, as well as Artillery Strikes if the unit built was manned. The CAS and Transport is working great by now but the Artillery is giving me some trouble... If you guys are interested in this as a solution I can share you my code to be added to main mission :D

Btw ALiVE is a super powerful tool, with it you could improve the way reinforcements work, example: add a function that, when you buy infatry, they will come in helicopter to a certain point... My point is: it would be nice to consider adding ALiVE to the base game maybe?
