### ISSUE TITLE
Suggestion: Penalty for Civilian Killing

### ISSUE THREAD

**Issue by eric963** [Wyqer/kp_liberation#154]
How about increasing the production time for producing resources a small amount each time a civilian is killed by BLUE forces.  This would simulate the people becoming unhappy due to deaths.  

Early in the campaign it would not hurt very much but as time goes by and more civs die and production times climb it could make things interesting.

Might even have a side mission to like deliver supplies to a town to lower production times a little.

**Comment by Wyqer** [comment]
Killing Civilians etc. will have much more influence in a more immersive way at 0.96.
You'll have a reputation system which will be affected by your actions.
https://forums.bistudio.com/forums/topic/202711-mpcti-coop-liberation-continued/?do=findComment&comment=3201375

**Comment by eric963** [comment]
Great!! Can't wait!!!!
