### ISSUE TITLE
.955 Slaves refuse interrogation

### ISSUE THREAD

**Issue by CurePindal** [Wyqer/kp_liberation#157]
### Basic Information
**Mission version: .955
**Map used: Tanoa
**Mods used: none
**Dedicated or local game? dedi
**GitHub or Workshop mission file? cant say

### Individual Things
**Did you edit anything within the mission files?**
no

### Short Issue Description
Captured enemies wont be interrogated:
Group leader died while he had 2 captured enemies in his group.
After respawn the slaves took a moment to be re-added to his group.
He lead them to the FOB, but they didnt sit down for interrogation.
(assumption: something broke when he, the group leader, died and the slaves got readded)

### Expected Behaviour
Captured slaves get interrogated when close enough to a FOB.

### Steps to Reproduce the Issue
I double checked the position of the captured slaves myself. My own slaves got interrogated, his just kept standing next to the FOB (close enough for interrogation)
Was late night, so unfortunatly had no time for reproduction. Sry.

**Comment by Wyqer** [comment]
Please try to reproduce this behviour and report here.
It could be that the death of the group leader could interrupt the function, I'll also have a look into this on my side.
