### ISSUE TITLE
Death back to the lobby

### ISSUE THREAD

**Issue by thirald** [Wyqer/kp_liberation#162]
Hello

I just posted a problem we meet on Liberation Malden
That's everything works perfectly, but when you die and you reappearing force back to the lobby are possible to remove this option and add the far revive just like Liberation Tanoa

This is the link of the Mission:

http://steamcommunity.com/sharedfiles/filedetails/?id=952565090&searchtext=liberation+malden

### Screenshots, 

http://image.noelshack.com/fichiers/2017/26/5/1498777646-20170630010656-1.jpg

Thank you

**Comment by Applejakerie** [comment]
This is not an option it's to do with server settings somewhere along the line, surely. It used to be an issue with swapping sides (have you done this?) but that was with FAR revive and removing it seemed to fix that issue, although it was removed for other reasons and also, removed per version, not per map. For instance, even v0.95 Tanoa does not use FAR revive. You are welcome to add it back, following the FAR script writers installation instructions should be enough.

Please use the format provided when creating an issue and fill it in with greater detail so we can look at why you might be getting kicked back to lobby per death. I have experienced this before myself and would like to see a reason so we can be better informed about what is going on, thanks. :))

**Comment by Wyqer** [comment]
As Applejakerie said: The template for issue creation is there for a reason (which is not mark all -> delete).
Please provide the informations which are asked there (as now we would start asking exactly these things which are asked in the template).
Also provide a full serverlog, where this happens to you.
Before that we can't help, as we don't have enough information.
