### ISSUE TITLE
BUG: Build FOB with more than 1 person simultanious

### ISSUE THREAD

**Issue by Kompetenzteam** [Wyqer/kp_liberation#163]
### Basic Information
**Mission version:**0.955
**Map used:**Malden (but replacable with every map)
**Mods used:**a lot but even without mods its reproducable
**Dedicated or local game?**dedicated
**GitHub or Workshop mission file?**github (but issue was is mission when zbug was Maker)

### Individual Things
**Did you edit anything within the mission files?**
nothing

**If yes, what did you edit exactly?**
nothing

### Short Issue Description
When dropping first FOB Container and two people with appropriate rights simultanious try to "BUILD FOB"... both people can place down the FOB. Both FOBs will be displayed with Model, Marker and features. Named FOB Alpha und FOB Bravo. But if you move one of the FOBs with "Unbuild FOB" and transport it away, the FOB and the Marker is beeing removed and the Trucks spawns. But the Features will stay at this position. The FOB Truck then can normaly used until "unbuild FOB" then everything again.

Maybee its possible to give every FOB a new id with precheck if this is already build? 

### Expected Behaviour
Only first Person should have the FOB beeing build, second should get a error Message "FOB already build!" (this is my wish!)

### Steps to Reproduce the Issue
As described, need two people with appropriate rights and try to build simultanious the FOB from Container. Both can place it down.

### Screenshots, Serverlog or any other helpful Information
Its easy to reproduce. No logs are beeing produced in our Server as we doesn`t have them activated.

**Comment by Wyqer** [comment]
Yeah, there is no kind of check for this situation.
Thanks for the report.
