### ISSUE TITLE
BUG: After reboot server, spawn impossible on FOB

### ISSUE THREAD

**Issue by Rius93** [Wyqer/kp_liberation#164]
### Basic Information
**Mission version:** 0.955
**Map used:** Malden 2035
**Mods used:** ACE, R3F, CBA, TFR, ...
**Dedicated or local game?** Dedicated
**GitHub or Workshop mission file?** Workshop

### Individual Things
**Did you edit anything within the mission files?**
yes

**If yes, what did you edit exactly?**
do_build_fob.sqf => _minsectordist = 0;
mission_params => CleanupVehicles, HaloJump, ShorterNights, MaximumFobs

### Short Issue Description
We deploy our first FOB Alpha in FARO. We built our defenses. We took the radio tower. No problem until now. The server rebooted and we can no longer appear on the FOB Alpha. After the reboot, we still have FARO and the radio tower in blue. Everything worked fine until the server rebooted. I try to make a wipe of the save but same problem

### Expected Behaviour
Be able to use FOBs even after a server reboot

### Steps to Reproduce the Issue
See description

**Comment by Wyqer** [comment]
Basicly that's no bug in general.
That edit is also stated as "own risk":
https://github.com/Wyqer/kp_liberation/wiki/EN:FAQ#how-can-i-build-my-fobs-closer-to-sectors

To have a closer look, please activate the debug messages in the parameters and also the savegame debug in `kp_liberation_config.sqf`

So we can have a look in the saved data.

**Comment by Rius93** [comment]
Thanks for your response
