### ISSUE TITLE
You can disassemble a mortar 'ghost' when you want to purchase one 

### ISSUE THREAD

**Issue by Aposky** [Wyqer/kp_liberation#166]
0.955 version

Go to build, select empty Mortar. Don't build. When you see a placement preview (ghost mortar), you can use scrollwheel and disassemble it into parts. It disappears from preview, but two backpack parts spawn on a ground. You shouldn't be able to do it I guess.

**Comment by Applejakerie** [comment]
Wow, nice catch!

**Comment by Wyqer** [comment]
That's "great". Many thanks for the report of this unintended possibility.
I'll have a look to prevent this.

**Comment by Aposky** [comment]
Easiest way, that I can think of is to move mortar further away from client.

**Comment by Wyqer** [comment]
Yes, that would work, sure.
I would love to fix it in a "nicer" way, but I guess it'll be the distance change to the player. Even if it feels more like a "quick workaround".
