### ISSUE TITLE
Rare and intermittent ?client? side error that Ive noticed.

### ISSUE THREAD

**Issue by Sycholic** [Wyqer/kp_liberation#167]
### Basic Information
**Mission version:** 0.955
**Map used:** Malden
**Mods used:** None
**Dedicated or local game?** Both
**GitHub or Workshop mission file?** Workshop

### Individual Things
**Did you edit anything within the mission files?** No

### Short Issue Description
Random and very rare script error popup while playing on a dedicated server.  Tried on a client/server  happened as well I believe.

### Steps to Reproduce the Issue
Unknown likely linked to respawn UI interaction.

### Screenshots, Serverlog or any other helpful Information

Script Error as follows.

21:53:28 Error in expression <
respawn_object setposATL ((choiceslist select _oldsel) select 1);
_startdist = >
21:53:28   Error position: <select _oldsel) select 1);
_startdist = >
21:53:28   Error Zero divisor
21:53:28 File mpmissions\__CUR_MP.Malden\scripts\client\spawn\redeploy_manager.sqf, line 108

**Comment by Wyqer** [comment]
I can't remember who, but this message showed up for someone before, but couldn't be reproduced directly.
Could be that it was Applejakerie.
I'll have a look into that. It's linked to the respawn / redeploy dialog, yes.

**Comment by Sycholic** [comment]
There is another issue also I noticed in the logs... and its quite the spammy one.  Soon as the mission file notice is posted..

 2:22:09  Mission id: 2887486e72aa9e6d441b4885efa15f81aa374f99
 2:22:11 Bad conversion: bool
 2:22:11 Bad conversion: bool
(repeat 600times then)
 2:22:10 "[KP LIBERATION] [DEBUG] Respawn script started for: sycholic"

pretty much on repeat...

**Comment by Wyqer** [comment]
These aren't "Liberation related" messages in the log.
This Bad conversion: bool appears on many missions (and only on local playing, not in a dedicated server log). Basically it's the same as these strange convex or Error: Bone messages in the log. Nothing to worry about concerning my information.

**Comment by Sycholic** [comment]
Ah... okay. I never seen that one before.  thanks for the fast replies and keep up the great work.

**Comment by Sycholic** [comment]
Found a way to trigger the Error Zero divisor error pretty regularly.... hit escape in the spawn menu after joining in from the lobby.

**Comment by Wyqer** [comment]
https://github.com/Wyqer/kp_liberation/commit/8b9c6fc4ac0e95902013e9505a1e7966b845e04c

I put the hashtag at the wrong position, so it wouldn't link directly -.-
Well, I couldn't reproduce that error via local game from the editor with a fresh save.
Started and on the first respawn screen, after the intro, hitting escape only reopens the respawn screen immediately. No errors on this side. The edit could maybe fix a general thing which could be connected to your issue, but I can't test it on my side.
Maybe you try it again after replacing the file in your pbo.

**Comment by Sycholic** [comment]
No luck with reinstall. it happens for both the steam workshop pbo and source code.   here's a screenie.  https://steamuserimages-a.akamaihd.net/ugc/847090634557558944/C6939138C7FE89D1130B80CD714417D92B6F6738/  this also will only show if you have -showScriptErrors for client launch (but I think you know that already)

**Comment by Wyqer** [comment]
Yes and if you start a mission from the editor you'll have automaticly activated script error showing.
So you start a fresh save, start it as mp game from the editor (I guess), select a slot, join the mission and after the cinematic you select join the fight and hit escape as soon as the deploy dialog appears?
And then you get that error?

**Comment by mwpowellhtx** [comment]
So, no one's been able to isolate in which script(s) this might ba happening?
