### ISSUE TITLE
Unable to Rearm Drones

### ISSUE THREAD

**Issue by OP-Iceman** [Wyqer/kp_liberation#168]
### Basic Information
**Mission version:** 0.955
**Map used:** Tanoa
**Mods used:** CBA, Ace, TFAR
**Dedicated or local game?** Dedicated
**GitHub or Workshop mission file?** Github

### Individual Things
**Did you edit anything within the mission files?** 
Yes

**If yes, what did you edit exactly?** 
Custom Arsenal based on killahpotatoes.sqf with less equipment; mission_params.hpp with our custom difficult settings;  ACE server config file.

### Short Issue Description
Unable to rearm UCAVs neither in containers nor trucks. Using ace_enable 0 due to ace rearm not working properly, so the vanilla rearm system is not working for rearm drones, even when someone is inside the truck and a operator in control of the "driver" position of the drone. Tried with autonomous drone settings 

### Expected Behaviour
Be able to rearm UCAVs near the container and rearm trucks using Vanilla system.

### Steps to Reproduce the Issue
Take a UCAV, drop some stores, return to base and try to rearm. With ou withot help of a second guy.

### Screenshots, Serverlog or any other helpful Information
As no messages appears and there's no error, there isn't any log.

**Comment by Wyqer** [comment]
I can have a look at this tomorrow afternoon.
It would work with ACE for sure (if it weren't broken atm). But I don't know if it's basically even possible in vanilla ArmA. That's what I've to test.
Maybe you want to have a look into that via the editor and without any mods until tomorrow.

**Comment by OP-Iceman** [comment]
I've tested on the editor without mods and with mods, with vanilla rearm and it worked. I'll try later today another test in the mission in a unmodified pbo that I use to test changes than I'll come back to tell if it worked.

**Comment by OP-Iceman** [comment]
Not working the vanilla rearm with or without mods in the mission. The drone refuel and repair, but doesn't rearms.

**Comment by FatRefrigerator** [comment]
I've rearmed a drone with vanilla before so it should be possible. I do know that in Lib sometimes things don't rearm/fuel/repair like they should.

**Comment by Wyqer** [comment]
I really can't reproduce this issue until now.
I've tested it in vanilla ArmA and also in Liberation.
If I control the UAV (I tested the Greyhawk) and drive it near an ammo truck it get's automaticly rearmed. There are no screen messages or anything else, because it's just the vanilla ArmA mechanic. But the rearming script of Liberation only adapts to player vehicles (and drones are remote controlled as they've always a driver and gunner AI "inside"). So the normal vanilla rearming take place for the UAVs.

**Comment by OP-Iceman** [comment]
Thank's Wyqer for having a look. I really don't know why our mission is not rearming the drones. The only thing I've edited was the arsenal and the params for the mission, difficult and ace_enable 0. Tried in all drones possible and none of them rearm. If i choose ace_enable 1 in the missionparam, is it possible to disable the ace rearm logic via serverconfig? I`ve been using ace_enable 0 due to ace rearm not working atm.
Once again, thank's for looking at this issue of mine!

**Comment by Wyqer** [comment]
Oh, you're welcome. I rather feel sorry about that it took me so long to really have a look at it and report back to you.

You can try to set `class ace_rearm_level` in the serverconfig of ACE to 0. Maybe that could help. At the current state (as I've tried it without ACE in both cases to be sure it workd in vanilla ArmA and vanilla Liberation) I assume that it's connected to the general issue with the ACE rearm. So I bet we can only hope for a soon release of the next patch from ACE. :o/
