### ISSUE TITLE
Side missions spawn in the water on rare occassions

### ISSUE THREAD

**Issue by Aposky** [Wyqer/kp_liberation#174]
0.955 Altis
Area of Pefkas Outpost
Side mission: rescue pilots from crash site

Hey,
yesterday we encountered this bug, where crash site spawned in water. It had soldiers patrolling around it, so they had to swim sometimes. There was an enemy tank and truck submerged or on those rocks in the picture. When we the cleared area one pilot inside a water, once I clicked capture on him, he dawned, died immediately and mission was a failure.

Pictures: https://steamuserimages-a.akamaihd.net/ugc/830202454034331017/917BB25CD6F8040B3F8E3D378EB255384A429CD4/
https://steamuserimages-a.akamaihd.net/ugc/851594469172824330/53C162A8608E45D5676C9D7AD99434511F35535A/

**Comment by Wyqer** [comment]
Hey there and sorry for the late reply.
The helicopter position is random around the defined spawnpoints for sidemissions. We can check if there are some maybe too close to the water but basicly it's something which could rarely happen, yes.
