### ISSUE TITLE
how to neded 

### ISSUE THREAD

**Issue by nifewavinsycho** [Wyqer/kp_liberation#179]
### Basic Information
I'm wanting to know some more information kind of a how to guide to adding different units to the build menu, I am wanting to add the ffaa transport ship/boat to the build menu for tanoa, might just make it a bit more interesting, I'm clueless to when it comes to editing missions
**Mission version:** 
liberation tanoa
latest update
**Map used:**
Tanoa
**Mods used:**
FFAA and a few others in the future
**Dedicated or local game?**
**GitHub or Workshop mission file?**

### Individual Things
**Did you edit anything within the mission files?**

**If yes, what did you edit exactly?**

### Short Issue Description
looking for a 'how to' guide to adding units to the build menu

**Comment by Wyqer** [comment]
Please look in the provided wiki:

Unpbo your mission, edit it and pbo it again.

https://github.com/Wyqer/kp_liberation/wiki/EN:ImportantHints

https://github.com/Wyqer/kp_liberation/wiki/EN:ConfigFiles
