### ISSUE TITLE
modifying the pbo

### ISSUE THREAD

**Issue by nifewavinsycho** [Wyqer/kp_liberation#180]
### Basic Information
so I recently asked you for help as theres no way I'm any kind of modder and your wiki guide really helped, so I hav in pbo'd your mission.... edited it.... and now I'm stuck I have no clue on what to do.... do I re pbo it or not then where do I place it so I can play it? if you can help with this little it I should be good thanks
**Mission version:**
Latest
**Map used:**
Tanoa
**Mods used:**
Plenty of different ones
**Dedicated or local game?**
**GitHub or Workshop mission file?**

### Individual Things
**Did you edit anything within the mission files?**

**If yes, what did you edit exactly?**

**Comment by Applejakerie** [comment]
😅

Question: Do I re-PBO it? 

Yes, if you are using a dedicated server (you didn't answer the dedicated or local question) then the mission file needs to be a .PBO and placed within the (usually) `mpmissions` folders of the server. You also need to direct your `server.cfg` `class Missions` there for the mission to run, like any other, which brings me to; please don't ask questions concerning "how to run a server", this is not Liberation related and we cannot support every ArmA 3 server question people would like to ask on a daily basis.

Comment: "no way I'm any kind of modder". 

Then please refrain from editing the mission file unless you are absolutely sure you won't run into any issues. Knowing things like, Liberation is not a mod and how to run a server would probably come first, no offence.

Any other issues, please fill out the form properly and with more detail than "Plenty of different ones". 😠

Please don't take any of this the wrong way, happy playing!

😅

**Comment by nifewavinsycho** [comment]
sorry this is for my own enjoyment not for dedicated server,

**Comment by Applejakerie** [comment]
Then it doesn't matter, you can use folder or PBO from the right folder.

**Comment by nifewavinsycho** [comment]
which is the right folder

**Comment by Applejakerie** [comment]
`:\Program Files (x86)\Steam\steamapps\common\Arma 3\MPMissions` or
`:\Users\LCARTER\Documents\Arma 3 - Other Profiles\Applejakerie\mpmissions`.
