### ISSUE TITLE
artillery module lost after commanders death

### ISSUE THREAD

**Issue by Aposky** [Wyqer/kp_liberation#181]
0.96 DEV Altis
Multiplayer, server
Mods server: CBA_A3, TFAR and ASR_AI
Extra Client: Achilles for Zeus

What we did:
- built a new FOB and moved there resources
- purchased mortar with crew
- BiS artillery module was active with 0-8 menu
- Commander was shot, 2x revived and respawned before I notice that menu was gone
- BiS artillery menu was gone

Adding .rpt file (yep I notice that asr_ai error :P)
[arma3server_x64_2017-07-23_20-37-48.zip](https://github.com/Wyqer/kp_liberation/files/1169902/arma3server_x64_2017-07-23_20-37-48.zip)

**Comment by Wyqer** [comment]
Thanks for the report.
I'll look into this during the development.
If you encounter more stuff, just throw it in :)

**Comment by Aposky** [comment]
Update:
When we booted server back up and continued session, the BiS artillery module was assigned back to commander. 
We played too short to confirm issue in first post.

**Comment by enxyo** [comment]
We just got the same/similar issue.
Server is set so everyone can use the support module.

While the commander can use it perfectly, the second player can't. After connecting you get the message artillery support available.
When trying to use it you get "No providers available" at 0-8-artillery strike.
After that artillery symbol on the left is gone.

One server restart before both players could use the support system. No changes between restarts where made.

We will investigate further and report back.

**Comment by Wyqer** [comment]
I guess after 0.96 I'll look back into the Artillery Support issues again. So closed for now.
