### ISSUE TITLE
Suggestion: Patrols missions

### ISSUE THREAD

**Issue by lolloscout** [Wyqer/kp_liberation#184]
Hello! I have a mission proposal for you. A new method for acquiring intelligence points: In many real-life roles the offensives are preceded by reconnaissance of some teams infiltrated into enemy territory to observe the displacements and enemy positions. Could you recreate something like that in the game? Some reconnaissance mission that provides intel points? Thank you fot the answers

**Comment by Applejakerie** [comment]
Another nice idea.
https://github.com/Wyqer/kp_liberation/issues/7

**Comment by lolloscout** [comment]
I add this in the page Applejakerie

**Comment by lolloscout** [comment]
Nevermind. I wait the permission

**Comment by Applejakerie** [comment]
Don't worry about adding it to that list, it shows as referenced so we'll see it. :smile:

**Comment by Applejakerie** [comment]
That's why I added the # links.

**Comment by lolloscout** [comment]
Yeah. I saw it now. Perfect. One question, how many devs are working on Liberation now?

**Comment by Applejakerie** [comment]
Just the 1 dev, Wyqer. I help with all things non-SQF. ^^;

**Comment by lolloscout** [comment]
thank you so much! I appreciate your work
