### ISSUE TITLE
Suggestion: Sniper missions

### ISSUE THREAD

**Issue by lolloscout** [Wyqer/kp_liberation#185]
Forgive me if i'm intrusive. This is another mission suggestion: 
The elimination of priority targets as enemy officers / colonies to lower enemy alerts. This would be a good simulation of the fact that the player cuts enemy lines of command making them unable to organize well for some time. I hope you like it.

**Comment by Applejakerie** [comment]
Nice idea, already planned. :wink: 
https://github.com/Wyqer/kp_liberation/issues/7
