### ISSUE TITLE
Micro sttuttering issue

### ISSUE THREAD

**Issue by HeliceWolf** [Wyqer/kp_liberation#186]
### Basic Information
**Mission version:0.955**
**Map used: Chernarus**
**Mods used: CBA, ACE, RHSAFRF, RHSUSAF, Ace Compat RHSAFRF, Ace Compat RHSUSAF, Advanced Urban Rapelling, Enhanced Movement, Suppress, Immerse, CUP terrains core and CUP terrains maps**
**Dedicated or local game?: DEDICATED server**
**GitHub or Workshop mission file? Github**

### Individual Things

**Did you edit anything within the mission files?**
Yes.

**If yes, what did you edit exactly?**

Edited ui\mission_params.hpp to avoid change parameters every time i start the server.
Edited to have full zeus with instructions on: https://github.com/Wyqer/kp_liberation/wiki/EN:FAQ#how-can-i-enable-full-zeus
But now i dont have full zeus. Since the problem starts i tried a clean github file mission. But same problem.

### Short Issue Description

After we have 16 production facilities running and their logistics to send everything to a couple of FOB (with the 100000, 100000, 100000 method) the game makes micro sttutering every 5-6 seconds like a clock to everyone. If i wipe the savegame the problem is solved but we would like continue the mission.

We tried a second server more powerful (i7-7700k instead the regular AMD FX8320 both 16GB RAM) and the problem is the same.

### Expected Behaviour

One think i cannot understand is why there are 288 vehicles with the server just restarted. We use reduced civilians. No idea if can be part of the problem.

### Steps to Reproduce the Issue

I think the easy way is use my savegame (attached with RPT)

### Screenshots, Serverlog or any other helpful Information
RPT with server parameter debug ON and the savegame if you want to see it by yourself.

[microstutteringRPTandSAVEGAME.zip](https://github.com/Wyqer/kp_liberation/files/1183361/microstutteringRPTandSAVEGAME.zip)

**Comment by Applejakerie** [comment]
This is very descriptive thanks. Currently there's a bit of an "away" period with development but that's due to end soon enough and this will be looked into as soon as possible, I'm sure. As for the 288 vehicles, these are just objects, anything from resource crates to pre-placed enemy military sectors, even weapons on the ground count towards this whilst they are there. This is nothing to worry about.

**Comment by Wyqer** [comment]
The production and AI logistic couldn't cause a 5-6 stutter interval. They just run every minute. As I'm "really back" in 2 days, I'll have a look at the log.
