### ISSUE TITLE
Suggestion: Make it require supplies to spawn at a mobile respawn

### ISSUE THREAD

**Issue by Freddo3000** [Wyqer/kp_liberation#187]
The thought behind this is that the mobile respawn is a bit powerful, due to the enemies ability to target and destroy it. It discourages waiting for revives and makes it so that you don't really have to care about if you die or not. It allows players to quite easily succeed in taking towns by simply rushing, respawning, and rushing again.

So to counter this, the idea is that the mobile respawn will have an internal buffer of supplies and/or ammo that will be drained as people respawn, with the buffer being somewhere around 100 resources and draining 10 or so per respawn.

On top of this, it might be worth making it cheaper to respawn at a ground vehicle, rather than a helicopter.

Thoughts?

**Comment by Applejakerie** [comment]
I like this, mind you I don't know about it costing resources. 

How about more like, a parameter option to select a respawn limit for the Spartan 01 and another parameter for medical vehicles past that. So you could, say, have it so Spartan 01 allows for 50 respawns before needing to be taken back to an FOB where it can "recharge" (1 per 30 seconds maybe). For the medical vehicles, you could have a lower more sensible value at 25 say and again, once depleted these vehicles need to "recharge" local to an FOB.

**Comment by Applejakerie** [comment]
We were at one point looking to have the enemy attack empty vehicles but not sure if it's any easy possibility with regards to BIS functionality, still something to be looked into I think.

**Comment by Freddo3000** [comment]
I'd argue that the truck should have more space for "Respawns", while it does not really make sense, something has to compensate for the lack of mobility compared to the Huron.

On the topic of vehicles, perhaps spawning a hidden AI with simulation disabled inside the vehicle is an option, making the AI target it as it is "blufor controlled"?

**Comment by Applejakerie** [comment]
Personally I couldn't decide between either, the truck being limited because it's just a truck and not THE Spartan 01 which is primarily the #1 mobile respawn or if like you say, it should be the Spartan 01 that is limited further due to it's extreme mobility. It's good to remember there is any amount of mobile trucks tho and only one Spartan 01.

**Comment by Applejakerie** [comment]
The hidden AI is a good idea, one we had before too but it didn't seem to work suitably. 

Thanks for the great suggestions.

**Comment by lolloscout** [comment]
I think this is bad for a small group of players

**Comment by Freddo3000** [comment]
@lolloscout How so? If anything, smaller groups should be able to deal with this easier than larger ones.

**Comment by Applejakerie** [comment]
Although we support small groups of players, Liberation is primarily a large scale CTI. The idea between keeping this as a parameter would be that you could have anywhere from 5 respawns per vehicle to an infinite amount of respawns, as it is now, however. Also I agree with Freddo, this would make your lives easier than larger groups.

**Comment by Freddo3000** [comment]
Perhaps have it be something like 2X or 0,5X where X is the number of players, for respawn slots. Perhaps also a minimum of around 5 or so respawns?

**Comment by Applejakerie** [comment]
That works too but not sure how it would update regarding new players joining without constant loops. Not my area however so I'll leave that. Minimum would be 0, given there is already a parameter to disable mobile respawns entirely. :wink:

**Comment by lolloscout** [comment]
Okok nevermind. You're right guys, i hate the fact that a respawn point become a easy way to take sectors. I think that this can be an option in the parameters menu

**Comment by enxyo** [comment]
Respawn slots/tickets are a nice idea, a cooldown timer like with the halo jump would probably encourage more teamplay and going for the revive.

**Comment by Aposky** [comment]
I like it. Manpower should cost us resources. Please make cost of respawn adjustable.

**Comment by XLpacman805** [comment]
I vote no on this. The Mobile respawn is the workhorse when you first start out and don't have a lot of resources.

**Comment by FatRefrigerator** [comment]
I love this idea because it forces you to think and not be a human wave.

**Comment by Wyqer** [comment]
It won't cost resources. Guess that would be too much micromanagement for most groups.
Added a parameter instead to set a cooldown for mobile respawning (default 15 minutes).
