### ISSUE TITLE
Suggestion: Custom placed objects/units in zones

### ISSUE THREAD

**Issue by Freddo3000** [Wyqer/kp_liberation#188]
To simply put, having the option to sync units and/or structures to objective markers, making them only spawn when the zone is active, perhaps leaving the static guns and structures around until the next server restart.

**Comment by Applejakerie** [comment]
So, you'd like more control over sector defenders? How they spawn, what they spawn with?

**Comment by Freddo3000** [comment]
In short.

**Comment by Freddo3000** [comment]
Rather what will spawn on top of what is already there.

**Comment by Applejakerie** [comment]
Well, with 0.96 comes a huge AI overhaul. This might (I'm pretty sure it will) remove the sector defenders entirely. I think a great idea is being able to build statics, sandbag walls etc at any sector, knowing they will stay for the rest of the campaign and on top of them, defenders will spawn when the sector is attacked. Gives a way of paying for added protection but you know the enemy, they're likely to stroll up one time with a few too many tanks and absolutely obliterate any fortifications.

**Comment by Freddo3000** [comment]
Seems like I wasn't clear enough when it came to this. I meant that the enemy sectors would have the preplaced things. I've already read that friendly sector building is in consideration, but this was rather to give the enemy some extra fortifications/units.

**Comment by Applejakerie** [comment]
This is also an idea planned, if not written down. Statics primarily, in a way that doesn't mean there is opportunity for a guy to be arming a static, facing a wall, etc.
