### ISSUE TITLE
Suggestion: Dangerous Enemy Airspace

### ISSUE THREAD

**Issue by lolloscout** [Wyqer/kp_liberation#189]
Today this is my 3° suggestion. You are hating me! I wrote this in the comment section of another suggestion and i don't know if you remember it: It would be cool to have OPFOR heli-patrols (I find it strange that I am invading an enemy-controlled territory but I can safely fly over their airspace by helicopters and airplanes.)
Jets can be OP with missiles and the new radar system, but transport helicopters (with MG/miniguns) can spawn in random positions and patrol the OPFOR airspace and defend it against players helicopters.

**Comment by Wyqer** [comment]
Maybe you should have a look in the planned things for 0.96 ;)
https://github.com/Wyqer/kp_liberation/wiki/EN:0.96

**Comment by lolloscout** [comment]
Thanks Wyqer
