### ISSUE TITLE
Civilian evacuations

### ISSUE THREAD

**Issue by FatRefrigerator** [Wyqer/kp_liberation#201]
There might want to be a function where you can evacuate civilians. Maybe spend intel or some other liberation currency to "warn" civilians of the coming attack. This will make the enemy more aware of your attack so they will be greater in number and not spawn in "safe" mode, but there won't be any civilians or their vehicles in the town.

**Comment by abunchofscience** [comment]
Perhaps using something like the new pamphlets in the laws of war DLC could work for this?

**Comment by FatRefrigerator** [comment]
They could certainly be used as a visual aid for this
