### ISSUE TITLE
Suggestion: Make it SP friendly

### ISSUE THREAD

**Issue by leopard20** [Wyqer/kp_liberation#208]
The original version is SP compatible and has no limitations (for example, when I try to buy the night stalker scope it says it's not allowed).

**Comment by Applejakerie** [comment]
The game is already SP compatible, it is however more driven towards MP. You can disable arsenal blocks within the lobby parameters or you can remove the scope classname from the `blacklisted_from_arsenal` array in `kp_liberation_config.sqf`. 

Change: 
`	"RHS_SPG9_Gun_Bag",
	"RHS_SPG9_Tripod_Bag",
	"optic_Nightstalker",
	"optic_tws",
	"optic_tws_mg"
`
to:
`	"RHS_SPG9_Gun_Bag",
	"RHS_SPG9_Tripod_Bag",
	"optic_tws",
	"optic_tws_mg"
`
Notice that there is no comma on the last entry, this is intentional and needs to be exact.

Other recommendations whilst running it in SP include putting the unit cap lobby parameter at 50%. You can edit the `mission_params.sqf` file to change lobby parameter defaults so you don't have to do this every session.

**Comment by Wyqer** [comment]
The old 924 version has also limitations. What is "SP compatible" for you? Without further details this phrase hold no information.
As Apple said you can play the mission without problems as SP.

Concerning limitations in 924:
Line 305
https://github.com/GreuhZbug/greuh_liberation.Altis/blob/master/classnames_extension.sqf

**Comment by leopard20** [comment]
> What is "SP compatible" for you?
Sorry, I meant SP friendly! 
Also, in the original version there was an option that replaced crates with passive income (so I didn't have to go all the way over to the bases to collect the crates, come back and recycle them)

**Comment by Applejakerie** [comment]
🙂 No worries!

1. There is still a passive income feature, it just requires some work, like an "investment" to get it setup. This takes away the magical give me resources dependent on progress and creates a virtual reality regarding how you would justify gaining resources. See these two links for further details:

- https://github.com/Wyqer/kp_liberation/wiki/EN:Production
- https://github.com/Wyqer/kp_liberation/wiki/EN:Logistic

Specifically: 

- https://github.com/Wyqer/kp_liberation/wiki/EN:Logistic#creating-a-passive-income

2. Even with the resource multiplier at 1, myself and team of say 5 max always run into "too many" resources, once we set it up passively 95% of the game the trucks are waiting on standby as I have nowhere else to store more resources. 😅

As far as I was aware, the Unit Cap is how many sectors would activate at a time. So if 8 sectors would activate on 100%, only 4 would activate on 50% and the same response would work for reinforcements and battlegroups too. As one person, you wouldn't need 4 sectors at once, let alone 8. It's just a recommendation to help keep the local host server clean and running well. If it's fine already, I wouldn't worry about it for the most part.

1. Secondary objectives you can access and initiate via the scroll menu at an FOB. They cost intel, which is gained by bringing prisoners back to an FOB or finding intelligence laptops around military bases. They each come with their own rewards, an FOB hunt would be the best for lowering the enemy alert.
2. There's no possibility of updating between new versions, only hotfixes of the same versions, so 0.924 won't update to 0.955 without wiping your save unfortunately. You could always "cheat" your way back to a similar progress using an unlocked Zeus, see here:

- https://github.com/Wyqer/kp_liberation/wiki/EN:FAQ#how-can-i-enable-full-zeus

**Comment by leopard20** [comment]
> There's no possibility of updating between new versions

Pity, I put a lot of work into the old one!

**Comment by Wyqer** [comment]
Nothing force you to use the latest version. Just finish your actual campaign and change afterwards. :)

**Comment by leopard20** [comment]
Yeah. I know!
One thing I forgot: Can you increase the amount of resources at startup? At least enough to create a darter and a light rifle squad, which is 20 green resources (don't know what it's called!) and 5 fuel.

**Comment by leopard20** [comment]
Ok I just actually played your mission and I must say the unit and asset costs are unreasonably high. The original version costs were much better. This makes me resort to cheating! (using full zeus to create something like M5 sandstorm and then recycle them). Can you create a parameter like "cost multiplier" (with options lower than 1 of course!)?

**Comment by Wyqer** [comment]
No, there'll be no multiplier parameter, as everyone can just edit the prices to their own likings in the preset file. A multiplier is unnecessary code.

**Comment by Applejakerie** [comment]
Just wanted to clarify, those hummingbirds won't explode if you give the mission 20 seconds to load entirely. When you load into the briefing screen, you'll see the map and mission sector icons, find a base and wait for the locked "elite" vehicle to show above it, as these are the last things to load in on the map. Starting the mission and hitting go instantly; that causes the hummingbirds to clip and explode.

Also, the "cost" multiplier would be the same as the resource multiplier but in a different direction, so entirely redundant and as Wyqer said, you can change the costs within the preset files but honestly, you should quickly realise you'll have more resources than you can spend. Capture 3 sectors, have these 3 sectors produce each resource type respectively, have logistics carry those resources back to your FOB on an infinite loop, all explained within the Wiki. You'll have more resources than you can spend in a realistic, milsim and co-operative environment. Remember, you're not buying vehicles per sector operation, you should be buying and preserving a vehicle, the entire campaign.

**Comment by leopard20** [comment]
OK, so I reduced all unit costs in the preset but I don't know how to reduce squad costs!

**Comment by Applejakerie** [comment]
It's the `scripts\shared\classnames.sqf` file. 

Top of that is...

`squads = [
	[blufor_squad_inf_light,200,0,0],
	[blufor_squad_inf,300,0,0],
	[blufor_squad_at,200,250,0],
	[blufor_squad_aa,200,250,0],
	[blufor_squad_recon,250,0,0],
	[blufor_squad_para,200,0,0]
];`

**Comment by leopard20** [comment]
@Applejakerie Thank you!
