### ISSUE TITLE
Suggestions: Use CUP units instead of Project OPFOR in Takistan

### ISSUE THREAD

**Issue by leopard20** [Wyqer/kp_liberation#209]
Can you use CUP units instead of PROJECT OPFOR? (or add compatibility for both)
It's just that my mod list is way too long already! (Check out below!)
`

	class Mod1
	{
		dir="@CBA_A3";
		name="Community Base Addons v3.3.1";
		origin="GAME DIR";
		fullPath="E:\ARMA 3\@CBA_A3";
	}
	class Mod2
	{
		dir="@CUP_Terrains_Core";
		name="CUP Terrains - Core 1.3.0";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@CUP_Terrains_Core";
	};
	class Mod3
	{
		dir="@CUP_Terrains_Maps";
		name="CUP Terrains - Maps 1.3.0";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@CUP_Terrains_Maps";
	};
	class Mod4
	{
		dir="@RHSUSAF";
		name="RHS: United States Forces";
		origin="GAME DIR";
		fullPath="E:\ARMA 3\@RHSUSAF";
	};
	class Mod5
	{
		dir="@RHSAFRF";
		name="RHS: Armed Forces of the Russian Federation";
		origin="GAME DIR";
		fullPath="E:\ARMA 3\@RHSAFRF";
	};
	class Mod6
	{
		dir="@RHSGREF";
		name="RHS: GREF";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@RHSGREF";
	};
	class Mod7
	{
		dir="@RHSSAF";
		name="RHS: Serbian Armed Forces";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@RHSSAF";
	};
	class Mod8
	{
		dir="@CUP_Weapons";
		name="CUP Weapons 1.9.1";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@CUP_Weapons";
	};
	class Mod9
	{
		dir="@CUP_Units";
		name="CUP Units 1.9.1";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@CUP_Units";
	};
	class Mod10
	{
		dir="@CUP_Vehicles";
		name="CUP Vehicles 1.9.1";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@CUP_Vehicles";
	};
	class Mod11
	{
		dir="@ACS_MOD";
		name="Advanced Comand System";
		origin="GAME DIR";
		fullPath="E:\ARMA 3\@ACS_MOD";
	};
	class Mod12
	{
		dir="@ace";
		name="Advanced Combat Environment 3.10.1";
		origin="GAME DIR";
		fullPath="E:\ARMA 3\@ace";
	};
	class Mod13
	{
		dir="@TPW_MODS";
		name="TPW MODS";
		origin="GAME DIR";
		fullPath="E:\ARMA 3\@TPW_MODS";
	};
	class Mod14
	{
		dir="@ASR AI 3";
		name="ASR AI3";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@ASR AI 3";
	};
	class Mod15
	{
		dir="@JSRS_SOUNDMOD";
		name="JSRS Soundmod - 5.17.0630";
		origin="GAME DIR";
		fullPath="E:\ARMA 3\@JSRS_SOUNDMOD";
	};
	class Mod16
	{
		dir="@TracerMod";
		name="Tracermod";
		origin="GAME DIR";
		fullPath="E:\ARMA 3\@TracerMod";
	};
	class Mod17
	{
		dir="@BaBe_midTex";
		name="@BaBe_midTex";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@BaBe_midTex";
	};
	class Mod18
	{
		dir="@LI";
		name="@LI";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@LI";
	};
	class Mod19
	{
		dir="@Resist";
		name="Resist";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@Resist";
	};
	class Mod20
	{
		dir="@F14_Standalone";
		name="F-14D Tomcat";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@F14_Standalone";
	};
	class Mod21
	{
		dir="@JS_JC_SU35";
		name="Su-35 Flanker E";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@JS_JC_SU35";
	};
	class Mod22
	{
		dir="@FIR AWS(AirWeaponSystem)";
		name="FIR AIRWEAPONSYSTEM";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@FIR AWS(AirWeaponSystem)";
	};
	class Mod23
	{
		dir="@HCC - High Command Converter 1.5.1";
		name="High Command Converter 1.5.1";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@HCC - High Command Converter 1.5.1";
	};
	class Mod24
	{
		dir="@simple_rp";
		name="Simple Rank Patches v1.4.2";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@simple_rp";
	};
	class Mod25
	{
		dir="@Earplugs";
		name="Earplugs";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@Earplugs";
	};
	class Mod26
	{
		dir="@WW_AIMenu";
		name="@WW_AIMenu";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@WW_AIMenu";
	};
	class Mod27
	{
		dir="@DCE";
		name="@DCE";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@DCE";
	};
	class Mod28
	{
		dir="@Elite Warriors Stamina Carry Capacity";
		name="@Elite Warriors Stamina Carry Capacity";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@Elite Warriors Stamina Carry Capacity";
	};
	class Mod29
	{
		dir="@HC_Transport";
		name="@HC_Transport";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@HC_Transport";
	};
	class Mod30
	{
		dir="@T_Helmetcam";
		name="Helmetcam liveFeed (by Tajin)";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@T_Helmetcam";
	};
	class Mod31
	{
		dir="@support";
		name="@support";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@support";
	};
	class Mod32
	{
		dir="@tao_foldmap_a3";
		name="Tao Folding Map";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@tao_foldmap_a3";
	};
	class Mod33
	{
		dir="@zbe_cache";
		name="@zbe_cache";
		origin="GAME DIR";
		fullPath="e:\ARMA 3\@zbe_cache";
	};
};`

**Comment by Wyqer** [comment]
Liberation has compatibility with "everything" concerning adding classnames of vehicles.
Your mod list is by the way nothing which would be needed for this question (don't get me wrong, no offense).
Just edit your preset file with CUP classnames and you're ready to go.
Have a look here:
https://github.com/Wyqer/kp_liberation/wiki/EN:ConfigFiles#presetscustomsqf

Personally I won't create a preset with CUP vehicles, as I've never used that mod, because I don't like the vehicles, units or weapons from CUP. If you finish a "full CUP preset" you could contribute it, so it can be implemented in the preset list.

**Comment by leopard20** [comment]
> no offense

None taken.

> I don't like the vehicles, units or weapons from CUP

CUP units are okay actually :) It's the vehicles and weapons that look bad.

>  If you finish a "full CUP preset" you could contribute it, so it can be implemented in the preset list.

I'll give it a shot!
