### ISSUE TITLE
suggestion permanent indication 

### ISSUE THREAD

**Issue by madpat3** [Wyqer/kp_liberation#211]
when a certain amount of spawned units on the server is reached, the mission informs you about the sectors, where units can be spawned.

this should be indicated permanently. 

because after time you may forget about that. then after traveling maybe long distances you get to a sector and wonder why there are no enemy units.

**Comment by Wyqer** [comment]
There is already a permanent hint in the bottom right corner if too many sectors are activated. If this hint shows up, no other sectors can be activated, so in no other sectors will spawn any unit until there aren't that much other sectors activated.
Until this hint isn't showing up, there is no "nothing can spawn" functionality.

**Comment by madpat3** [comment]
yes, but the hint disappears over time and the unit spawn is still limited to certain sectors.
