### ISSUE TITLE
Invincible Jet Pilot

### ISSUE THREAD

**Issue by ildolore** [Wyqer/kp_liberation#218]
### Basic Information
**Mission version:** 0.955
**Map used:** Sahrani
**Mods used:** ace, rhs, cups, align, immerse, suppress, adv ai command, project uncut
**Dedicated or local game?** local
**GitHub or Workshop mission file?** workshp

### Individual Things
**Did you edit anything within the mission files?**
no

**If yes, what did you edit exactly?**

### Short Issue Description
Shot down a jet, the pilot was invincible and attacked the FOB until he ran out of pistol ammo. The ai guards then chased him across the map.

**Comment by Wyqer** [comment]
Is this reproducable for you?
Do you have any logs where you encountered helpful informations?
If you're able to reproduce it, try if it still happen if you play without any mods.

**Comment by ildolore** [comment]
It was only the second jet and first pilot I've seen in mission. If it happens again I'll update.

**Comment by lolloscout** [comment]
Same problem happened everytime when i played Liberation on Chernarus.

**Comment by Wyqer** [comment]
Checked it here and got no issues with a pilot from a spawned enemy aircraft.
Keep me updated, if you're able to resproduce it to 100% with the exact steps and circumstances.

**Comment by SunStalker** [comment]
Happened to us with the RHS Preset. Shot down pilot from FOB Attackforce was invincible.
