### ISSUE TITLE
Suggestion: Add spare wheels and treads

### ISSUE THREAD

**Issue by jweisner** [Wyqer/kp_liberation#225]
Our players are robbing civilians for their tires.

Maybe add `ACE_Wheel` and `ACE_Track` to the buildable items?

Something like...
```
[ACE_Track,50,0,0],
[ACE_Wheel,10,0,0],
```

**Comment by Wyqer** [comment]
It's already added since August 9th in the 0.96 dev :)
https://github.com/Wyqer/kp_liberation/commit/fef06e91eea3579931b91e2b01620fe807491426#diff-f46e8fc3c1ab862797d3725d0eae237b
