### ISSUE TITLE
RHS MK V SOC (boat) build radius and protected area overlap

### ISSUE THREAD

**Issue by SunStalker** [Wyqer/kp_liberation#230]
### Basic Information
**Mission version:** 0.96 dev
**Map used:** Tanoa
**Mods used:** RHS, ACe
**Dedicated or local game?** Ded
**GitHub or Workshop mission file?** GitH

### Individual Things
**Did you edit anything within the mission files?**
Yes, nothing related

**If yes, what did you edit exactly?**

### Short Issue Description
When trying to build a MK V SOC boat (RHS), the player trying to build it is standing in the circle, so you can't build it because there is an object in it.

### Expected Behaviour
If the circle is 1 meter smaller or the boat 1 meter further away it would let you build it.

### Steps to Reproduce the Issue
Try to build RHS Boat MV V SOC

**Comment by madpat3** [comment]
try to add "Land_MkV_Roadway", into presets>init_presets.sqf>line84 and following.
