### ISSUE TITLE
Stack and Sort

### ISSUE THREAD

**Issue by SunStalker** [Wyqer/kp_liberation#233]
### Basic Information
**Mission version:** 0.96
**Map used:** Tanoa
**Mods used:** Arma, RHS
**Dedicated or local game?** Ded
**GitHub or Workshop mission file?** GitHub

### Individual Things
**Did you edit anything within the mission files?**
No, fresh download from Master.

**If yes, what did you edit exactly?**
/

### Short Issue Description
Using Stack and sort on the storage gives 1 error per box and the boxes go airborne.

### Screenshots, Serverlog or any other helpful Information
[rpt.txt](https://github.com/Wyqer/kp_liberation/files/1383629/rpt.txt)

**Comment by dvdbrewster** [comment]
Y our fob would unload them from the storage right in fron of your nose.. did't lose any, but had to store them again.
