### ISSUE TITLE
Feature Suggestion: Civilian Aid Side Ops

### ISSUE THREAD

**Issue by chrisleaptrott** [Wyqer/kp_liberation#234]
In keeping with the spirit, not necessarily the stuff in there since you can do things with Vanilla equipment, but it would be really cool to have some side missions that were on the humanitarian support side of things. The reward would be some CIV rep boosts. Failing could result in loss of rep.
Some thoughts would be:
1: Deliver relief supplies to Civilians in an occupied area. Like others, this would spawn in some CIVs gathered as the objective. They would be there to get some boxes that might have food or other supplies (in the narrative sense) and the players have to get it in there to them....the enemy may wish to stop this. You have your conflict of how to go about it. Mission wins when the crate gets to the objective (AA might make it hard to just drop things, etc....or make it a truck of things....but ensure slingload.)
2: IED clearing: Very minor rep reward mission that would spawn in an IED in a friendly controlled area. Players must go and defuse....the problem being that AI CIV traffic could very well set it off. Low reward/penalty.
3: Mine-clearning: Spawns a point in BLUFOR controlled areas (near by, appropriate area far enough away and off of things. Basically like a up-scaled version of the IED, but off in an area that shouldn't have much 'traffic'.
4: Flyer dispersal: Something that gives a low reward and lets people use the LoW stuff in fun way...just get your UAV into a controlled area to toss out some fliers....mission fail if the UAV is lost before the pamphlets are dispersed.

I'm going to take a look into the framework and see about possibly coding one or two of these in and tossing them your way if interested.

LOVE the CIV stuff in the new version :D

**Comment by chrisleaptrott** [comment]
Hey, I've done a reworking of the Convoy side mission to have it reward CIV rep instead of drop alertness. I've found in the many times I've played through Lib with a group that people rarely ever do the Convoy mission, so the idea came to me to change it to be useful in providing CIV rep.
I'll do a PR with the files if you guys want to look at it or whatever.

**Comment by ildolore** [comment]
Hey this is a super idea.
Since the update to civ/repo points. I've never intentionally hurt them but they randomly run around in battle zones and they get killed. I accidentally one with a truck - he ran directly at me while driving at high speed. I tried to avoid him but he died, i wasn't able to revive him. 
Unless i've just been super unlucky, i feel like i'll never reduce my rep (it's -25 atm).
Side missions of relief or mine clearing are excellent ideas. 

I was thinking that Supply or Fuel (not ammo i guess) could be sent (logistics menu or by myself) to a village to gain rep.

Great work!

**Comment by Wyqer** [comment]
More possibilities/sidemissions are already planned for the upcoming patches to extend the ways to influent the civil reputation. Consider the current functionality of the civil reputation in 0.96 as a "general working framework" which will now be built on.
