### ISSUE TITLE
Liberation cont.  .96 

### ISSUE THREAD

**Issue by dvdbrewster** [Wyqer/kp_liberation#235]
### Basic Information
**Mission version:**  .96  .  APEX  presets  blu,op,res,civ.
**Map used:**Tanoa
**Mods used:**cba,ace,cupmappak,mao-bloodmist,ewk_cigs. 
**Dedicated or local game?**ded, 2x hc's
**GitHub or Workshop mission file?**wip

### Individual Things
**Did you edit anything within the mission files?**
params,presets.

**If yes, what did you edit exactly?**
presets,params

### Short Issue Description
Its confirmed ,  A restart is required here after every town capture. (blu town indicator..red letters..no enemies, no civs)'
I notice on the map screen when jining-everytime- the HC's show 50 fps, and the server always shows 2.0
or less. weird 'cause this would prevent ais loading..but there was never any message. I have the 2 hc's but ai cap is just 100%(ded server recommended).(fears of overload from zbugs  days).

### Expected Behaviour
something normal.. I played exact mods on previous vers (.95).   

### Steps to Reproduce the Issue
load up

### Screenshots, Serverlog or any other helpful Information
Ive been running logs off,  I can redefine and restart for u.

https://www.dropbox.com/s/xlijxkmq8w7rm40/arma3server_x64_2017-10-14_16-49-32.rpt?dl=0

here the rpt file.. fresh start /o mods...Fresh started serer 1 hc.. cba/ace.. ace server.  Captured 1 radio tower.. moved to recon the "camp" and there was no enemies.  @18:19 I restarted mission..  I had mayN this was a good idea so can reference the time of the occurrence. MayB not if it doesn't make a difference if U have captured a town or not. ! several respawns to capture radio tower , the enemies were always there(didn't despawn b4 the capture). I'll send my server config. for the ace server mod if u want it.

**Comment by Wyqer** [comment]
Was already fixed with: https://github.com/Wyqer/kp_liberation/commit/5958a099c4b7ddb7ec6f56b884a1f0b70c7586a8

But also made another solution which I prefer. Commiting in a few minutes.
