### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by killing3mark** [Wyqer/kp_liberation#238]
### Basic 
**Mission version:v 0.961
**Map used:Malden
**Mods used:Rhs, cup,  advanced mods(sling loading...)
**Dedicated or local game? Local
**GitHub or Workshop mission file? Github

### Individual Things
**Did you edit anything within the mission files?**

No
**If yes, what did you edit exactly?**

### Short Issue Description

I can't edit permissions for individuals it edits them for all, if I click for example to disable building for a certain player it disables it for  all.
### Expected Behaviour

Individual permissions

**Comment by Wyqer** [comment]
So you have the list of permissions with the names of the players listed under the default line.
And when you click, for example, on the permission to pilot air vehicles from one player this permission will get red for every player and not just the one at which line you've clicked on the permission?

**Comment by killing3mark** [comment]
That's correct

Dana 15. lis 2017. 05:07 PM osoba "Christian" <notifications@github.com>
napisala je:
