### ISSUE TITLE
Vehicles not able to be recycled

### ISSUE THREAD

**Issue by benismaster** [Wyqer/kp_liberation#239]
### Basic Information
**Mission version:** 0.96
**Map used:** Takistan
**Mods used:** CUP Terrains - Core, CUP Terrains - Maps, RHSUSAF, RHSAFRF, CBA_A3, Bloodlust, Advanced Rappelling, Advanced Sling Loading, Advanced Towing, Advanced Urban Rappelling, Project OPFOR, Donkeypunch.INFO Open Chernaurus Project
**Dedicated or local game?** Local
**GitHub or Workshop mission file?** Workshop

### Individual Things
**Did you edit anything within the mission files?**
No

**If yes, what did you edit exactly?**

### Short Issue Description
Driving any buildable vehicle up to the salvage depot will not have the "Recycle" option pop up.

### Expected Behaviour
Any vehicle cannot be recycled. However, I was able once to drive an enemy UAZ - 3151 DSHKm up to the depot and recycle it, since then no vehicles have been able to be recycled. Even restarting the local server will not fix it.

### Steps to Reproduce the Issue
Drive a vehicle up to the salvage depot

### Screenshots, Serverlog or any other helpful Information
https://steamuserimages-a.akamaihd.net/ugc/866240102625164431/815FA632FA5F6D9E46F39152C8A0A159DDE90D54/

**Comment by Wyqer** [comment]
And the vehicle you want to recycle has been built via the build menu?
I've just tested it also on a local game and I had not issues with recycle vehicles.
