### ISSUE TITLE
Problem, suggestion

### ISSUE THREAD

**Issue by killing3mark** [Wyqer/kp_liberation#240]
### Basic Information
**Mission version:0.961
**Map used:any
**Mods used:any
**Dedicated or local game?local
**GitHub or Workshop mission file?github

### Individual Things
**Did you edit anything within the mission files?**

No
**If yes, what did you edit exactly?**

### Short Issue Description

When you attack a sector and die, but you dont have a mobile respawn or nearby ai or players with you enemies dissapear and you have to kill them all over again
### Expected Behaviour
Enemy AI stay for a designated amount of time

### Steps to Reproduce the Issue

Die, travel to the same distanced location again

**Comment by Wyqer** [comment]
That's intended behaviour and can be "solved" with more preparation for the attacks. (AI nearby, a dron in the are, deploy mobile respawn, etc.)
Think logical like "Attack has stopped, enemy can reinforce".
And technical: "Keeps the AI count on a good level and therefore the serverload small".
