### ISSUE TITLE
Blufor defenders question

### ISSUE THREAD

**Issue by killing3mark** [Wyqer/kp_liberation#241]
### Basic Information
**Mission version:0.961
**Map used:any
**Mods used:any
**Dedicated or local game?local
**GitHub or Workshop mission file?github

### Individual Things
**Did you edit anything within the mission files?**

No
**If yes, what did you edit exactly?**

### Short Issue Description
What does the blufor defenders in owned sectors refer to? Getting ai in fobs when you build them? Or blufor defenders in towns bases citira etc.when you capture them because I haven't been seeing any of those?

**Comment by Wyqer** [comment]
Please ask basical questions on Discord and use this issue system only for suggestions or issues.
Blufor Defenders spawn if a blufor sector is attacked.
