### ISSUE TITLE
despawn/cleanup?

### ISSUE THREAD

**Issue by dvdbrewster** [Wyqer/kp_liberation#242]
### Basic Information
Mission version: .96 . APEX presets blu,op,res,civ.
**Map used:**Tanoa
**Mods used:**cba,ace,cupmappak,mao-bloodmist,ewk_cigs.
**Dedicated or local game?**ded, 2x hc's
**GitHub or Workshop mission file?**wip
**Mission version:**
.96(fixed)
**Dedicated or local game?**
ded
**GitHub or Workshop mission file?**
git
### Individual Things
**Did you edit anything within the mission files?**
params/presets

**If yes, what did you edit exactly?**
like yesterdays issue.. no enemies. (apex factions-all of them, params..)

### Short Issue Description
I was attacking a camo.. I got killed.. pulled last squad member back to fob.  30 min. later or 45 min.. I went back with a complete squad.. and the wrecks remained from last attack. 1 guy was left to kill and I managed capture..

### Expected Behaviour
new spawn

### Steps to Reproduce the Issue
?

**Comment by Wyqer** [comment]
Activate the sector spawn debug in the mission params and append a serverlog if you encounter this again.
New spawn will happen if the sector deactivates (no blufor units closer than about 1km to the sector).
Without the log there isn't anything I can look for.
