### ISSUE TITLE
Client FPS Drops

### ISSUE THREAD

**Issue by HandiworksInteractive** [Wyqer/kp_liberation#243]
### Basic Information
**Mission version: 0.955**
**Map used: Malden**
**Mods used: None**
**Dedicated or local game? Dedicated**
**GitHub or Workshop mission file? Github**

### Individual Things
**Did you edit anything within the mission files?**
No

**If yes, what did you edit exactly?**

### Short Issue Description
Every 2 hours Client FPS go to 10 server stay stable and high

### Expected Behaviour
No Client FPS drops

### Steps to Reproduce the Issue
Just playing

### Screenshots, Serverlog or any other helpful Information
[arma3-server-console.log](https://github.com/Wyqer/kp_liberation/files/1385925/arma3-server-console.log)

**Comment by HandiworksInteractive** [comment]
[Arma3_x64_2017-10-16_01-38-46.txt](https://github.com/Wyqer/kp_liberation/files/1386003/Arma3_x64_2017-10-16_01-38-46.txt)

**Comment by Wyqer** [comment]
Concerning to the logs "no edits to the missionfile" is wrong.
Stats from each client in the serverlog is in this issue helpful, but wasn't part of 0.955.

As you can see in the log, the fps of the server are fine and all AI is also located on the server (clints have only 1 local unit all the time). If there would be a real issue connected to the mission, the server would have "issues", too.

I recommend to use a not edited missionfile with 0.955 or with 0.96, but you're not playing a "not edited" 0.955 version currently.

Personally I can't reproduce this kind of performance issues in Liberation locally or on our weekly sessions, where also nobody experienced this kind of behaviour. But maybe someone else around might have a similar thing to report.

After using a not edited version provide a new serverlog. Or state all edits you've made to your current missionfile.

**Comment by dedmen** [comment]
To investigate FPS issues please provide profiling reports: https://community.bistudio.com/wiki/Performance_Profiling
Just click "copy-all" paste it into a textfile and upload it.
Atleast 2 or 3 files would be good.
Also atleast one `diag_captureSlowFrame ['total',0.04];`

**Comment by HandiworksInteractive** [comment]
[proffps.txt](https://github.com/Wyqer/kp_liberation/files/1388938/proffps.txt)

**Comment by HandiworksInteractive** [comment]
and here is a diag where we screwed around for a bit with low fps and all of the sudden i got a fps boost again 
[proffps2.txt](https://github.com/Wyqer/kp_liberation/files/1389178/proffps2.txt)

**Comment by HandiworksInteractive** [comment]
any news on the reason behind the fps drops?

**Comment by dedmen** [comment]
Remind me again in about 9 hours from now ^^

**Comment by HandiworksInteractive** [comment]
like this? :P

**Comment by dedmen** [comment]
proffps.txt: That's soundbug. https://feedback.bistudio.com/T124746
friend one is.. nothing I guess everything is a little slow in general.. but nothing special.
proffps2.txt That's an eventhandler in exiting RscDisplayMPInterrupt.
You closed the escape menu and some unscheduled script took 50ms. Looks like a BIS script.

**Comment by HandiworksInteractive** [comment]
doesnt sound like it at all as the fps drop over time not at one alt tab ?

**Comment by dedmen** [comment]
@HandiworksInteractive what?

**Comment by dedmen** [comment]
Interesting that the soundbug appears here. I only had that on Liberation so far.. Never thought about that.. Could very well be some thing in Liberation causing that.
