### ISSUE TITLE
Suggestions: Construction Separation

### ISSUE THREAD

**Issue by chrisleaptrott** [Wyqer/kp_liberation#244]
It would be a benefit to how permissions are set up if it were possible to limit what people were authorized to build via the permissions. I am looking into implementing this into code myself, any pointers would be welcome and I'll gladly handover any progress if you guys want.

thanks again for the best mission in Arma 3!

**Comment by Wyqer** [comment]
Glad you like it.
Concerning your suggestion: There is already a very similar topic opened concerning the permission system, so I'll close this one after linking it.
#95
