### ISSUE TITLE
SMAW optics not available in RHS arsenals.

### ISSUE THREAD

**Issue by SporkFortuna** [Wyqer/kp_liberation#245]
### Basic Information
**Mission version:** 0.955 but looks like it is still present in 0.96 Release according to the files listed in /Missionframework/arsenal_presets
**Map used:** N/A, Discovered in Altis mission but not map specific.
**Mods used:** RHS: USAF
**Dedicated or local game?** Local
**GitHub or Workshop mission file?** Both

### Individual Things
**Did you edit anything within the mission files?** 
Yes

**If yes, what did you edit exactly?** 
Added items and  to arsenal preset rhsusaf.sqf and unit preset rhs_usaf.sqf my group enjoy playing with.  I also specifically went into the arsenal preset to try and find the SMAW Sight, where I saw "rhs_weap_optic_smaw" was in the wrong place.

### Short Issue Description
rhs_weap_optic_smaw is in GRLIB_arsenal_weapons rather than GRLIB_arsenal_items and does not show up as a weapon attachment in the arsenal.  Moving to GRLIB_arsenal_items fixes this.

### Expected Behaviour
SMAW optics should be available to the two SMAW variants.  It is not.

### Steps to Reproduce the Issue
Equip the SMAW from the arsenal and the SMAW optics are not listed.  Moving "rhs_weap_optic_smaw" from GRLIB_arsenal_weapons to GRLIB_arsenal_items in the arsenal preset file fixes the issue. 

### Screenshots, Serverlog or any other helpful Information
This seems to be present on all RHS arsenal presets.

**Comment by FatRefrigerator** [comment]
Good catch, thanks
