### ISSUE TITLE
Suggestion: Parameter to toggle resource production in 'city' zones

### ISSUE THREAD

**Issue by Blakmane** [Wyqer/kp_liberation#246]
The new version (0.96) removes resource production for cities (the small capturable zones, not the major 'objective' zones). After talking with Wyqer it seems the plan is to move cities towards Civrep functions and leave factories as the major resource provider. I understand this was in part because the glut of captured zones in the mid to late game can create a ridiculous resource overflow.

However, the new  situation this creates a bit of a difficult situation for small groups, especially in the early game where supplies are vital to outfit AI squads for sector capture. It also creates a heavy disincentive to capture cities, which provide one-off civrep (that has some nice, but pretty minor benefits, again especially early on) but no other tangible bonus.

Until city capture offers a more tangible alternative to resources, it might be useful to have a parameter that re-enables resource production in cities, disabled by default of course.

Thoughts?

**Comment by Wyqer** [comment]
As we talked already, I'm also very excited for other opinions.
And Applejakerie planned to do a small "balancing" on the prices etc. due to the new situation and due to incoming feeback, of course.

**Comment by FatRefrigerator** [comment]
How about CivRep is high enough, there should be a 20%? chance that every resource tick the civilians will donate a random resource crate as a "gift".

**Comment by Blakmane** [comment]
Something like that could work, but I think the issue is primarily early in the game where you have no CivRep and no resources. Having an extra reward at high CivRep doesn't help at that point. Perhaps something like the ability to 'draft' FIA units into your squad at the price of CivRep could work? Lategame you have plenty of resources and probably want to keep a high CivRep, so it wouldn't scale badly.
