### ISSUE TITLE
Resource trucking issue

### ISSUE THREAD

**Issue by ildolore** [Wyqer/kp_liberation#249]
Kill this issue if it working as planned, but...

I accidentally produced too many resources and all the factory storage sites were maxed out. The FOB then maxed out and the truck drove back to the factory and waited until i manually loaded 3 boxes into my vehicle. It then dumped it's boxes into the factory and ended the mission back at the FOB.

This was the only way i could solve the issue logistically, I guess I could have built something for a museum! 

Perhaps there could be a back end solution or notification?

**Comment by FatRefrigerator** [comment]
You can build more than one supply pad at the FOB

**Comment by ildolore** [comment]
The FOB has 4 large storage. 

I'm happy for you to delete this report and call me stupid, just thought I'd report the behaviour in case

**Comment by Wyqer** [comment]
No need to delete it. Did you read the wiki entry about the logistics?
It explains the specific behaviour of the logistic groups. Your description seems to be "all fine" to me.
https://github.com/Wyqer/kp_liberation/wiki/EN:Logistic
