### ISSUE TITLE
Can't heal injured civ

### ISSUE THREAD

**Issue by ildolore** [Wyqer/kp_liberation#251]
![20171025103431_1](https://user-images.githubusercontent.com/29398536/32005162-2e2c8510-b9d6-11e7-91e9-1ea8c76fc6c2.jpg)
![20171025103436_1](https://user-images.githubusercontent.com/29398536/32005163-2e687138-b9d6-11e7-96c3-2da553c87d83.jpg)
![20171025103422_1](https://user-images.githubusercontent.com/29398536/32005164-2ea394d4-b9d6-11e7-9f44-228eeeb38c16.jpg)

- I have bandages in my inventory
- There is no item in the action menu to heal the man
- There is no injured part on the man in the ACE heal menu

The other player in my team reported that the man was in a combat/firing stance without a gun - same clothes though. He didn't get an image.

Attached images and log. I was hosting locally.

[Arma3_x64_2017-10-25_09-42-18.txt](https://github.com/Wyqer/kp_liberation/files/1415032/Arma3_x64_2017-10-25_09-42-18.txt)

**Comment by matr1x001** [comment]
The civs that are in a combat firing stance is I think just the result of the units items being checked and then removed via script after town clearance not an indication they are about to go rogue. I have found the medical issue can be resolved by carrying more types of bandages like quick clot, packing bandages etc, even if just to carry out treatment on these civs. Try equipping a variety of bandage and dressing types then check if it helps in this situation. There may be traces of ace advanced wounds used in this event.

**Comment by ildolore** [comment]
Ah, I'll try with different bandages. 

To be clear, the man was in the firing stance while he was prone for me. We were looking at the same man.

Because I only play with one other, we don't take a medics' slot but I will do that or even equip a medical AI next time. 

Will report back

**Comment by Wyqer** [comment]
Activate the civrep debug and provide a logfile.
