### ISSUE TITLE
Feature | Zeus options

### ISSUE THREAD

**Issue by Tress16** [Wyqer/kp_liberation#254]
Would be a nice feature if the Zeus regulation (teleport units, ...) could be definable in the **mission_params.hpp** so the admins can handle this.

**Comment by Wyqer** [comment]
They can already. But there is no way for a parameter, which could modify the mission.sqm
And the work which has to be done for fetching the used addons which are individually used on the server/client and add them to the curator module via script commands is in no balance to the small edit which has to be done by the admin/player in the missionfile itself.
https://github.com/Wyqer/kp_liberation/wiki/EN:FAQ#how-can-i-enable-full-zeus

**Comment by Tress16** [comment]
Copy. Thx

**Comment by TheKukyCZ** [comment]
If I want to see that link https://github.com/Wyqer/kp_liberation/wiki/EN:FAQ#how-can-i-enable-full-zeus
I've got error: You do not have permission to update this wiki.

So where can I see how to enable Zeus? Thanks

**Comment by TheKukyCZ** [comment]
dmorchard thankssss!

**Comment by TheKukyCZ** [comment]
@dmorchard Thanksss!!
