### ISSUE TITLE
Feature | FOB Manager

### ISSUE THREAD

**Issue by Tress16** [Wyqer/kp_liberation#256]
Would be a nice feature if the FOB's have a own permission system so that only the High-Commander and the FOB-Commander(s) can handle the features on the FOB's who permissed to.

- Only High-Commander can give permissions.

- Player can get the permissions of 1 or more FOB's.

- Only the FOB-Commander(s) and the High-Commander can build, recycle and handle ressources (F, A, S) on the given FOB(s).

- FOB-permissions can given to 1 or more playsers.

- Only the FOB-Commander(s) and the High-Commander can given vehicle permissions for **in his FOB builded vehicles**.

- Only the FOB-Commander(s) can give permissions to respawn on his FOB.

**Comment by Wyqer** [comment]
Same general topic as in #95
