### ISSUE TITLE
Mission file disable mods

### ISSUE THREAD

**Issue by bGr3m** [Wyqer/kp_liberation#258]
### Basic Information
**Mission version:**
0.96
**Map used:**
Tanoa
**Mods used:**
CBA, ace, ace extensions, task force radio, cup terrains core, acecompat rhsusaf, acecompat rhsafrf, rhsusaf, rhsafrf, project opfor, Red's Office Furniture Pack

**Dedicated or local game?**
dedi (linux)

**GitHub or Workshop mission file?**
workshop

### Individual Things
**Did you edit anything within the mission files?**
no

**If yes, what did you edit exactly?**

### Short Issue Description
on server starts mods are showed and loaded correctly, then on "select role" screen, mods will "disappear" and launcher will say "no mods", difficulty also got resetted (from custom to recruit)

not 100% sure if this is mission related but is the first time i see this beahvior and only with this liberation tanoa (my clan played a lot of liberation mission on last year with no problem)

### Expected Behaviour
mod list should be visible in launcher for correct loading when join

### Screenshots, Serverlog or any other helpful Information

**Comment by Wyqer** [comment]
Personally I can't imagine that the missionfile could interrupt anything in the communication between server and the steam api to show the mods etc. which are needed/running on the server.
As you said, that you've played other maps with Liberation without any issues it's also very hard to imagine. Reason is, that the only difference in e.g. Tanoa Liberation and Altis Liberation is the mission.sqm. Script files etc. are all the same.

Only thought I had concerning your description is the issue with the ArmA 3 Launcher concerning limited mod count. But you don't have that much mods, that it could be an issue I guess. But maybe you want to have a look at it, too:
https://feedback.bistudio.com/T123655
