### ISSUE TITLE
OPFOR Vehicles Disappearing

### ISSUE THREAD

**Issue by Corpdraco** [Wyqer/kp_liberation#262]
### Basic Information
**Mission version:** 
0.96 Hotfix

**Map used:** 
Tanoa

**Mods used:**
![image](https://user-images.githubusercontent.com/2280835/32338145-f1ff3528-bfc1-11e7-9b0f-2333a5cd4a7d.png)

**Dedicated or local game?**
100% Dedicated

**GitHub or Workshop mission file?**
GitHub

### Individual Things
**Did you edit anything within the mission files?**
Yes.

**If yes, what did you edit exactly?**
I removed the commander Zeus module.

### Short Issue Description
Captured OPFOR vehicles are disappearing when driving back to the FOB. The vehicles will delete with players inside and with cargo crates inside. The cargo crates will drop to the ground unharmed. This happens with T-100s, Ifrits, or any variant of OPFOR vehicle. I feel this is part of the cleanup / variable settings within Liberation.

### Expected Behaviour
Captured OPFOR vehicles shouldn't delete.

### Steps to Reproduce the Issue
Capture an OPFOR vehicle, and it will delete itself.

### Screenshots, Serverlog or any other helpful Information
No screenshots available due to the randomness of it.

**Comment by Wyqer** [comment]
Can't confirm that issue, as we haven't encountered problems with this behaviour and the scripts automatically set a variable on each enemy vehicle in which blufor crew is detected. And during the deletion of opfor vehicles it will only delete vehicles which haven't this variable set.

Please attach a serverlog and your missionfile.
