### ISSUE TITLE
Question | GREUH folder

### ISSUE THREAD

**Issue by Tress16** [Wyqer/kp_liberation#265]
I wanne delete the **GREUH-folder**. Can I delete them and the follow code from the **init.sqf** without having any problems? Or have I do something more for this? We don't need this function and wanna keep it simple.

`[] execVM "GREUH\scripts\GREUH_activate.sqf";`

and the code from **description.ext**:
`#include "GREUH\UI\GREUH_interface.hpp"`

**Comment by Wyqer** [comment]
Already done it? What did you encountered by this?

**Comment by Tress16** [comment]
I've deleted the code and the whole folder.
Till now I can't see any problems.
