### ISSUE TITLE
Feature | Max players airdrop option

### ISSUE THREAD

**Issue by Tress16** [Wyqer/kp_liberation#268]
It would be a nice feature if the airdrop were adjustable so that the maximum number of players determines if a jump is available or not. For example, you could put the value on 6 players. If there are 6 or more players, the parachute jump would not be available. Only with less than 6 players you could use the vertical routing. This could give logistics more weight and operations deep in the enemy territory would be more demanding.

**Comment by Wyqer** [comment]
Why the codework etc. if this is, in my opinion, just a question of talking with the players and state the convention that this feature should only be used if there were less than 6 players on the server?

**Comment by Tress16** [comment]
I think if there are more than x players on the server somebody can make the transport part. But if there are not enough players available everyone should have the option to rejoin his team by using the vertical way.


```
// IF MORE THEN X PLAYERS
if (playersNumber west >=6) exitWith {
	hint localize "STR_KP_noAirdropAvailable";
};
```

**Comment by Wyqer** [comment]
Don't get me wrong, but I didn't asked how to code something.
I asked why should something implemented as coded functionality if that behaviour can be easily achived by just talk with the own group and say "We don't use the paradrop, when we're more than X players"?

**Comment by Tress16** [comment]
Ohhh... I‘m sorry. My english is not the yellow from the egg.

Only tell the people what is allowed and what is not will not work and the admins have to much to do too. And if we stop this function by script nobody have to study the rules and count the players before jumping.

**Comment by Applejakerie** [comment]
Just wanted to add my input. 

It doesn't seem very useful to me? Just because you have X amount of players doesn't mean one should be punished playing "taxi". Sure a lot of servers - the majority most likely - like to play with realism where transport is indeed intended but then they disable the airdrop, or at the least add a large cooldown. Hope you see my point kindly. 😄

**Comment by Tress16** [comment]
If a server admin don‘t wanna use this it can be disabled with setting max players high enough. But for the community‘s who wanna bring the part of planning the infiltration more in the focus this could be a nice feature. Only setting a cooldown is not flexible enough for the moments with only a few players and the rush hour.

**Comment by Wyqer** [comment]
Currently you can disable, enable with or without cooldown.
A counter would be, in my opinion, unnecessary codework for a feature which has the arguments "the admins have to much to do" and "nobody have to study the rules". Beside of the fact that the amount of people who really need such a functionality is very very small.
Of course, you're free to code this and contribute the working code to this repository for checking and implementing. Personally I won't code such a feature.

**Comment by Tress16** [comment]
OK
