### ISSUE TITLE
Enemy vehicle crew not always forced into "GRLIB_side_enemy"

### ISSUE THREAD

**Issue by veteran29** [Wyqer/kp_liberation#273]
When testing #271 I have found out that in some cases crew of enemy vehicles is not forced to correct side.

I have configured friendly side to _EAST_ and enemy to _WEST_, blufor was set to _AFRF_ preset from pull request and opfor was set to _Project OPFOR_ preset.

**What happended:**
When _takistani_ units were spawning they were forced into WEST side. But some vehicles spawned as EAST side and started to shoot at them.

From what I have found this is caused by _createVehicleCrew_ usage in this method, this method spawns default crew for vehicle (in this case crewmans allied to _EAST_ side) 
https://github.com/Wyqer/kp_liberation/blob/d269b87720ed0a601052299a7b42e2ff32a7bee9/Missionframework/scripts/shared/functions/F_libSpawnVehicle.sqf#L36-L44

Paratroopers chopper is propably affected by same problem:
https://github.com/Wyqer/kp_liberation/blob/d269b87720ed0a601052299a7b42e2ff32a7bee9/Missionframework/scripts/server/patrols/send_paratroopers.sqf#L10-L14

Im not sure but can this be fixed just by doing it like this?:
```sqf
_grp = createGroup GRLIB_side_enemy;
createVehicleCrew _newvehicle;
(crew _newvehicle) joinSilent _grp;
```

**Comment by Wyqer** [comment]
This is a situation which was never thought of, of course. Basically you've an east preset fighting against an east preset. `createVehicleCrew` creates the crew according to the config of the vehicle and set them to the default vehicle side.

The workaround you're mentioning would basically work, but should be tested many times, as it could happen that it don't work always realiable. The best way to ensure that the crew etc. will be on the "right side" is to create a default unit from the enemy side (for example a west survivor), let the vehicle crew join the group of the survivor and afterwards delete the survivor. But this can't be achieved dynamically with just selecting the enemy side, so your thought concerning the `joinSilent` would be the best way, yes.

**Comment by veteran29** [comment]
After #276 this is fixed. Closing.
