### ISSUE TITLE
Crash when respawn camera first looks at aircraft carrier

### ISSUE THREAD

**Issue by PhantomViper** [Wyqer/kp_liberation#274]
### Basic Information
**Mission version: 0.961
**Map used: Altis
**Mods used: Not sure all but I know advanced towing is in there, otherwise vanilla.
**Dedicated or local game? Dedicated, no headless client. (Public server if it helps: 88.99.130.226:2302)
**GitHub or Workshop mission file? GitHub

### Individual Things
**Did you edit anything within the mission files?**
Yes.

**If yes, what did you edit exactly?**
Tweaks what spawns.

### Short Issue Description
My game freezes and gives me the error code bad_module_info after I die and my camera is looking at the aircraft carrier.

### Expected Behaviour
No crashing

### Steps to Reproduce the Issue
1. Die
2. Camera looks at aircraft carrier
3. Crash

### Screenshots, Serverlog or any other helpful Information
If there is a way to get crash logs let me know and I will get them.

**Comment by Wyqer** [comment]
It would be very helpful if you can provide a full rpt from the server and the crashing client.
Clients RPTs are in appdata\local\ArmA 3 and are named similar to the server rpts.
But the issue you describe didn't happened to someone before or to me, so I've no initial advise for you.

**Comment by Wyqer** [comment]
https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/bad-module-info/d83dd149-de84-490f-9983-905f4c2af6f0?auth=1
