### ISSUE TITLE
Seperate command and logistics.

### ISSUE THREAD

**Issue by PhantomViper** [Wyqer/kp_liberation#275]
I think that having logistics and command split could be beneficial for busy public servers as well as private ones. The main idea here is further utilizing the logistics slot and reducing the responsibilities of a commander. The commander would go unchanged but the logistics officer would also have access to Zeus but no editing abilities. This access would be to help locate crates. The logistics officer could also use production setting and the logistics overview. The logistics team as a whole would have the main goal of securing supplies for the group to use on building and vehicles. The main reason I felt prompted to suggest this is because I was playing on a public server in the command slot. On this server the everything goes through command, you want a vehicle? Ask command. You want to know which town to attack next? Ask command. You need...? Ask command. I felt overwhelmed trying to manage getting our first FOB set up and trying to manage people asking me for new orders, repair trucks, fuel trucks and other things of the sort. This suggestion would take some of that stress away and some people enjoy the logistics side of things(I am one of them). I can sit for hours and work on all that stuff while others go and fight. Just adds for options without dividing abilities up. Maybe a parameters option to disable logistics Zeus access. Anyway, thanks for reading! 😄

**Comment by Wyqer** [comment]
The commander should be (in normal player count) only in the FOB and manage all aspects of the mission. But you can for sure add another zeus module for one of the other playable slots by giving that slot a variable name in the editor or by editing the mission.sqm

Beside of this I guess this would fit best to #95
