### ISSUE TITLE
Massive Frame Drops Across 3 People

### ISSUE THREAD

**Issue by LoadingSAa** [Wyqer/kp_liberation#278]
### Basic Information
**Mission version:**
0.961
**Map used:**
Chernarus
**Mods used:**
@cba_a3
@asr_ai3
@asr_ai3_-_rhs_config
@ace
@acex
@rhsafrf
@rhsgref
@rhssaf
@rhsusaf
@ace_compat_-_rhs_armed_forces_of_the_russian_federation
@ace_compat_-_rhs-_gref
@ace_compat_-_rhs_united_states_armed_forces
@cup_terrains_-_core
@cup_terrains_-_maps
@task_force_radio
@lythium
@jbad
@niarms_core
@niarms_p226_pistols
@project_infinite_-_all_in_one
@project_infinite_-_attachments_cba_a3
@project_zenith_alpha
@bwa3_ace
@bwmod
@l3-gpnvg18_panoramic_night_vision
@military_gear_pack
@specialist_military_arms
@the_mighty_gau8_avenger
@xcam_taunus <-- Not used currently still loaded on the server though.
@r3f_advance_logisticsmods
@aceserver
@mcc
@advanced_rappelling
@advanced_sling_loading
@advanced_towing
@advanced_urban_rappelling
@shacktac_user_interface

**Dedicated or local game?**
Dedicated with 1 HC
**GitHub or Workshop mission file?**
Git

### Individual Things
**Did you edit anything within the mission files?**
Yes
I changed the main config a little bit with the following lines.
```
GRLIB_battlegroup_size = 2	
GRLIB_surrender_chance = 0;
GRLIB_civilians_amount = 1
GRLIB_cleanup_delay = 300;
```

I also changed rhs_usaf.sqf in presets

```
	["B_Quadbike_01_F",0,0,0],										//Quad Bike
	["rhsusf_m1025_w",0,0,0],										//M1025A2
	["rhsusf_m1025_w_m2",0,0,0],									//M1025A2 (M2)
	["rhsusf_m1025_w_mk19",0,0,0],									//M1025A2 (Mk19)
```
```
class Params
{
	class MissionOptions {
		title = $STR_PARAMS_MISSIONOPTIONS;
		values[] = { "" };
		texts[] = { "" };
		default = "";
	};
	class Unitcap {
		title = $STR_PARAMS_UNITCAP;
		values[] = {0,1,2,3,4,5};
		texts[] = {$STR_PARAMS_UNITCAP1,$STR_PARAMS_UNITCAP2,$STR_PARAMS_UNITCAP3,$STR_PARAMS_UNITCAP4,$STR_PARAMS_UNITCAP5,$STR_PARAMS_UNITCAP6};
		default = 0;
	};
	class Difficulty {
		title = $STR_PARAMS_DIFFICULTY;
		values[] = { 0, 1, 2, 3, 4, 5, 6, 7 };
		texts[] = { $STR_PARAMS_DIFFICULTY1, $STR_PARAMS_DIFFICULTY2, $STR_PARAMS_DIFFICULTY3, $STR_PARAMS_DIFFICULTY4, $STR_PARAMS_DIFFICULTY5, $STR_PARAMS_DIFFICULTY6, $STR_PARAMS_DIFFICULTY7, $STR_PARAMS_DIFFICULTY8 };
		default = 2;
	};
	class Aggressivity {
		title = $STR_AGGRESSIVITY_PARAM;
		values[] = {0,1,2,3,4};
		texts[] = {$STR_AGGRESSIVITY_PARAM0, $STR_AGGRESSIVITY_PARAM1,$STR_AGGRESSIVITY_PARAM2,$STR_AGGRESSIVITY_PARAM3,$STR_AGGRESSIVITY_PARAM4};
		default = 1;
	};
	class AdaptToPlayercount {
		title = $STR_PARAM_ADAPT_TO_PLAYERCOUNT;
		values[] = {1,0};
		texts[] = {$STR_PARAMS_ENABLED,$STR_PARAMS_DISABLED};
		default = 1;
	};
	class Civilians {
		title = $STR_PARAMS_CIVILIANS;
		values[] = {0,1,2,3};
		texts[] = {$STR_PARAMS_CIVILIANS1,$STR_PARAMS_CIVILIANS2,$STR_PARAMS_CIVILIANS3,$STR_PARAMS_CIVILIANS4};
		default = 0;
	};
	class FirstFob {
		title = $STR_PARAMS_FIRSTFOB;
		values[] = { 1, 0 };
		texts[] = { $STR_YES, $STR_NO };
		default = 0;
	};
	class MaximumFobs {
		title = $STR_PARAM_FOBS_COUNT;
		values[] = {3,5,7,10,15,20,26};
		texts[] = {3,5,7,10,15,20,26};
		default = 26;
	};
	class MaxSquadSize {
		title = $STR_PARAM_SQUAD_SIZE;
		values[] = {0,1,2,4,6,8,10,12,16,20,24,30,36};
		texts[] = {0,1,2,4,6,8,10,12,16,20,24,30,36};
		default = 0;
	};
	class BluforDefenders {
		title = $STR_PARAM_BLUFOR_DEFENDERS;
		values[] = {1,0};
		texts[] = { $STR_PARAMS_ENABLED, $STR_PARAMS_DISABLED };
		default = 0;
	};
	class Autodanger {
		title = $STR_PARAM_AUTODANGER;
		values[] = {1,0};
		texts[] = { $STR_PARAMS_ENABLED, $STR_PARAMS_DISABLED };
		default = 1;
	};
	class DayDuration {
		title = $STR_PARAMS_DAYDURATION;
		values[] = {48, 24, 16, 12, 8, 6, 4, 3, 2, 1};
		texts[] = {"0.5","1","1.5","2","3","4","6","8","12","24"};
		default = 12;
	};
	class ShorterNights {
		title = $STR_SHORTER_NIGHTS_PARAM;
		values[] = {1,0};
		texts[] = { $STR_PARAMS_ENABLED, $STR_PARAMS_DISABLED };
		default = 1;
	};
	class Weather {
		title = $STR_WEATHER_PARAM;
		values[] = { 1,2,3 };
		texts[] = { $STR_WEATHER_PARAM1, $STR_WEATHER_PARAM2, $STR_WEATHER_PARAM3 };
		default = 1;
	};
	class ResourcesMultiplier {
		title = $STR_PARAMS_RESOURCESMULTIPLIER;
		values[] = { 0, 1, 2, 3, 4, 5, 6, 7 };
		texts[] = { "x0.25", "x0.5", "x0.75", "x1", "x1.25","x1.5","x2","x3" };
		default = 5;
	};
	class Spacer1 {
		title = "";
		values[] = { "" };
		texts[] = { "" };
		default = "";
	};
	class ReviveOptions {
		title = $STR_PARAMS_REVIVEOPTIONS;
		values[] = { "" };
		texts[] = { "" };
		default = "";
	};
	class ReviveMode {
		title = $STR_A3_ReviveMode;
		isGlobal = 1;
		values[] = {-100,0,1};
		texts[] = {$STR_A3_MissionDefault, $STR_A3_Disabled, $STR_A3_EnabledForAllPlayers};
		default = 0;
		function = "bis_fnc_paramReviveMode";
	};
	class ReviveDuration {
		title = $STR_A3_ReviveDuration;
		isGlobal = 1;
		values[] = {-100,6,8,10,12,15,20,25,30};
		texts[] = {$STR_A3_MissionDefault,6,8,10,12,15,20,25,30};
		default = 6;
		function = "bis_fnc_paramReviveDuration";
	};
	class ReviveRequiredTrait {
		title = $STR_A3_RequiredTrait;
		isGlobal = 1;
		values[] = {-100,0,1};
		texts[] = {$STR_A3_MissionDefault,$STR_A3_None,$STR_A3_Medic};
		default = 1;
		function = "bis_fnc_paramReviveRequiredTrait";
	};
	class ReviveMedicSpeedMultiplier {
		title = $STR_A3_RequiredTrait_MedicSpeedMultiplier;
		isGlobal = 1;
		values[] = {-100,1,1.5,2,2.5,3};
		texts[] = {$STR_A3_MissionDefault,"1x","1.5x","2x","2.5x","3x"};
		default = 1;
		function = "bis_fnc_paramReviveMedicSpeedMultiplier";
	};
	class ReviveRequiredItems {
		title = $STR_A3_RequiredItems;
		isGlobal = 1;
		values[] = {-100,0,1,2};
		texts[] = {$STR_A3_MissionDefault,$STR_A3_None,$STR_A3_Medikit,$STR_A3_FirstAidKitOrMedikit};
		default = 1;
		function = "bis_fnc_paramReviveRequiredItems";
	};
	class UnconsciousStateMode {
		title = $STR_A3_IncapacitationMode;
		isGlobal = 1;
		values[] = {-100,0,1,2};
		texts[] = {$STR_A3_MissionDefault,$STR_A3_Basic,$STR_A3_Advanced,$STR_A3_Realistic};
		default = 0;
		function = "bis_fnc_paramReviveUnconsciousStateMode";
	};
	class ReviveBleedOutDuration {
		title = $STR_A3_BleedOutDuration;
		isGlobal = 1;
		values[] = {-100,10,15,20,30,45,60,90,180};
		texts[] = {$STR_A3_MissionDefault,10,15,20,30,45,60,90,180};
		default = 180;
		function = "bis_fnc_paramReviveBleedOutDuration";
	};
	class ReviveForceRespawnDuration {
		title = $STR_A3_ForceRespawnDuration;
		isGlobal = 1;
		values[] = {-100,3,4,5,6,7,8,9,10};
		texts[] = {$STR_A3_MissionDefault,3,4,5,6,7,8,9,10};
		default = 10;
		function = "bis_fnc_paramReviveForceRespawnDuration";
	};
	class Spacer2 {
		title = "";
		values[] = { "" };
		texts[] = { "" };
		default = "";
	};
	class GameplayOptions {
		title = $STR_PARAMS_GAMEPLAYOPTIONS;
		values[] = { "" };
		texts[] = { "" };
		default = "";
	};
	class Fatigue {
		title = $STR_PARAMS_FATIGUE;
		values[] = { 0, 1 };
		texts[] = { $STR_PARAMS_DISABLED, $STR_PARAMS_ENABLED };
		default = 0;
	};
	class ArsenalUsePreset {
		title = $STR_PARAMS_ARSENALUSEPRESET;
		values[] = { 0, 1 };
		texts[] = { $STR_PARAMS_NORESTRICTIONS, $STR_PARAMS_USEPRESET };
		default = 0;
	};
	class MapMarkers {
		title = $STR_PARAMS_MAPMARKERS;
		values[] = { 0, 1 };
		texts[] = { $STR_PARAMS_DISABLED, $STR_PARAMS_ENABLED };
		default = 0;
	};
	class MobileRespawn {
		title = $STR_PARAMS_MOBILERESPAWN;
		values[] = { 0, 1 };
		texts[] = { $STR_PARAMS_DISABLED, $STR_PARAMS_ENABLED };
		default = 1;
	};
	class RespawnCooldown {
		title = $STR_PARAM_RESPAWN_COOLDOWN;
		values[] = {0, 300, 600, 900, 1200, 1800, 3600};
		texts[] = {$STR_PARAMS_DISABLED, 5, 10, 15, 20, 30, 60};
		default = 0;
	};
	class MobileArsenal {
		title = $STR_PARAMS_MOBILEARSENAL;
		values[] = { 0, 1 };
		texts[] = { $STR_PARAMS_DISABLED, $STR_PARAMS_ENABLED };
		default = 1;
	};
	class AiLogistics {
		title = $STR_PARAMS_AILOGISTICS;
		values[] = {0, 1};
		texts[] = {$STR_PARAMS_DISABLED, $STR_PARAMS_ENABLED};
		default = 0;
	};
	// Arty Supp deactivated for now
	/*class SuppMod {
		title = $STR_PARAMS_SUPPMOD;
		values[] = {0, 1, 2, 3};
		texts[] = {$STR_PARAMS_DISABLED, $STR_PARAMS_COMMANDER, $STR_PARAMS_WHITELISTONLY, $STR_PARAMS_EVERYONE};
		default = 0;
	};*/
	class TeamkillPenalty {
		title = $STR_PARAM_TEAMKILL_PENALTY;
		values[] = {1,0};
		texts[] = { $STR_PARAMS_ENABLED, $STR_PARAMS_DISABLED };
		default = 0;
	};
	class CR_Building {
		title = $STR_PARAM_CR_BUILDING;
		values[] = {1,0};
		texts[] = {$STR_PARAM_CR_DAMAGED, $STR_PARAM_CR_DESTROYED};
		default = 0;
	};
	class HaloJump {
		title = $STR_HALO_PARAM;
		values[] = {1,5,10,15,20,30,0};
		texts[] = { $STR_HALO_PARAM1, $STR_HALO_PARAM2, $STR_HALO_PARAM3, $STR_HALO_PARAM4, $STR_HALO_PARAM5, $STR_HALO_PARAM6, $STR_PARAMS_DISABLED };
		default = 1;
	};
	class ClearCargo {
		title = $STR_PARAM_CLEAR_CARGO;
		values[] = {1,0};
		texts[] = { $STR_PARAMS_ENABLED, $STR_PARAMS_DISABLED };
		default = 1;
	};
	class Spacer3 {
		title = "";
		values[] = { "" };
		texts[] = { "" };
		default = "";
	};
	class TechnicalOptions {
		title = $STR_PARAMS_TECHNICALOPTIONS;
		values[] = { "" };
		texts[] = { "" };
		default = "";
	};
	class Permissions {
		title = $STR_PERMISSIONS_PARAM;
		values[] = {1,0};
		texts[] = { $STR_PARAMS_ENABLED, $STR_PARAMS_DISABLED };
		default = 0;
	};
	class CleanupVehicles {
		title = $STR_CLEANUP_PARAM;
		values[] = { 0,1,2,4 };
		texts[] = { $STR_PARAMS_DISABLED, $STR_CLEANUP_PARAM1, $STR_CLEANUP_PARAM2, $STR_CLEANUP_PARAM3 };
		default = 1;
	};
	class Introduction {
		title = $STR_PARAMS_INTRO;
		values[] = { 1, 0 };
		texts[] = { $STR_PARAMS_ENABLED, $STR_PARAMS_DISABLED };
		default = 0;
	};
	class DeploymentCinematic {
		title = $STR_PARAMS_DEPLOYMENTCAMERA;
		values[] = { 1, 0 };
		texts[] = { $STR_PARAMS_ENABLED, $STR_PARAMS_DISABLED };
		default = 0;
	};
	class Whitelist {
		title = $STR_WHITELIST_PARAM;
		values[] = { 1, 0 };
		texts[] = { $STR_WHITELIST_ENABLED, $STR_PARAMS_DISABLED };
		default = 0;
	};
	class ServerRestart {
		title = $STR_RESTART_PARAM;
		values[] = {0,1,2,3,4,5,6};
		texts[] = {$STR_PARAMS_DISABLED,"1","2","3","4","5","6"};
		default = 0;
	};
	class WipeSave1 {
		title = $STR_WIPE_TITLE;
		values[] = {0,1};
		texts[] =  {$STR_WIPE_NO,$STR_WIPE_YES};
		default = 0;
	};
	class WipeSave2 {
		title = $STR_WIPE_TITLE_2;
		values[] = {0,1};
		texts[] = {$STR_WIPE_NO,$STR_WIPE_YES};
		default = 0;
	};
	class Spacer4 {
		title = "";
		values[] = {""};
		texts[] = {""};
		default = "";
	};
	class DebugOptions {
		title = $STR_PARAMS_DEBUGOPTIONS;
		values[] = {""};
		texts[] = {""};
		default = "";
	};
	class DebugAsymmetric {
		title = $STR_PARAMS_DEBUG_ASYMMETRIC;
		values[] = {0, 1};
		texts[] = {$STR_PARAMS_DISABLED, $STR_PARAMS_ENABLED};
		default = 0;
	};
	class DebugCivInfo {
		title = $STR_PARAMS_DEBUG_CIVINFO;
		values[] = {0, 1};
		texts[] = {$STR_PARAMS_DISABLED, $STR_PARAMS_ENABLED};
		default = 0;
	};
	class DebugCivRep {
		title = $STR_PARAMS_DEBUG_CIVREP;
		values[] = {0, 1};
		texts[] = {$STR_PARAMS_DISABLED, $STR_PARAMS_ENABLED};
		default = 0;
	};
	class DebugKill {
		title = $STR_PARAMS_DEBUG_KILL;
		values[] = {0, 1};
		texts[] = {$STR_PARAMS_DISABLED, $STR_PARAMS_ENABLED};
		default = 0;
	};
	class DebugLogistic {
		title = $STR_PARAMS_DEBUG_LOGISTIC;
		values[] = {0, 1};
		texts[] = {$STR_PARAMS_DISABLED, $STR_PARAMS_ENABLED};
		default = 0;
	};
	class DebugProduction {
		title = $STR_PARAMS_DEBUG_PRODUCTION;
		values[] = {0, 1};
		texts[] = {$STR_PARAMS_DISABLED, $STR_PARAMS_ENABLED};
		default = 0;
	};
	class DebugSave {
		title = $STR_PARAMS_DEBUG_SAVE;
		values[] = {0, 1};
		texts[] = {$STR_PARAMS_DISABLED, $STR_PARAMS_ENABLED};
		default = 0;
	};
	class DebugSectorSpawn {
		title = $STR_PARAMS_DEBUG_SECTORSPAWN;
		values[] = {0, 1};
		texts[] = {$STR_PARAMS_DISABLED, $STR_PARAMS_ENABLED};
		default = 0;
	};
};
```

I also hard coded the default mission prams to my liking

### Short Issue Description

 A small group of friends and I have started up an ARMA server to play missions and mess around. We have noticed that after about an hour we get massive frame drops that will keep getting lower and lower until you get to about 5-8 fps then the game will just crash. I have been able to reproduce this bug across 3 computers and the bug once started will continue regardless of switching mission or restarting the server the only thing that fixes it is to fully restart arma on the client.

I have done the following to try and fix this issue. 
 

- Removed all the mods from the server adding them back one by one testing each one for 2 hours.
- Downloaded fresh untouched versions of our missions to rule out it being one of my edits causing it.
- I downloaded the performance build and did all the standard optimizations I could to my client. 
- Redownloaded the whole of arma 3.

 
There is likely more that I can't even remember doing now as I have tried everything I could find online and think of. 

### Expected Behaviour

Frame drops in large fights and a return to normal after the fight.

### Steps to Reproduce the Issue
I'm not sure but I tested this with a fresh install and download of the mission from git and got the same issue. I also tired to test each mod one at a time to see if a mod was causing this.

However We have been able to reproduce this bug by starting a large fight in a city/town and then respawning on the carrier

### Screenshots, Serverlog or any other helpful Information

[HC RPT Log](http://sawchuk.horse/arma3server-console.log)
[Main Server RPT](https://hastebin.com/ewisafexuq.vbs)

**Comment by LoadingSAa** [comment]
I just tried to test with only well known mods to see if it would help and it did a little bit but the issue was still there.

@cba_a3
@ace
@acex
@rhsafrf
@rhsgref
@rhssaf
@rhsusaf
@ace_compat-rhs_armed_forces_of_the_russian_federation
@ace_compat-_rhs-gref
@ace_compat-rhs_united_states_armed_forces
@cup_terrains-core
@cup_terrains-maps
@task_force_radio
@specialist_military_arms
@r3f_advance_logisticsmods
@Aceserver
@mcc
@advanced_rappelling
@advanced_sling_loading
@advanced_towing
@advanced_urban_rappelling
@shacktac_user_interface

were the only loaded mods and I started a huge fight in a major city (Cherno) my FPS dropped to 18-30 in the fight. When I died and respawned about 3km away my FPS came back up to 28-30 but no higher.

My idle fps on the mission is about 60fps.

**Comment by Wyqer** [comment]
Can't say why you experience this issues, but I list some things which I encountered in the log (basically the same as I already did on Discord)

You're missing the ace mod dlls on the server:

    CallExtension 'ace_medical' could not be found
    18:42:18 [ACE] (medical) INFO: Extension ace_medical.dll not installed.

You should have in your ACE mod folder these dlls on your server:

    ace_advanced_ballistics.dll
    ace_advanced_ballistics_x64.dll
    ace_break_line.dll
    ace_break_line_x64.dll
    ace_clipboard.dll
    ace_clipboard_x64.dll
    ace_fcs.dll
    ace_fcs_x64.dll
    ace_medical.dll
    ace_medical_x64.dll
    ace_parse_imagepath.dll
    ace_parse_imagepath_x64.dll

This error message is quite frequently spamming. Personally I never encountered this message in our rpts, so it might be connected with your issue and may come from one of your mods.

    DeleteWeapon: wrong weaponID!

Your HC isn't running RHS USAF

    19:25:25 Warning Message: Addon 'rhsgref_c_air' requires addon 'rhsusf_c_heavyweapons'
    19:25:25 Warning Message: Addon 'rhsgref_c_airweapons' requires addon 'rhsusf_main'
    19:25:25 Warning Message: Addon 'rhsgref_c_vehicles_ret' requires addon 'rhsusf_c_m1117'
    19:25:25 Warning Message: Addon 'rhsgref_c_vehicles_ret' requires addon 'rhsusf_c_statics'
    etc.

Because of this your HC is just spamming and handling "no entry" errors.

    19:25:57 Warning Message: No entry 'bin\config.bin/CfgVehicles/rhsusf_usmc_marpat_wd_rifleman.predictTurnSimul'.
    19:25:57 Warning Message: '/' is not a value
    19:25:57 Warning Message: No entry 'bin\config.bin/CfgVehicles/rhsusf_usmc_marpat_wd_rifleman.predictTurnPlan'.
    19:25:57 Warning Message: '/' is not a value
    19:25:57 Warning Message: No entry 'bin\config.bin/CfgVehicles/rhsusf_usmc_marpat_wd_rifleman.minFireTime'.
    19:25:57 Warning Message: '/' is not a value
    etc.

Do you have `verifySignatures = 2` in your server.cfg? If not, you should activate it, to be sure every connected client has the right mods in the right version. My first guess would be that you've some kind of "mod chaos" between server, HC and all players. Could you post your startup line for the HC and the server? Also the server.cfg and basic.cfg of your server (erase the Admin/Server PW before posting it).

**Comment by LoadingSAa** [comment]
I will post these are they are right now.

https://hastebin.com/itonolipuw.php

The DLL's not loading are due to the server being on linux I tried to research that this is the main github page I could find on this error [Link](https://github.com/acemod/ACE3/issues/4253)

I will try redoing the mods on my HC and redoing the mods command line for it. I will enable verify signatures 2 to make sure everything is perfect.

**Comment by Applejakerie** [comment]
Just a note that I posted a comment on the Zenith mod a while back asking for server keys, you can produce them yourself but I wasn't up for distributing that across every one of my players and our server is public also, no reply yet - will comment again if I get one.

**Comment by LoadingSAa** [comment]
Yeah I saw your comment on the mod page when I was looking into it. I decided the same thing as you.

________________________________

**Comment by LoadingSAa** [comment]
We played with a group of 2 last night and it was much more stable I'm still not happy about going down to >30 FPS still but I don't know if that's the mission or the game..arma is bad. 

I think we will test with 3 tonight and I will post logs of that.

**Comment by LoadingSAa** [comment]
ok this has been fixed with a fresh upload of mods for the HC and server and making sure each client is also running the same mods with verifySignatures = 2.
