### ISSUE TITLE
Suggestion - Add ACE Revive System

### ISSUE THREAD

**Issue by FChapeau** [Wyqer/kp_liberation#280]
I've been playing other missions and came to experience the ACE Medical Revive System. My gaming group and me have become somewhat annoyed that the flow of gaming in Liberation is:

Get in fight -> Get shot -> Die -> Respawn -> Get in fight...

I think that the possibility of using the ACE Revive system would be interesting. It would make the flow more interesting because instead of simply dying, we'd need to be healed and helped back, which makes medics more useful and combat have more meaning, instead of simply respawning when you die.

It could be configured in some way, adding options to enable ACE Revive, set the revive timer, set the number of lives available to players, etc.

I don't know much about Arma mission editing on the scale of Liberation, but I'd be willing to have a crack at it and do a pull request, with some guidance.

**Comment by veteran29** [comment]
Disable BIS Revive module via mission param and ACE medical should be working fine.

https://github.com/Wyqer/kp_liberation/blob/9862bcd3e32d3af9eda2a1a0802ae72fe1e6fc64/Missionframework/ui/mission_params.hpp#L105-L112

**Comment by FChapeau** [comment]
You have me hesitant. I modified my mission_params.hpp on my dedicated server to have this:

```
class ReviveMode {
		title = $STR_A3_ReviveMode;
		isGlobal = 1;
		values[] = {-100,0,1};
		texts[] = {$STR_A3_MissionDefault, $STR_A3_Disabled, $STR_A3_EnabledForAllPlayers};
		default = 0;
		function = "bis_fnc_paramReviveMode";
	};
```
So I'm taking BIS Revive isn't off as it is? If BIS revive is disabled, then we won't just suddenly die, but fall unconscious and need to be healed with the whole blood IV and epinephrine shebang, not just shot, bandage morphine, shot, die?

**Comment by Wyqer** [comment]
https://github.com/Wyqer/kp_liberation#ace-serverside-settings

https://ace3mod.com/wiki/framework/settings-framework.html#32-loading-up-the-server-config

https://ace3mod.com/wiki/

**Comment by FChapeau** [comment]
I'll try this out as soon as I can.

**Comment by Wyqer** [comment]
Liberation is fully ACE compatible.
The things you ask for are only settings you've to do in the ACE mod itself.

**Comment by FChapeau** [comment]
You are right. Thank you very much. I followed the ACE documentation to setup it and the ACE Revive System now works in Liberation.
