### ISSUE TITLE
Undestroyable objects

### ISSUE THREAD

**Issue by TheKukyCZ** [Wyqer/kp_liberation#282]
Hi, I just have a question, it is possible to set up the objects I place as a Commander the parameter "allowDamage false"? I need when I place something, it will be undestroyable.

**Comment by Wyqer** [comment]
If you want specific objects to have specific attributes (like flags with individual textures, buildings undestroyable, vehicle as ACE medic vehicle, etc.), this would be the way:

scripts/client/build/do_build.sqf
beginning at line 321

    switch (_classname) do {
        case FOB_box_typename: {[_vehicle, 3000] remoteExec ["F_setMass",_vehicle];};
        case "Land_Medevac_house_V1_F";
        case "Land_Medevac_HQ_V1_F": {_vehicle setVariable ["ace_medical_isMedicalFacility", true, true];};
        case KP_liberation_recycle_building: {_vehicle setVariable ["ace_isRepairFacility", 1, true];};
        case "Flag_White_F": {_vehicle setFlagTexture "res\kpflag.jpg";};
        case KP_liberation_small_storage_building;
        case KP_liberation_large_storage_building: {_vehicle setVariable ["KP_liberation_storage_type", 0, true];};
        default {};
    };

add there something like:

    case "my_desired_building_classname": {[_vehicle, false] remoteExec ["allowDamage"];};

remoteexec because it's only global as long as the object is local to the builder. If the locality change (builder disconnect or if it's a vehicle, someone get in as driver) it would need to be runned again on the new object owner machine. With the remoteExec you should have it directly global (even if the argument for allowDamage should be local). Refer https://community.bistudio.com/wiki/allowDamage

>Additional Information
Multiplayer: This command only works locally and must be run on all machines to have global affect.

With the above edit, you have it after building. The next edit ensure, that it'll be applied also after loading.

scripts/server/game/save_manager.sqf
line 260 - 289

There are basically the same things like above, just with if constructs. So just add after the last if construct your desired one like this:

    if (_nextclass == "my_desired_building_classname") then {
        [_nextbuilding, false] remoteExec ["allowDamage", 0, true];
    };

**Comment by TheKukyCZ** [comment]
Well, thanks so for example if I want undestroyable razor fence and in do_build.sqf it doesn't defined so I must find name of this fence and just add it?

**Comment by Wyqer** [comment]
Exactly. You just need the classname of the object

**Comment by TheKukyCZ** [comment]
Mkay, thank you very much!

**Comment by TheKukyCZ** [comment]
Hi again, I'm traing it now and I have a trouble w/that. Where I can define false or true? (allowDamage). Thanks
Hi again, I'm traing it now and I have a trouble w/that. Where I can define false or true? (allowDamage). Thanks

**Comment by Wyqer** [comment]
https://community.bistudio.com/wiki/remoteExec

https://community.bistudio.com/wiki/allowDamage

[_nextbuilding, false] remoteExec ["allowDamage", 0, **true**];

**Comment by PhantomViper** [comment]
I am attempting to utilize this to make a concrete gate, that I added to the build menu, indestructible.
The object classname is Land_ConcreteWall_01_l_gate_F. I added this line to do_build.sqf on line 329:
`case "Land_ConcreteWall_01_l_gate_F": {[_vehicle, false] remoteExec ["allowDamage"];};`
Then I added this line of code to save_manager.sqf on line 290:
`			if (_nextclass == "Land_ConcreteWall_01_l_gate_F") then {
				[_nextbuilding, false] remoteExec ["allowDamage", 0, true];
			};`
The wall are still getting taken down by getting hit by cars and rockets.

**Comment by Wyqer** [comment]
Guess it's a difference for ArmA if it's a building or a vehicle concerning allowDamage. You could give `enableSimulationGlobal` a chance by setting it to false for the wall.

**Comment by PhantomViper** [comment]
@madpat3 How was this inserted into the code on your end? When I insert it into my code using any classname it breaks do_build.sqf as a whole. When I use build all items I want to build aren't visible in any form.

**Comment by madpat3** [comment]
e.g. this in the do_build.sqf:
case "Land_BarGate_F": {_vehicle addEventHandler ["HandleDamage", {0}]; //somewhere after line 326 

and this in the savemanager.sqf:
if (_nextclass == "Land_BarGate_F") then { _nextbuilding allowDamage false;}; // here for some reasons allowDamage works as well.

**Comment by TheKukyCZ** [comment]
Hi again, so I tried both of option. From @Wyqer it doesn't work. If I used that from @madpat3 my build menu was broken totaly and I couldnt build anything.

**Comment by TheKukyCZ** [comment]
My files example:
https://pastebin.com/cZykUdMe

**Comment by madpat3** [comment]
after line 348 in the build.sqf, it should look like this:
`if (_classname == "Land_Razorwire_F") then {
					_vehicle addEventHandler ["HandleDamage", {0}];
				} else {
				
				sleep 0.3;
				_vehicle allowDamage true;
				_vehicle setDamage 0;
				};`

in the savemanager.sqf it should look like this:
`if (_nextclass == "Land_Razorwire_F") then {
				_nextbuilding addEventHandler ["HandleDamage", {0}];
			};`

**Comment by TheKukyCZ** [comment]
@madpat3 after a hundred attempts and lots of codes, only Yours is working! I love You man! Thankssss!!

**Comment by madpat3** [comment]
glad i could help. 
but be aware, sometimes i've noticed, even this hangs up and doesn't work. but after restart of the mission, it works again. no idea why this is.
