### ISSUE TITLE
Crates disappearing after unloading more than one crate

### ISSUE THREAD

**Issue by NomadRomeo** [Wyqer/kp_liberation#283]
### Basic Information
**Mission version:** 0.961.
**Map used:** KP Liberation Takistan / KP Liberation Tanoa.

**Mods used:**
@Advanced Rappelling, @Advanced Towing, @Advanced Urban Rappelling, @Blastcore Edited (standalone version), @CBA_A3, @CUP Terrains - Core, @CUP Terrains - Maps, @Enhanced Movement, @Project OPFOR, @RHSAFRF, @RHSUSAF.

**Dedicated or local game?**
Hosted game (with a friend to help me test).

**GitHub or Workshop mission file?**
Steam Workshop.

### Individual Things
**Did you edit anything within the mission files?**
No.

**If yes, what did you edit exactly?**
-

### Short Issue Description
After trying to unload more then one crate from the transport helicopter, instead of being stacked side by side, they disappear. Checked around the location, inside the helo and found nothing.

### Expected Behaviour
They should be either stacked side by side or near the helicopter.

### Steps to Reproduce the Issue
After noticing the issue more than twice on Takistan, decided to test on Tanoa's KP Liberation.
**1.** Loaded **one** box inside;
**2.** Took off and landed the helicopter;
**3**. Checked if the crate was still inside;
**4.** Selected the UNLOAD CRATE option: Worked fine;
**5.** Did the same as steps 1-4 but with **two** boxes inside. All crates gone.
**6.** Repeated steps 1-4 with **three** crates. All crates gone.

**PS.:** I repeated those steps at least three times on Takistan and twice on Tanoa.
Managed to parachute some crates to keep the game going, but that wasn't possible on Tanoa. The transport helo doesn't have this option.

### Screenshots, Serverlog or any other helpful Information
**Screenshots:** Perhaps I'll add a video later.
**Serverlog:** You'll have to walk me through this. Never did it.
**Any other helpful Information:** I can try it without mods if necessary.

**Comment by Mike2306** [comment]
I faced the same problem twice so far.
The crates do not disappear they glitch into the ground.

Take a look with Zeus you will see them "floating" under the ground.

**Comment by NomadRomeo** [comment]
Yeah, I thought about that but forgot to use Zeus. Can we "unglitch" it somehow?

**Comment by Wyqer** [comment]
Was able to reproduce this (which is indeed new since the last ArmA 3 Update).
I've tweaked the unload script. Replaced the deprecated and old bis_fnc_relPos with the new syntax from getPos. In my tests this more perfomant way of unloading fixed the "crates sink into ground" issue for me.

**Comment by NomadRomeo** [comment]
Thanks Wyqer!
