### ISSUE TITLE
Immortality in unconsciousness

### ISSUE THREAD

**Issue by TheKukyCZ** [Wyqer/kp_liberation#285]
Hi again, I sorry, couse I think that this question was already somewhere here, but I cant find it, so I need to ask again. Is it posible when I'm using basic revive system and Ai shoot me down. I stay "down" and in that time I can't get any damage? Because for example when Tygris shoots me Im instantly dead and I need to stay only in first stage of dead when medic can revive me. It's okay to bleed out, just do not die with more damage. I hope that you will understand :D Thanks.

**Comment by Wyqer** [comment]
Hey there.
You're talking about the vanilla revive system from BI, right?
If you leave it at the basic setting (which is default) it should have exactly the behaviour you're describing.

> Basic
> Basic is the least-harsh preset. Damage received is calculated in the same way as is in vanilla, non-modded Arma 3. The defining difference is that the player will always enter the incapacitated state when they would otherwise be killed.

Refer to:
https://community.bistudio.com/wiki/Arma_3_Revive

**Comment by veteran29** [comment]
Basic revive guarantees that you will always go into unconscious mode, however if something like Tigris or ZSU shoots at you it usually shots with short bursts and u are killed when lying in unconscious state.

I guess to prevent that you would need some event handler that will disable damage when player goes into unconscious state. Adding something like this would need some code modifications.

**Comment by TheKukyCZ** [comment]
Yes, I mean vanilla revive system. It works like first shoot = unconscious, second (when you're already in unconscious) = dead > you must respawn, select new gear... And I need to disable that thing (when you're unconscious you can die after second hit (shoot, explosion...)). But I don't know how, or is it even possible?

**Comment by Wyqer** [comment]
Mostly "everything" is possible. It's only a question if the work is in balance to the benefit.

So as @veteran29 already mentioned you could use a event handler or a watch script which sets the player to be invincible while unconscious. But I would doubt that this would be always fast enough to prevent the death of a ZSU firing multiple shots at you.

From the "normal setting framework" which comes with the BI Revive there is no way to achieve that. So if you would have to code it.

**Comment by TheKukyCZ** [comment]
Well, thanks for the answers, I'll see what I'll do with it.
