### ISSUE TITLE
Virtual Arsenal blocked save/load.

### ISSUE THREAD

**Issue by Applejakerie** [Wyqer/kp_liberation#296]
### Short Issue Description
Just wanted to see if there's any additional issues like this from other users.

vArsenal save and load blocks loadouts at random. I have two loadouts, both exactly the same. One is blocked, the other is fine. If I exit the save/load screen then go back, it might be a different combination (both blocked, both fine or vice versa to the original issue etc). It's seemingly entirely random, can be a pain when the save/load function already can take a few seconds to open. There are no "issue items", all loadouts can be taken fine from the original "easy pick" menu, only happens once inside vArsenal and again, very random (closing and opening the save/load menu changes up the issue). I've experienced this on different combinations of mods and maps.

### Expected Behaviour
For it to be smooth and wonderful. :wink: 

It just shouldn't be randomly blocking loadouts for no reason and at different times/loadouts.

**Comment by Applejakerie** [comment]
In the first image below, I was unable to load any of the greyed out loadouts. They have no "issue items" as said before, I was using them fine in my last session also and can load them fine in this session via that "easy pick" menu. Then 5 minutes later after a restart, same loadouts are greyed but this time I can still click load. I was thinking it'd be usual Arma "feature not a bug" but wanted to point it out and get some feedback.

![load_unable](https://user-images.githubusercontent.com/20494241/33911673-fc67d0ae-df8a-11e7-9bcf-251d9fc303ed.JPG)
![load_able](https://user-images.githubusercontent.com/20494241/33911676-fe6ca55a-df8a-11e7-85ff-576500a732c3.JPG)

**Comment by Wyqer** [comment]
I've experienced the same strange behaviour in the virtual arsenal sometimes. But I was always able to click on "load", even if the loadout was greyed out in the list. My guess is that you're right that it could just be an "ArmA Thing" when you use some mods which add gear content, etc.

**Comment by Applejakerie** [comment]
Yea, I definitely couldn't load anything greyed in the first instance. It's why I didn't think to include the load button in the snip at the time. Will post any new info of it if I can. Hoping it's not an Arma thing as it bugs me to hell! 😛

**Comment by Applejakerie** [comment]
Today I have greyed loadouts but I can save/load always as you say. Yesterday I definitely couldn't save some loadouts, I'd have to empty the save name, write a new one and then save, that works fine. Saving over the greyed save tho sometimes seems disallowed.

**Comment by FatRefrigerator** [comment]
Is the massive amount of lag you get when you load a loadout also an Arma thing? Whenever I host locally i have to yell "lag inbound" whenever choose a loadout.

**Comment by Applejakerie** [comment]
I don't know about it hitting other clients however I play on a dedicated server but yea, I get a "loading time" per  save/load action, 2-5 seconds at least. Would be okay if it was the first action but every action in the same arsenal "session" seems excessive. I only have 5 or 6 loadouts and we don't use Vana Loadout Management as that adds no end of lag to the server.

**Comment by madpat3** [comment]
are you using the blacklist method? i think that's the point, because the crawler must search every loadout for blacklisted items.
