### ISSUE TITLE
Build menu

### ISSUE THREAD

**Issue by NomadRomeo** [Wyqer/kp_liberation#299]
### Basic Information
**Mission version:** 0.962
**Map used:** Takistan
**Mods used:** @advanced Towing, @advanced Urban Rappelling, @blastcore Edited (standalone version), @CBA_A3, @cup Terrains - Core, @cup Terrains - Maps, @enhanced Movement, @project OPFOR, @rhsafrf, @rhsusaf.
**Dedicated or local game?** Local game
**GitHub or Workshop mission file?** Steam Workshop

### Individual Things
**Did you edit anything within the mission files?** No.

**If yes, what did you edit exactly?** -

### Short Issue Description
Build menu buttons won't work after selecting the **infantry squads** build menu. After spawning a vehicle, the menu works, but only spawns the first infantry squad of the list, even if selecting another one.
If I open the build menu, all options will work until I click on the **infantry squads** menu. To make it possible to spawn a squad, first it's needed to try building a vehicle.

On 0.961 it was working fine. I tested both missions to check before the official update, when I was working on the portuguese localization.

### Expected Behaviour
After clicking the options, the buttons should work fine.
This was happening before the official release of 0.962.

### Steps to Reproduce the Issue
**1**. Hosted the mission, selected the commander slot and spawned on FOB Alpha;
**2**. Opened the **build menu**, selected **infantry squads** build. All options appear unavaiable. Unit cap is 25/50;
**3**. Opened the **build menu** again, selected **infantry squads** option, still not working - Buttons are grey;
**4**. Reopened the **build menu**, selected any **vehicle** to spawn. Spawning vehicles works;
**5**. After trying to spawn a vehicle, the **infantry squads** build button works;
**6**. Tried to select a paratrooper squad: It spawns the first squad only, light infantry. I had resources to create all of them;
**7**. Repeated step 4 and 6. You can only spawn a specific infantry squad if it was already selected on the last try.

### Screenshots, Serverlog or any other helpful Information
https://www.youtube.com/watch?v=XJ8UswkQP6Y&t=42s
Ps.: Sorry for the low quality.

**EDIT:** On the video, the squad menu won't work. It only works after opening again directly on the squad menu. If I switch to another tab, it bugs.

[Liberation 0.962 .rpt file - Build menu issue.zip](https://github.com/Wyqer/kp_liberation/files/1556316/Liberation.0.962.rpt.file.-.Build.menu.issue.zip)

**Comment by Wyqer** [comment]
Thanks for the exemplary issue report.
I'll have a look at this issue in the next days, as I don't have time this evening anymore.
But as far as I know @Applejakerie want to try to reproduce this.
So if anyone can also reproduce this issue, I would be glad for more information. Personally I've never experienced that issue, but as you say it only happened since 0.962 for you.

**Comment by NomadRomeo** [comment]
Yes, and even after the official release.
I switched to english to see if the portuguese localization had anything to do, but it still happens.
Tonight I'll try to reproduce that on Tanoa. Couldn't do today as I didn't have enought resources ingame.

Thanks for you time.

**Comment by Applejakerie** [comment]
- Hosted the mission. Commander slot. FOB Alpha.
- Opened build. Selected infantry squads tab. All are available. (ERROR HERE).
- Purchased light infantry squad, got recon squad.
- Opened infantry squads tab again. All are available. (ERROR HERE).
- Purchased recon squad, got light infantry squad.
- Can swap between all tabs perfectly fine.
- Opened infantry squads tab again. All are available. (ERROR HERE).
- Purchased AT squad, got AA squad. (ERROR HERE).
- Went over unit cap, deleted squads with zeus, unit cap is back at 1/25.
- Opened infantry squads tab again. All are locked with no reason to be, possibly doesn't know the unit cap is low again? Error on `scripts\shared\functions\F_kp_isClassUAV.sqf`.

- Can't swap any tabs anymore either.

`17:23:53 Error in expression <( getNumber(configFile >> "CfgVehicles" >> _vehicleclass >> "isUav") == 1 && (ty>
17:23:53   Error position: <>> _vehicleclass >> "isUav") == 1 && (ty>
17:23:53   Error >>: Type Array, expected String`

[Arma3_x64_2017-12-13_16-57-11 - Copy.txt](https://github.com/Wyqer/kp_liberation/files/1556398/Arma3_x64_2017-12-13_16-57-11.-.Copy.txt)

**Comment by veteran29** [comment]
Woops. I think I'm responsible for this bug.

**Comment by enhanced** [comment]
Can you guys remove the @enhanced from the bug info, that pulls me into the
thread.

**Comment by NomadRomeo** [comment]
Issue resolved.
Closing it now.

Thanks Apple, Wyqer and everyone involved!
