### ISSUE TITLE
Class system

### ISSUE THREAD

**Issue by jus61** [Wyqer/kp_liberation#3]
With a mission option, alternative loadouts system that enforces actual classes instead of people being able to play rambo (a side effect of the option to remove fatigue entirely...)

**Comment by Wyqer** [comment]
I'll have a look into that, but if I'll implement it, then only as optional parameter.
That's because I don't want to create real restrictions for groups which are capable of organizing themself in a senseful way.
For only 24/7 public server this could be more interesting, sure.
