### ISSUE TITLE
suggestion: manned vehicles with selected preset-crew 

### ISSUE THREAD

**Issue by madpat3** [Wyqer/kp_liberation#305]
the commander can build manned vehicles.

these vehicles should be manned with members of the blufor faction of the selected preset.

**Comment by Wyqer** [comment]
It's already that way.

Have a look at these links:
https://github.com/Wyqer/kp_liberation/blob/master/Missionframework/presets/blufor/rhs_usaf_wdl.sqf#L18
https://github.com/Wyqer/kp_liberation/blob/master/Missionframework/scripts/client/build/do_build.sqf#L317
https://github.com/Wyqer/kp_liberation/blob/master/Missionframework/scripts/shared/functions/F_forceBluforCrew.sqf#L12

**Comment by madpat3** [comment]
then maybe it's a bug. on lythium, when i spawn a vehicle, it uses the default crew. e.g. for a quadbike>vanilla crew. rhs hummvee>rhs crew.

**Comment by Wyqer** [comment]
You used the custom.sqf and edited it for your mission? Look what crewman classname is in your edited preset file.

**Comment by madpat3** [comment]
i use bwmod_des.sqf
crewman_classname = "BWA3_Crew_Tropen";

[bwmod_des.zip](https://github.com/Wyqer/kp_liberation/files/1598588/bwmod_des.zip)
