### ISSUE TITLE
Suggestion: Enemy artillery and mortar positions

### ISSUE THREAD

**Issue by SondreBakken** [Wyqer/kp_liberation#308]
I have been playing around a bit and found a script I would really like to recommend!

https://forums.bistudio.com/forums/topic/159152-fire-for-effect-the-god-of-war-smart-simple-ai-artillery/

A rather small script. Easy to edit and incorporate. Behaviour can be changed in the config, but default is that they will fire once or twice to in order to adjust their fire then unleash a longer series of shots. Gives nice suspense and realistic feel

I used it in a experimental sector mission where I spawned in 0-2 mortars whenever a sector was initialized. 

Gave the mission a very different dynamic when you knew that there was a chance of taking mortar fire from the city you are trying to overtake when your position is discovered. 

Also spawned mortar positions on random. They would fire at your position if anyone from their side spottet you. Could work great with asymmetric threat if you spawn a mortar position and some spotters that would advance towards your FOB. 

Creates realism much similar to what happens in war zones (I learned that this is one of the most credible treats to fobs around the middle east). FOBS suddenly takes mortar fire. You have to get out there and locate the insurgent mortar position.

It also works for bigger artillery, so whenever battle groups are spawned you could incorporate some heavier artillery that would fire at you :smiley:

**Comment by Wyqer** [comment]
Artillery in general like mortars etc. will be implemented for the enemy. Guess it'll be part of 0.97.
But I would write own mechanics for it.

So this suggestion is basically accepted and already planned. But implement a 3rd party script for this is denied.

And I agree fully that it would really improve the feeling to have a possible threat of artillery fire support for the enemy, if you engage him. It'll be some work to find a good balance, as a mortar can easily kill a group of players. From my experience the AI is quite accurate with their mortars.

**Comment by SondreBakken** [comment]
Well, it wont really be a third party script since you copy and maintain it, maybe refactor it. 

My experience with this script is that it does a lot of things right, and in order for you to make the best script possible, I guess it would be helpful to look at / take inspiration from this script. Why reinvent the wheel if its already right in front of you.

About your last paragraph saying it can be to efficient. This script solves this really well with parameters for accuracy, and also it simulates real life behaviour  by letting a spotter report in coordinates, the artillery fires two shots that are very inaccurate, where the hits are reported back and after that there will be a more accurate barrage.

This works very well because it creates a lot of suspense when you hear or see some artillery explosions in the area, because you are not sure whats the target, it might be you or something else in the area, you know that there is a spotter you should locate in order to stop the artillery and you have to move/take cover asap

**Comment by veteran29** [comment]
I agree that _FFE_ script is nice and maybe it could be useful as "inspiration" how to do things right regarding artillery. However I think APL-SA licence that it is distributed with, is not compatible with GPL. Liberation will be distributed on GPL license from 0.97 as far as I know.

[APL-SA](https://www.bohemia.net/community/licenses/arma-public-license-share-alike) requires to distribute code based on it to use same license type.

However after looking at upcoming modular structure of 0.97 (which looks very promising 😛) I could try to implement this script as plugin/module to liberation. Code of the module would be in separate repository so there will be no license problems.

**Comment by veteran29** [comment]
Ofc. there is no sense in making it into separate module if 0.97 will have own implementation of artillery from "_launch_" version.

**Comment by Wyqer** [comment]
I guess I'll have something in the 0.97 (which will overhaul the enemy stuff beside of the code).
The "denied" is just for the script itself, not the functionality that the enemy should have some mortar/artillery capabilities, which is something I also want to have in the mission :)
