### ISSUE TITLE
Suggestion: Patrol Ops Integration as Secondary Objective

### ISSUE THREAD

**Issue by glothos** [Wyqer/kp_liberation#309]
Hello guys. Its just a suggestion. Would be possible to add a Patrol Ops as secondary objective to decrease the enemy alert? Mostly the mission would have ambushes but sometimes it could just go smoothly, depending on the current alert level. The players would have to go to captured town from another captured town following another AI squad that would walk through the road  and if all of them get killed the mission fails.

**Comment by Wyqer** [comment]
I'll keep that kind of mission in mind. Basically there will be more sidemissions (especially some which are connected to the civil reputation) in the future versions, of course.
I just think that a "follow this AI squad and guard them" could be very frustrating sometimes. They can stop after a firefight for some time or have general bugs. Failing when they're all dead can also happen very quick, I guess. So personally I think it would be better to not include anything AI related, but some kind of patrol tasks sounds not bad.

**Comment by glothos** [comment]
I suggested an AI squad so the player doesn't rush to the waypoint. Would there be another way to prevent that?

**Comment by Takahashi-Yuuki** [comment]
It's possible to encourage player to hang around in an area by using delays between waypoints. Guard waypoints would be especially useful in this regard. Not really any way to stop players from barrelling from point to point in a jeep though.
