### ISSUE TITLE
RHS Afrf weapons or equipament not allowed

### ISSUE THREAD

**Issue by tiagoaraujo555** [Wyqer/kp_liberation#311]
### Basic Information
**Mission version:**0.963
**Map used:**Tanoa
**Mods used:**ACE, RHS
**Dedicated or local game:** Local game
**Source of the mission file (URL):**

### Individual Things
**Did you edit anything within the mission files?**
yes

**If yes, what did you edit exactly?**
Custom arsenal

### Short Issue Description
any weapon or added equipment of the Rhs Afrf added to the custom arsenal is not allowed, but when they are not added in whitelist they work perfectly

### Expected Behaviour
allow only the weapons of the Rhs Afrf

### Steps to Reproduce the Issue
add only afrs equipment in whitelist

### Screenshots, Serverlog or any other helpful Information
![sem titulo1](https://user-images.githubusercontent.com/35400589/34906898-76a69c3e-f85d-11e7-9dad-fc3fe10f377f.png)
![sem titulo](https://user-images.githubusercontent.com/35400589/34906900-7ae5bd52-f85d-11e7-88cd-5d42b4b4bd22.png)
![sem titulo3](https://user-images.githubusercontent.com/35400589/34906901-7e05feca-f85d-11e7-983f-7b3938936a75.png)

**Comment by Wyqer** [comment]
You have to enter the classnames case sensitive in the arrays. So exactly like the real classname is provided from the mod.

    rhs_weap_ak74m in [RHS_WEAP_AK74M] // false
    rhs_weap_ak74m in [rhs_weap_ak74m] // true
