### ISSUE TITLE
Problem with AI spawning too closer when in air vehicle

### ISSUE THREAD

**Issue by AngusDLX** [Wyqer/kp_liberation#313]
### Basic Information
**Mission version:** 0.963
**Map used:** Altis
**Mods used:** RHSUSAF, JSRS4, Advanced SlingLoad, CUP Terrains Complete,  
**Dedicated or local game:** LAN
**Source of the mission file (URL):**

### Individual Things
**Did you edit anything within the mission files?** Yes

**If yes, what did you edit exactly?** Buildings and Vehicles

### Short Issue Description
When we are just me and my friend on the server and in the same air vehicle as for example an AH-64D and we go close to a sector, the AI only spawns when we are more or less 500 meters of distance. Impossible for a reconnaissance flight for example or attack beacause AI will spawn.

### Expected Behaviour

AI will spawn and kill us for being very close

### Steps to Reproduce the Issue
None, i think

**Comment by Wyqer** [comment]
You could raise the activation range in the config or (which would be the recommended method) just let a drone fly near the sector or similar.

**Comment by AngusDLX** [comment]
Thank you Wyqer!

Some way to change the air vehicle limit by FOB?

**Comment by Wyqer** [comment]
https://github.com/Wyqer/kp_liberation/wiki/EN:FAQ#buildings-and-their-purposes

    Flight Control
    Helipad
    Tent Hangar

You could lower the prices in the preset file to make it a little bit easier if your play with just 2 people.
