### ISSUE TITLE
[Suggestion] Enemy navy

### ISSUE THREAD

**Issue by RaulPro19** [Wyqer/kp_liberation#314]
I think that it would be nice that in coastal bases or in enemy ports, enemy ships can be spawned, or if you have your FOB in an island, they could attack you by water.

**Comment by Blakmane** [comment]
Pretty sure this is planned, but non-trivial to execute because the game needs to figure out what is water, what is enough water to spawn boats, where to spawn the boats etc etc. The Arma engine isn't particularly good or forgiving with water things in general, unfortunately.

**Comment by Wyqer** [comment]
#90
