### ISSUE TITLE
Bug: Action Menu Duplicates

### ISSUE THREAD

**Issue by Utmanarn** [Wyqer/kp_liberation#315]
### Basic Information
**Mission version:** 0.963
**Map used:** Tanoa
**Mods used:** Advanced Ai Command, C2 - Command & Control, ace, Advanced Rappelling, CBA_A3, Advanced Sling Loading, Enhanced Movement.
**Dedicated or local game:** Local
**Source of the mission file (URL):** https://steamcommunity.com/sharedfiles/filedetails/?id=878714108

### Individual Things
**Did you edit anything within the mission files?**
Nothing at all. (Only Lobby perams)

**If yes, what did you edit exactly?**

### Short Issue Description
My action menu get's duplicates of Build, Redeploy, Logistics, and all those stuff.

### Expected Behaviour
Only 1 of each menu item(s).

### Steps to Reproduce the Issue
Stand next to FOB, on map go to remote unit (Mod), remote control any of your ungrouped Ai unit then go back to your character and then do that 2-3 times and you have the bug!

### Screenshots, Serverlog or any other helpful Information
For all the 4 times I tried this it always came up. Only way I found to fix it was to go back to the Role Selection screen which is very annoying.
![20180118192229_1](https://user-images.githubusercontent.com/26390071/35114771-389df716-fc86-11e7-8978-e25755882fbd.jpg)
![20180118192238_1](https://user-images.githubusercontent.com/26390071/35114773-3f820cac-fc86-11e7-9b20-d7a7c1cee6fe.jpg)
![20180118192246_1](https://user-images.githubusercontent.com/26390071/35114776-43b6e7d4-fc86-11e7-83a1-e0b3a3c9bee8.jpg)

**Comment by Wyqer** [comment]
That's not a bug basically.
As far as I know it don't happen if you use remote control from zeus or with the Liberation group manager.

I've never used the mod you mention (I guess it's through "Advanced Ai Command" or "C2 - Command & Control"). Currently there won't be a "workaround" for 0.963 for this glitch through the usage of one of these mods. Next step is the refactoring which will end in the release of 0.97. After that release you would need to check if it still occurs. If it does, report back to this issue.

I guess you can expect 0.97 in 2-3 months.

**Comment by Utmanarn** [comment]
Ok
