### ISSUE TITLE
Vanishing Vehicles

### ISSUE THREAD

**Issue by RegoxXVII** [Wyqer/kp_liberation#319]
Experiencing an issue where upon reloading of server, buildings at FOB's save fine, but any and all vehicles there vanish on restart.. Using lib Tanoa, tried a full restart but issue persists. Only vehicle that has remained sofar has been one built at the FOB, but all captured and also zeus vehicles vanish.

**Comment by Wyqer** [comment]
The template which you see upon creating an issue isn't meant to be deleted.
Mission version?
Map used?
Mods used?
Dedicated or local game?
Source of the mission file (URL)?
Did you edit anything within the mission files?
If yes, what did you edit exactly?
Append serverlogs from "put a vehicle at the FOB" and "vehicle is gone after loading".

**Comment by RegoxXVII** [comment]
Apologies

Liberation 0.963, Tanoa, modlist is [img]https://i.imgur.com/Zaw9H1a.png[/img] , LAN game for sp, obtained from here, edited to allow zeus usage according to the instructions in the FAQ under "How can I enable full zeus?"

**Comment by Applejakerie** [comment]
You might wanna also include a report file. You wanna start the mission, reproduce the bug, stop and start the mission and if vehicle is missing, then find the report file at `D:\Users\<PCNAME>\AppData\Local\Arma 3`, it'll be named like `Arma3_x64_2018-01-18_18-00-39` but with an appropriate date and time at the end.

**Comment by Wyqer** [comment]
And as you still starting a new game....
Do this once with your modlist and if it still happens, do it also with the exact same missionfile but without any mods.

**Comment by RegoxXVII** [comment]
Logs attached, first one on exit with a FOB full of vehicles, second on log in with only the built truck and a civvie hatchback remaining.

[Arma logs.zip](https://github.com/Wyqer/kp_liberation/files/1650922/Arma.logs.zip)

**Comment by RegoxXVII** [comment]
Tried running the same mission without mods, same results

**Comment by RegoxXVII** [comment]
Tried a fresh restart with no mods in, still no vehicle persistence.
[Logs2.zip](https://github.com/Wyqer/kp_liberation/files/1654119/Logs2.zip)

**Comment by Wyqer** [comment]
Ok, I think I've a good guess what's the "issue".
If I look at the timeframe for the test (you started with a fresh save, right?), I just want to make sure:
You deploy your first FOB with the container from the beginning? Or do you place a vehicle via Zeus at the "Operation Base" where you initially start the campaign? Because the only "save areas" are around a FOB and the "Operation Base" don't count as FOB.

**Comment by RegoxXVII** [comment]
Created a FOB a few times, and then used the spawn with a FOB on shore option, still no change. Doing a full reinstall of arma anyway, will see if that fixes the issue.

**Comment by Wyqer** [comment]
Very strange. If you capture a sector it'll be saved as captured, but the vehicles at your FOB are gone?

**Comment by RegoxXVII** [comment]
Indeed, buildings and supplies persist, same as vehicles built at the FOB, but seized vehicles and zeus stuff wouldn't

**Comment by Wyqer** [comment]
> vehicles built at the FOB [...] zeus stuff wouldn't

The save system only saves vehicles, AI and buildings which are available in the build menu (depending on your chosen preset). If you place down a vehicle with zeus which you couldn't also build via the build menu, it won't be saved. That's the normal and intended behaviour.

**Comment by barlach** [comment]
I can confirm this behaviour version 0.963 Sahrani on hosted LAN.
I tried to wipe my profile and start a new game.
1. Deployed a FOB
2. Bought a truck and 1 rifleman, left the game running for another 5 minutes (didn't take any sectors) .
3. Restarted server

Result:
FOB and buildings still in place. Huron still located at FOB. Truck and rifleman gone. Resources were not reverted (not sure if they are meant to be?)

I can try and do the whole thing again with only the recommended Mods if that helps you?

**Comment by Wyqer** [comment]
Append a log if you can reproduce it again.
Also enable the save debug in the mission parameters.
You can find your local log here: C:\Users\<yourname>\AppData\Local\Arma 3

**Comment by barlach** [comment]
I started a new game on Takistan 0.963 with only the required mods loaded.
Deployed a FOB
Bought a truck and 1 rifleman, left the game running for another 5 minutes (didn't take any sectors) .
Restarted server

Result:
Truck was still present after restart but unit was gone (along with resources).
I've attached the logs.

[Arma3_x64_2018-02-13_20-42-24.rpt.txt](https://github.com/Wyqer/kp_liberation/files/1721757/Arma3_x64_2018-02-13_20-42-24.rpt.txt)
[Arma3_x64_2018-02-13_20-59-14.rpt.txt](https://github.com/Wyqer/kp_liberation/files/1721758/Arma3_x64_2018-02-13_20-59-14.rpt.txt)
[mpStatistics_4612.log](https://github.com/Wyqer/kp_liberation/files/1721759/mpStatistics_4612.log)
[mpStatistics_7772.log](https://github.com/Wyqer/kp_liberation/files/1721760/mpStatistics_7772.log)

Let me know if you need anything else.

PS. Thanks for the awesome work!!

**Comment by Wyqer** [comment]
AI in a player squad won't be saved.
You've to ungroup any AI soldiers from the player squad via zeus (ctrl drag).

**Comment by barlach** [comment]
I see, thanks.
I'll let you know if I encounter the vehicle problem again as I enable mods.

**Comment by AmkoTheTerrible** [comment]
Having the same problem, running CBA, RHSUSAF, RHSAFRF, RHSGREF, RHSSAF

FOBs, Sectors, Buildings, etc, all save and load without fail. Vehicles do not, and the resources are not refunded.

**Comment by Wyqer** [comment]
And where do you have the vehicles? And which vehicles? Little Birds from the Carrier/Base? Built vehicles? Placed down with Zeus? etc.

**Comment by AmkoTheTerrible** [comment]
The hummingbirds and huron from the base do not despawn, the build vehicles built via the Build menu, despawn upon reloading.

Playing on Altis, and mostly using RHSUSAF vehicles, the HUMVEE, MRAP, LMTV, Bradley.

**Comment by Wyqer** [comment]
The Little Birds are always respawning at the carrier/base upon server restart.
And other vehicles are only saved inside the FOB build radius. And if they are not part of a players squad (if manned by AI).
Built vehicles are also only saved if they are in the built list (listed in the preset).
You can activate the save debug parameter to have the full save data listed in the server log upon save. There you can have a look if the vehicles are listed there or you put your serverlog with this debug output here.
In general I can't confirm any issues with the saving of built vehicles.

**Comment by AmkoTheTerrible** [comment]
It seems to be limited to RHS Vehicles, theyre in the FOBs area, built from the build list, but dont show up on the right
https://i.imgur.com/UHeZZq9.jpg Here is a screenshot, the RHS Blackhawk bought from the Build menu, after building the flight control and two helipads, giving us a capacity of 2 helicopters. The flight control and helipads WERE necessary to be able to build the Blackhawk as well, but it isn't taking up one of the capacity.

When building something, there is two buttons, Build and Build [Crew], what is the difference between these?

**Comment by AmkoTheTerrible** [comment]
Additionally, i am unable to spawn or select RHS vehicles or objects from the Zeus menu, despite having set the GM module to accept all addons, even unofficial.

https://i.imgur.com/2Orl25m.jpg

**Comment by AmkoTheTerrible** [comment]
Curiously, when i open the mission in the editor, i can spawn in RHS stuff, but when I'm in Zeus on the server, i cant spawn them in, but can buy them with the in-game build menu, though these cannot be recycled, selected or edited with Zeus or persist on the server being reloaded.

**Comment by Wyqer** [comment]
Are you sure you've done all necessary edits concerning zeus? (like it's described in the FAQ in the wiki)
Do you've any mods installed beside of the RHS ones? Especially which may alter vehicle attributes or anything.
Attach a server log and your preset file.

**Comment by AmkoTheTerrible** [comment]
I've done all the necessary edits, checked seveal times, and the only mods we're running are CBA_A3, RHSAFRF, RHSUSAF, RHSGREF, and RHSSAF

[report.txt](https://github.com/Wyqer/kp_liberation/files/1844833/report.txt)
Github wont let me attach the preset file, so here is a launcher screenshot https://i.imgur.com/8jVOyKi.png

**Comment by AmkoTheTerrible** [comment]
Are the RHS vehicles not included in the CfgVehicles for the Altis version of the mod?

**Comment by Wyqer** [comment]
It is. And due to a look at your log I've your solution: You've to load the mods on the server, too. Not just on the client.

**Comment by AmkoTheTerrible** [comment]
I'm using TADST, and the content is on the server, we're able to equip RHS uniforms, weapons, and save them as loadouts. Just the vehicles giving us these problems.

**Comment by rufjame** [comment]
Your report.txt is showing that it can't find the RHS vehicles. Instead of loading the workshop folder as a mod, load the mods in the workshop folder. If vehicles are still disappearing please attach another rpt.

**Comment by AmkoTheTerrible** [comment]
THAT DID IT, THANK YOU SO MUCH

**Comment by Wyqer** [comment]
> we're able to equip RHS uniforms, weapons, and save them as loadouts
> We CAN spawn and use the vehicles

Which is always possible if you've loaded the mod as a client. But the server don't have the mod loaded, which is required for Liberation (and basically also in general ArmA) to work without errors and as intended.

**Comment by AmkoTheTerrible** [comment]
I feel like an idiot now, i thought TADST loading the !Workshop folder would work, it's one of its basic options i never looked into it.
