### ISSUE TITLE
Problem with loading map on dedicated server, user error? res/dkflag.jpg not found?

### ISSUE THREAD

**Issue by Paxton1997** [Wyqer/kp_liberation#320]
Everytime I try to load the map on my newly created dedicated server, i get this error and returns to map select screen, is it a problem with the mission files?

 3:39:47 Mission kp_liberation.Malden read from directory.
 3:39:49 Roles assigned.
 3:39:49 Reading mission ...
 3:39:57 Picture res\kpflag.jpg not found

**Comment by Wyqer** [comment]
Please fill the issue report template (the text which you deleted). These informations are necessary for a quick review of your issue. Otherwise I would need to ask for these informations step by step (some kind of similar to now) and take unnecessary time of you and me.
Your log tells you the issue, by the way: `Picture res\kpflag.jpg not found`

**Comment by Paxton1997** [comment]
### Basic Information
**Mission version:0.963**
**Map used:altis/tanoa/malden**
**Mods used:none**
**Dedicated or local game:dedicated**
**Source of the mission file (URL):**

### Individual Things
**Did you edit anything within the mission files? No**


**If yes, what did you edit exactly?**


### Short Issue Description
Trying to load map on dedicated server results in the same error message everytime. "Res\kpflag.jpg not found" but when i go to the directory it is sitting in the directory

### Expected Behaviour
Read kpflag.jpg since its right there.

### Steps to Reproduce the Issue
Put the mission files in mpmissions folder on arma 3 server directory and start the server and try to load the mission.

**Comment by Paxton1997** [comment]
Mission file source: steamapps\common\arma 3 server\mpmissions

**Comment by Wyqer** [comment]
Do you use a prepacked pbo from the releases tab or did you downloaded the master from github and build the mission with the framework by yourself?

> Mission file source: steamapps\common\arma 3 server\mpmissions

The question concerning the source of the missionfile is aiming to know if it's from GitHub, Workshop and if it's one of the "original KP" files and not from someone who published a "modified" version with own edits etc. But I guess you've taken it here from GitHub.

**Comment by Wyqer** [comment]
> i get this error and returns to map select screen,

So do you get that error on the map selection screen directly after you've entered the server? 
Or after going through the lobby and you should be ingame, but instead you get an error message and **return** to the mission selection screen?

First behaviour is normal, as the "mission picture" is in the pbo, which is delivered from the server to the client after the lobby is passed. Therefore you can't have the missing picture on the mission selection screen.
If you encounter the second one, you're missing the picture. So you should recheck if it's really inside your pbo which you've uploaded to the server. (maybe you've missed it as you've put the framework and basefile together, if you've downloaded the master)

**Comment by Paxton1997** [comment]
I get the error from the prepacked and the build my own.  I'm honestly not sure if I've installed them on the server properly but for at least the prepacked one I just dragged the folder into the mpmissions folder in my arma 3 server directory. I don't have a modified version of either, they're both directly from you. For both versions i get to the lobby and the error occurs while recieving mission file.  I get 2 different reactions though depending on what i do, if i use the prepacked one, i still get the same error but it loads the map, just not the liberation mission, i spawn at the little island but theres nothing else loaded.  If i use the build my own version it doesnt load the map and instead just returns me to the mission select screen after giving me the kpflag error. I have made sure the file is actually there and unless im looking in the wrong res folder, then its there.

**Comment by ShamFleet** [comment]
Is there any tutorial out there on how to install the mod for a dedicated server?

**Comment by veteran29** [comment]
@ShamFleet Issue tracker is not a best place for questions like that. There is a lot of tutorials on setting up dedicated server on the web. If you need additional help with configuration of the server you can always ask on Discord.

**Comment by Paxton1997** [comment]
Nevermind, I figured it out.  I was installing the mission into the server wrong.  I was trying to drag all the files into the mpmission folder, i was unaware of the fact that all i needed to do was drag JUST the .pbo into the folder for the prepackaged version. I also didnt know i had to package my own .pbo from the build my own.  Thanks for trying to help though.
