### ISSUE TITLE
End Game 'Finale': Operation Iron Shield

### ISSUE THREAD

**Issue by XefeWhiteFlye** [Wyqer/kp_liberation#323]
From what I've read with the end game being "capture that last sector and you win" I'd like to spice it up a little with an idea I was thinking on after reading through many ideas on discord: Operation Iron Shield.

Basically, when the final town is captured the game seems to be all good but then players are overflown by hostile aircraft (Helicopters/VTOL's) that continue on away from the map and despawn once out of the players view distance. After a few minutes in game time of silence, a message would come through stating that the hostile forces are planning one last push to defeat the players and allied forces in an 'all or nothing' assault. Once the message has been displayed, a menu would come up for players to vote on any one of their FOB's to defend from. 

Once the vote is complete, players have to make their way back to the marked FOB and prepare with a hidden timer running in the background. During this time, vehicles and units could possibly cost less to help with the defense costs or be adjustable through editing. Once the timer has run out, the FOB would be overflown by a hostile jet or two with no intention of attack followed by a artillery bombardment outside of the FOB's area to minimize damage but prep the players for the incoming assaults. After the bombardment, a timer will begin (10/15/20/30 minutes) on how long players have to hold out for before the mission is deemed complete and are provided support through allied AI that arrive in the last few seconds. 

The idea was to have the attack in waves, with the next wave starting when the other wave is deemed 'destroyed' and following another barrage of artillery to keep players inside the FOB area. The main FOB building is indestructible during this entire operation so players can freely spawn off it or from the USS Freedom. A concept for the waves would be: 

Wave 1: Light Helicopter Support/MRAPs and Infantry.
Wave 2: Medium Helicopter Support/IFVs and Infantry.
Wave 3: Light Helicopter Support/IFVs/Armored Vehicles and Infantry.
Wave 4: Heavy Helicopter Support/IFVs/Armored Vehicles/CAS Support and Infantry.
Wave 5: A mix of all units in a last ditch attempt to eliminate the allies.

It's more or less just an idea for something do to at the end of the game, as I stated earlier a grand finale for playing the mod and getting through all those objectives for one final holdout. I would love to hear some feedback on it.

**Comment by Wyqer** [comment]
I guess it would be a good thing to extend the overall victory condition of currently "just capture all capitals" to something more complex, indeed.
But personally I'm not sure, if a "survive X minutes against enemy waves" is really a suitable and satisfying "final task" for the campaign. Haven't thought further about the topic, but more opinions/thoughts/ideas from others are welcome.

**Comment by Applejakerie** [comment]
I really like this idea, surprised it hasn't come up before but to me "waves" seem a bit Call of Duty-esque. I'd like to see the "end mission" be random between a bunch of ideas. For example, an enemy squadron to beat back, an artillery field search and destroy, a very HVT assassination (the head of the snake) etc. Maybe the enemy takes back a capital sector with the remainder of their forces - you've got to take it back but expect heavier resistance than usual. Could even go as far as "enemy forces are assembling a nuclear weapon" type search and destroy. I just think it needs to be less "if you lose this mission you lose the game" and more "if you lose this mission the enemy gets one more heavy strike to the nation".

**Comment by XefeWhiteFlye** [comment]
I did think on the idea of a final base that would appear or a town that was once captured would fall back under enemy control, basically a last standing point for them. The idea of nukes or very powerful weaponry was another, but then that would lock it to either using RHS vehicles for the SCUD launcher or just using props like the device (avoiding spoilers) from the base game as a placeholder. The whole waves concept was really just a basic idea, but having something to do at the end to signify that you've taken the island rather than just capturing another town seems a bit more appealing to me
