### ISSUE TITLE
Increasing distance and strength of patrols around cities

### ISSUE THREAD

**Issue by reggaeman007jah** [Wyqer/kp_liberation#325]
Hi Wyqer, I was wondering if there has been any discussion around patrols around cities, or mil-bases. What I am thinking is that, as the alert level goes up, opfor would start to send out stronger patrols, and also send them further afield. When I approach a town or city, I generally do not encounter contact until I am in the red marker zone. If the alert level is higher than [x], perhaps opfor would start to send out more punchy teams, to look for trouble.

Equally, you could implement an escalating patrol defence system around cities, so that as more cities are taken by the liberators, patrols grow in strength. With the aim of making it a challenge to even reach the last city... therefore requiring some significant firepower to even get near it. 

Just a few thoughts for consideration, and thank you for your work on this - it is my only mission now!

**Comment by Wyqer** [comment]
An general overhaul of the enemy behaviour and mechanics is part of the 0.97 version. It'll be a whole overhaul of the enemy mechanics. (and a full code refactoring of the whole mission)

**Comment by reggaeman007jah** [comment]
Sounds both awesome and terrifying
