### ISSUE TITLE
Suggestion: Parameter persistence. 

### ISSUE THREAD

**Issue by Applejakerie** [Wyqer/kp_liberation#326]
Just a thought and a question of capability... Is it possible to have parameters be saved as the default at the lobby screen in-game? So if I change medical from basic to none, none becomes the new default. Exceptions of course would be the wipe save and debug parameters. I'd take a guess at it not being possible but if I'm wrong and it is, that'd be a game-changer. No more pointing to `ui\mission_params.hpp`.

**Comment by Wyqer** [comment]
It's not possible to edit the default values (overwrite them in the file) while ingame. So it has to be done manually for persistent changes or everytime through the lobby parameters.

**Comment by Applejakerie** [comment]
Bummer, figured as much.

**Comment by NeoArmageddon** [comment]
Just for reference: https://forums.bohemia.net/forums/topic/169164-script-saving-mp-parameter-across-sessions/
