### ISSUE TITLE
Instant Death No Matter What

### ISSUE THREAD

**Issue by h0th34d** [Wyqer/kp_liberation#335]
### Basic Information
**Mission version:**
0.963

**Map used:**
Malden 2035

**Mods used:** 
Our unit uses a variety of different mods, but we have also created our own mudpack which consists of many other mods.
@CBA_A3
@ACE
@327th
@CUP_Terrains_Complete
@RHSAFRF
@RHSGREF
@RHSSAF
@RHSUSAF
@task_force_radio

**Dedicated or local game:**
We run on a dedicated server.

**Source of the mission file (URL):**

### Individual Things
**Did you edit anything within the mission files?**
I found this issue before I edited anything, but yes.

**If yes, what did you edit exactly?**
Which units are on the list in the "Build" menu, a couple of the vehicles and static turrets on the "Build" menu, the parameters for stamina and revive, and the parameter for halo jumping.

### Short Issue Description
Normally when we run a mission and someone goes down, it doesn't matter how many times they get hit while down, they can still be brought up as long as we find them and get them up before they bleed out. However, on the Liberation mission, if you are hit too much while down, hit with an explosion, or anything else such, you will automatically die and respawn.

### Expected Behavior
The players should just remain unconscious until either brought back up by someone or they bleed out.

### Steps to Reproduce the Issue
I ran another mission file we have with the same server settings for medical.

**Comment by h0th34d** [comment]
And yes, prevent instant death is on, lives is set to -1, medical is set to basic, and revive is off.

**Comment by Wyqer** [comment]
> and revive is off

Which "Revive" exactly?
