### ISSUE TITLE
Enemy vehicles being added to Zeus [Potential Oversight]

### ISSUE THREAD

**Issue by Takahashi-Yuuki** [Wyqer/kp_liberation#336]
### Basic Information
**0.963**
**Altis/Tanoa**
**IFA3, Faces of War, CBA, Saabs Aircraft Lib, IFA3 FoW Compat Patch, Sabres Secret Weapons, FoW Sabres Planes Integration, VCOMAI**
**Local Game**
**N/A**

### Individual Things
**Yes many things**

**Of relevance is Opfor and Blufor custom.sqf.**

### Short Issue Description
OPFOR vehicles in both the BLUFOR Vehicle arrays and OPFOR Vehicle arrays are being added to Zeus.

### Expected Behaviour
It was initially expected that enemy controlled vehicles would not be added to Zeus. Cursory examination of zeus_syncro.sqf reveals no mechanism to prevent this behaviour. I am assuming that this behaviour is expected, but potentially undesirable behaviour, as a result.

### Steps to Reproduce the Issue
Add any vehicle from Opfor.sqf into one of the vehicle arrays in Blufor.sqf

### Screenshots, Serverlog or any other helpful Information
The classname of the M3 Stuart in this image had been entered into both the opfor_vehicles_low_intensity array in Opfor.sqf and the heavy_vehicles array in Blufor.sqf
https://i.imgur.com/52ITITy.jpg

**Comment by veteran29** [comment]
I can't test this in game right now but i guess changing:

```sqf
(typeof _x in _vehicleClassnames)
```
to
```sqf
(typeof _x in _vehicleClassnames && side _x !== GRLIB_side_enemy)
```
in this `if` in zeus synchro:
https://github.com/Wyqer/kp_liberation/blob/a16b84e4612d8d0b9a167c41865f9c1c4ec2a44b/Missionframework/scripts/server/game/zeus_synchro.sqf#L28-L32

would fix this issue.

**Comment by Wyqer** [comment]
@veteran29 points to the right edit you would have to make, if you add enemy vehicles to your own build list (why?).
Only thing it's `!=` and not `!==`

**Comment by Takahashi-Yuuki** [comment]
Much appreciated. The player faction I'm using has a very limited vehicle list, so I decided to use enemy vehicles as the base rewards, to simulate the capture of enemy stockpiles. It's not an ideal solution but the alternative was not providing any capture rewards at all.
