### ISSUE TITLE
AI have become uncapturable.

### ISSUE THREAD

**Issue by PhantomViper** [Wyqer/kp_liberation#341]
### Basic Information
**Mission version: 0.963**
**Map used: Tanoa**
**Mods used: (https://i.gyazo.com/251c882bc235a3403dfd6d3053aea3cd.png) We were also using a mod called ASR AI3 to make AI more difficult but found it to be too challenging so we removed it.**
**Dedicated or local game: Local**
**Source of the mission file (URL): https://github.com/Wyqer/kp_liberation**

### Individual Things
**Did you edit anything within the mission files?**
Yes.

**If yes, what did you edit exactly?**
Modified a few values pertaining to purchase values in the build menus as well as changing the height halo jumps start at.

### Short Issue Description
Enemies are no longer surrendering when capturing a town. Their weapons are removed but they do not put their hands on their head and they run around typically. They are not able to be captured. Occasionally not all the AI will surrender and will still their weapons, but there are still AI who did have their weapons removed mixed in so it is not a huge issue. At the start of the mission it was working as expected but something broke, not exactly sure when. Occurred before the removal of the ASR AI3 mod above. In addition helicopter pilots can not be captured either on search and rescue missions.

### Expected Behavior
When a town is captured enemies will surrender to be captured for intel. Also pilots will be able to be captured.

### Steps to Reproduce the Issue
1. Capture a town.
2. Notice AI do not surrender properly.
3. Become unable to gain intel to reduce threat level.

### Screenshots, Serverlog or any other helpful Information
Nothing.

**Comment by Wyqer** [comment]
Append a serverlog, where you've encountered this issue.

**Comment by PhantomViper** [comment]
No server logs, to much to keep track of mods wise. Guys decided to started a new game.

**Comment by PhantomViper** [comment]
We found that running this version on a dedicated server is causing the AI to become uncapturable. When swapped to non-dedicated the AI function as expected.

**Comment by PhantomViper** [comment]
No AI mods at all. Going to try to run a dedicated server on my end.

**Comment by PhantomViper** [comment]
It was running off my buddies system

**Comment by PhantomViper** [comment]
Finally set up a server on a second comp and all is working well. All the same mods and just some light touching of config files. My buddy might have changed something essential on accident on his game.
