### ISSUE TITLE
Generic Error In Expression

### ISSUE THREAD

**Issue by PurgenChikatilo** [Wyqer/kp_liberation#343]
### Basic Information
**Mission version:** 
0.963
**Map used:** 
Chernarus
**Mods used:** https://cdn.discordapp.com/attachments/315696454373212161/418646067924566017/137.html
**Dedicated or local game:** 
Both, neither change the effect on error.
**Source of the mission file (URL):** https://cdn.discordapp.com/attachments/315696454373212161/418646407776305162/106_liberation.chernarus.pbo

### Individual Things
**Did you edit anything within the mission files?**

Yep, quite a bit.

**If yes, what did you edit exactly?**

Arsenal loadout preset, BLUFOR/OPFOR/RESISTANCE/CIVILIAN preset. (Trying to get Russian VDV on Blufor, USMC on Opfor, Ukrainians on Resistance and Chernarus civvies on Civilian.

### Short Issue Description

So, this is related to the sqm files. I replace lines, everything is fine. I add or remove some, depending on what I wanna slam into the mission, it goes bonkers.

### Expected Behaviour

# **_[generic error in expression intensifies]_**

### Steps to Reproduce the Issue

Remove some lines of loadout bits like headgear, then add some extra vests or whatever. Literally screws it all up and prevents the mission from initializing.

### Screenshots, Serverlog or any other helpful Information

Right here: https://imgur.com/a/YRaCP

**Comment by Wyqer** [comment]
The error messages already showing you the answer of your issue. Your edits aren't following the SQF syntax. So recheck your edits. The issue isn't caused by anything "buggy", it's because of mistakes in your edits.
I recommend you have a look at this article in the wiki:
https://github.com/Wyqer/kp_liberation/wiki/EN:ImportantHints#preventing-common-mistakes

**Comment by PurgenChikatilo** [comment]
Oh my God, I cannot believe I screwed this up. The answer was there all along, I'm sorry for wasting your time.
Thanks a lot for pointing it out!
