### ISSUE TITLE
Progress not saving on dedicated server

### ISSUE THREAD

**Issue by azola21** [Wyqer/kp_liberation#345]
### Basic Information
**Mission version:** 0.963
**Map used:** Neaville
**Mods used:** IFA3_AIO_LITE, CBA_A3
**Dedicated or local game:** Dedicated
**Source of the mission file (URL):** http://steamcommunity.com/sharedfiles/filedetails/?id=917746370&searchtext=liberation+WW2

### Individual Things
**Did you edit anything within the mission files?**
No

### Short Issue Description
Progress is not saving, I believe this is because the profile location of the server is different to what the mission file expects. I was wondering if you knew any way for directly telling the mission file where to save to or how to otherwise save progress on the server. I am using vilayer.com for hosting.

### Steps to Reproduce the Issue
1. Launch server
2. Join server
3. Binge play liberation for 5 hours.
4. Leave server
5. Restart server
6. All progress is reset back to the start

Profile location below

![Profile location](https://user-images.githubusercontent.com/36462120/37152862-a933c3dc-232a-11e8-89a9-09466909539f.PNG)

**Comment by Wyqer** [comment]
> I believe this is because the profile location of the server is different to what the mission file expects

The missionfile don't say "use profile X". It's your server configuration (or from your admin) who has to specifiy which profile the server should use. Liberation stores the save data in the provided profile.
Make sure you set a -profiles and -name startup parameter.
Reference:
https://community.bistudio.com/wiki/Arma_3_Startup_Parameters#Profile_Options

**Comment by Wyqer** [comment]
If you encounter still issues after setup the server correctly, you should ask for support from the creator of the version you're playing, as it's no "KP Liberation orginal" and therefore I can't say what the creator may have changed. So it's his/her responsibility to provide support for their versions.
