### ISSUE TITLE
Suggestion: Vcom AI support/integration

### ISSUE THREAD

**Issue by CurePindal** [Wyqer/kp_liberation#346]
Hello Wyquer!
Is there a chance that you can integrate Vcom AI or at least add support for it?
[https://steamcommunity.com/sharedfiles/filedetails/?id=721359761&searchtext=vcom+ai](url)

We did some tests with the recent release and Vcom AI with some good results and some not so useful results. The AI was nicely enhanced, which gave e.g. town attacks a decent buff by making the AI much more engaging (and trip-mining houses..). Especially using e.g. statics on their own, manning unmanned vehicles (they stole our parked tanks a few times), flanking and more dynamic CQC makes it a worth to have mod.

The drawback seems to be that Vcom AI seems to coordinate all activated AIs. So it draws AI from near-by locations to the location youre fighting for and hence messing with the missions own balance. Also the CPU impact is higher, which we solved with lower max AI and additional headless clients. 

Overall it was a blast to test Vcom AI with Liberation and its really worth to have.

**Comment by Wyqer** [comment]
Hey CurePanda,
some people use VCom, but you should have a look at the own settings which are provided by it. For example deactivate it for blufor and civilian side. Beside of that I don't see a way/need to code something in as a "adapt if used" for a mod which provide most of the needed settings (as far as I know). Also I would need to read into a mod which I personally don't use.
Basically I recommend you head over to the discord and ask in the liberation channel concerning your specific "issues" which appear if you use VCOM AI alongside with the Liberation framework. I bet there are many people who use it and can provide direct support for it.
