### ISSUE TITLE
Suggestion: Basic Armory equipment costs

### ISSUE THREAD

**Issue by CurePindal** [Wyqer/kp_liberation#347]
Hello!
I wonder if it would be possible to add some simple/basic cost for equipping at the armory? Maybe as parameter toggle?
Something like basic costs in supplies and weapons for swapping rifles, launchers and armor. And some extra costs for high-tier stuff, like missiles, statics, drones and snipers.
Would be a nice addition when using the non-restricted armory.

**Comment by Wyqer** [comment]
Possible of course.
But not with a "let's quickly implement it". And as 0.97 is aiming to refactor the whole code and internal mechanics of the framework there won't be any further (optional) features until 0.97 is finished, which will still take a while.
