### ISSUE TITLE
A Sector is placed on map twice

### ISSUE THREAD

**Issue by madpat3** [Wyqer/kp_liberation#349]
### Basic Information
**Mission version: 963**
**Map used: Chernarus**
**Mods used: unimportant**
**Dedicated or local game: unimportant**
**Source of the mission file (URL): https://github.com/Wyqer/kp_liberation/releases**

### Individual Things
**Did you edit anything within the mission files?**
no

**If yes, what did you edit exactly?**
%

### Short Issue Description
the sector named "Solnichniy Fuelstation" is placed twice on map.
it should only be present on grid 134/758, but it is also placed on grid 104/781.

### Expected Behaviour
%

### Steps to Reproduce the Issue
%
### Screenshots, Serverlog or any other helpful Information
%

**Comment by Wyqer** [comment]
In the official release there is only one "Solnichniy Fuelstation" alongside with "Solnichniy" and "Solnichniy Factory".
Do you have / could make a screenshot of it?

**Comment by madpat3** [comment]
no, you're right.
for some reasons, don't know why, i copied an older mission.sqf into the new mission's folder.

my mistake, sorry.
