### ISSUE TITLE
Suggestion: big military bases

### ISSUE THREAD

**Issue by RaulPro19** [Wyqer/kp_liberation#350]
My idea is to add the "big military bases" or enemy HC, as a type of sector to capture necessary to achieve the victory as the big tows are.

I think this would be a nice idea because you can have lots of vehicles but you can't use them in the cities because of the civilian activity of the risk of destroying buildings.

This bases would be almost the same as the actual military bases but heavily defended with several armored vehicles, static weapons, lots of infantry and maybe helicopters (maybe landed until you are detected?)
Then, you can use your whole arsenal, planes, tanks and artillery to capture this sector without the risk of killing civilians.

My idea is to replace 1 or 2 cities per map and put this bases instead, and as i said, you will have to capture this bases in order to win the mission.

Thanks for reading it and sorry for my bad English :P

RaulPro19

**Comment by Wyqer** [comment]
The "overall goal" will be different as soon as the next version will be finished. Many things will change then. But I'll leave this suggestion open for any discussion about it.
