### ISSUE TITLE
Problem with IND Enemy Preset

### ISSUE THREAD

**Issue by Dubjunk** [Wyqer/kp_liberation#353]
Mission version: 0.963
Map used: Altis
Mods used: http://steamcommunity.com/sharedfiles/filedetails/?id=1308553600 + VCOM AI
Dedicated or local game: Dedicated
Source of the mission file (URL): https://cdn.discordapp.com/attachments/401424294032310272/418534957317750794/kp_liberation.Altis.pbo

Individual Things
Did you edit anything within the mission files?
Yes.

If yes, what did you edit exactly?
Modified different values and scripts.

Short Issue Description
Enemy High Ranked Officer spawning on wrong Side when using IND Enemys.

Expected Behaviour
The AI should be on OPFOR Side.

Steps to Reproduce the Issue
unknown

Screenshots, Serverlog or any other helpful Information
https://cdn.discordapp.com/attachments/416228713198387201/419163036662628364/20180302170146_1.jpg
https://cdn.discordapp.com/attachments/416228713198387201/419163040303546368/20180302170155_1.jpg
https://cdn.discordapp.com/attachments/416228713198387201/419163049182756874/20180302170216_1.jpg

**Comment by Wyqer** [comment]
As we've already talked in discord I'll close this here.

Summary:
It's not recommended to use a independent faction for the opfor side, as they are covered by the resistance faction in the mission.
It's needed to add some spawning of empty groups on the enemy side and put the independent units in the prespawned groups to adjust their side.
