### ISSUE TITLE
Suggestion: Elite OPFOR soldiers and squads

### ISSUE THREAD

**Issue by dmorchard** [Wyqer/kp_liberation#360]
Several versions ago there were more configurable slots for OPFOR soldiers (i.e. CSAT's Vipers) and squads (i.e. opfor_squad_low_intensity, opfor_squad_8_standard, opfor_squad_8_infkillers, opfor_squad_8_tankkillers, opfor_squad_8_airkillers).  I can't say for certain that I encountered all of those squad types in-game, but the Vipers were definitely present, and terrifying - especially in the Tanoan jungle at night :)

The current OPFOR presets don't have slots for any elite soldiers or specialist squads, but it'd be great to get those back in v0.97 for implementation during "high enemy combat readiness".

**Comment by Wyqer** [comment]
0.97 isn't nearly finish. So it's quite too early to say something like "get them back in 0.97" ;)
Everything which is currently in Liberation will be in 0.97, don't worry.
