### ISSUE TITLE
Problem with logistic system

### ISSUE THREAD

**Issue by Meiestrix** [Wyqer/kp_liberation#361]
Hi, 
I have a question / suggestion to the logistic system and hope it is Ok to ask here.
At the moment i am hosting your mission on a public server without problems, expect the logistics system.
Basically it works fine but i always have the problem that people play around with the settings without knowing what they do. The result is that there a no resources left at the FOBs and all the factorys are full.
Is there any way to limit the access to the logistics system to admins or change back to the passive income system?

At the moment it is not possible to play on long term without constantly checking if the logistic is still fine, when you host the mission on a public server.

**Comment by Wyqer** [comment]
> Is there any way to limit the access to the logistics system to admins

The production and the logistic interface is already only available for logged in admins and the player on the commander (Platoon Leader) slot. And the possibility to whitelist the commander slot is given by the mission parameter and whitelist.sqf in the mission folder.
