### ISSUE TITLE
Request to change addaction sort order.

### ISSUE THREAD

**Issue by Havoc302** [Wyqer/kp_liberation#369]
Request to change sort order of all cursortarget conditional addactions to be the highest on the list, especially "Push Crate" and "Build and Repeat".

This allows for easier rapid repeats.

**Comment by Wyqer** [comment]
Personally I won't change it in the "official version". In my opinion it shoudln't be the highest on the list. Also the "push crate" action don't disappear after using, so you can reclick after you've done the first push.
If you like to change it in your copy, here's how:
https://github.com/Wyqer/kp_liberation/blob/master/Missionframework/scripts/client/ammoboxes/ammobox_action_manager.sqf#L55

There you have the 4 addAction commands and the action priorities:
* -501
* -502
* -503
* -504

You could change them to:
* 23
* 22
* 21
* 20

This would make them appear at the top of the action menu.
