### ISSUE TITLE
Adding BAF vehicles to the build menu

### ISSUE THREAD

**Issue by Bear8402** [Wyqer/kp_liberation#371]
### Basic Information
**Mission version:** 0.963
**Map used:** Sahrani
**Mods Used:** GRAD Trenches, TFAR, Shactac, Enhanced Movement, Backpack on Chest, Ares Mod, Advanced Conmabt Environment Extras 3.3.0, Advanced Towing, Advnaced Combat Environment 3.12.1, Ace_Compat_AFRF, ACE_Compat_USAF, SMA RHS Comp Patch, Project OPFOR, f/a18 sUPER hORENT pACK, SMA, VSM All in one, RHS: Armed Forces of the Russian Federation, RHS: United States Forces, 3CB: BAF vehicles, Equipment, Weapons and units, CUP Terrains aps 1.4.2, CUP Terrains Core 1.4.2, CBA 3.6.1.

**Issue:** We have the 3CB BAF mods on the server, however we are unable to purchase any of the vics in game via the build menu. We're not quite sure why we are unable to as all the relevent sqf's are where they should be. We have spent a lot of time googleing around trying to find the solution but to no avail. We are clearly missing somthing to allow the buying/usage of the BAF vics in game. Can anyone suggest what the issue might be please.

**Comment by Bear8402** [comment]
Currently set to 2. Do we change it 0?

**Comment by jus61** [comment]
If your config KP_liberation_preset_blufor = 2; you must make your changes here https://github.com/Wyqer/kp_liberation/blob/0.963a/Missionframework/presets/blufor/3cbBAF_mtp.sqf

**Comment by Bear8402** [comment]
What changes do i make in that file?
Addtionally, Spartan 01 does not actually spawn in at the ops base now and neither do the boats and littlebirds. I know they should change to the BAF varaints (Merlin and wildcats) but they too do not spawn in.

**Comment by Wyqer** [comment]
Attach an actual serverlog, where you encounter this.

**Comment by Bear8402** [comment]
I only have access to the PBO and not any of the server bits at all. (I know weird). In the 3cbBAF_MTP.sqf file it states the default variants of Spartan 01 and the littlebirds (The US versions). Does this make a difference?

**Comment by Wyqer** [comment]
Without a serverlog it's like searching for a needle in a haystack, sorry.

**Comment by Bear8402** [comment]
Going to give a go. What is wierd though is thati was able to 'purchase' the UK3CB_BAF_Merlin_HC3_32_MTP via the build menu in game even though the logs state that it is not found.

**Comment by Wyqer** [comment]
Because the client (which has the mod installed correctly/intact) spawns a built vehicle and not the server.

**Comment by Bear8402** [comment]
ahhhhhhhhhhhh. Hopefully a verify should fix it.
Thanks for you help and patience

**Comment by Wyqer** [comment]
You're welcome.

**Comment by Bear8402** [comment]
Would it matter what the mods folders are named on the server itself. They are named @3cb_BAF etc...

**Comment by Bear8402** [comment]
What should be simple is getting frustrating. Re-downloaded the mods for the server and installed them again. Spartan 1 and little birds (or their BAF equivalents) not spawning in. Can purchase BAF vics however after a short while they become 'locked' we can see them and we get the options when scroll wheeling on them but cannot enter them to drive etc...After the server was restarted BAF vics that were purchased are no longer on the server. 
Am I missing something?

**Comment by Bear8402** [comment]
Just want to thank Jus61 and Wyqer for your patience and help. We've finally got the bottom of the problem and all is well. We can finally get back to playing.

Thanks again.
