### ISSUE TITLE
Option to play without enemy vehicles

### ISSUE THREAD

**Issue by steelbrain** [Wyqer/kp_liberation#42]
Enemy vehicles add exponential difficulty that you cannot battle by just spawning friendly AIs. It makes it super hard to complete the game after capturing a couple of regions.

Having an option that controls where Enemy vehicles are spawned or not would make the game a lot more enjoyable for 2-3 person LAN parties

**Comment by Applejakerie** [comment]
Really? I play in a group as low as 2 some of the time, enemy vehicles are usually combated via our own launchers or via an AI squad member. Fighting only enemy infantry would make little to no sense and would mean you, flying a jet or using a tank, would be unstoppable with only a slight amount of required skill. However, you could remove the vehicle classname from the custom.sqf and keep only the technical in the militia array. That might be more what you're aiming for?

**Comment by steelbrain** [comment]
Yes, that's what I've done for now, removed the values from custom.sqf

Not everybody wants to fight with jets and all, some people prefer the on ground experience of going from door to door and hunting enemies. Furthermore I've only requested this as an option, so it works for all

**Comment by Wyqer** [comment]
As you can customize that via the custom.sqf in the way @Applejakerie mentioned, I won't implement such a option.

**Comment by steelbrain** [comment]
While I disagree with what you're saying, I appreciate that you are trying to keep this project focused! :)
