### ISSUE TITLE
0.95 - Helipad Not Able to Recycle

### ISSUE THREAD

**Issue by ChiefOwens** [Wyqer/kp_liberation#43]
The Helipad is not able to be recycled. I believe it used to be but it was but it took some moving around to do it. I  tried all 4 corners, along the edges, and in the center to recycle the item.

**Comment by Wyqer** [comment]
Yeah, I've recognized that as well. And it's a kind of ArmA problem, not directly with the mission.
I will have a look to create some kind of workaraound, but for now it's BIs fault.
