### ISSUE TITLE
0.95 Unable to build Supply Point for Ioannina Sector

### ISSUE THREAD

**Issue by ChiefOwens** [Wyqer/kp_liberation#44]
I am unable to deploy a Supply Point for the Factory to produce supplies in Ioannina.. I took the radio tower near Pefkas, Pefkas, and then Ioannina Sector. Pefkas worked and is working fine. After Ioannina did not work, I went to Delfinaki and was able to build a Supply Point for that sector. I have tried reboots of Server and PC and I am still unable to build Ioanina.

**Comment by Wyqer** [comment]
Will have a look into it.

**Comment by ChiefOwens** [comment]
This is indeed fixed in the newest version.
