### ISSUE TITLE
0.95 Sector Supplies showing in FOB Supply Totals

### ISSUE THREAD

**Issue by ChiefOwens** [Wyqer/kp_liberation#45]
I modify do_build_fob.sql to

_minfobdist = 500;
//_minsectordist = GRLIB_capture_size + GRLIB_fob_range;
_minsectordist = 5;

to be able to build in key locations. The Sector in question is Almyra. The center of my FOB building is 89k meters from the center of the marker for Almyra at the airstrip in the desert. The supplies from Almyra are showing up on the ALPHA FOB totals without moving. The only time I need to move is when the Supply in Almyra reaches 12 and production stops. This is repeatable after server/pc reboot.

**Comment by Wyqer** [comment]
Yeah, the FOB resource storage array just work like "get all storage areas inside radius X from FOB building". I'll implement a object bound variable to prevent this to happen. But basicly it has reasons, why you shouldn't be able to build FOBs inside sector areas in the "official Liberation".
