### ISSUE TITLE
0.95 GRLIB_fob_range = Not Working // Build range around the FOB building

### ISSUE THREAD

**Issue by ChiefOwens** [Wyqer/kp_liberation#46]
// Build range around the FOB building
GRLIB_fob_range = 125;

Changing the above code does not work. Looking at action_manager.sqf, it appears that _distfob = 100; is the actual value that is being used and is hard coded. GRLIB_fob_range =  in the kp_liberation_config.sqf file is not being used.

**Comment by ChiefOwens** [comment]
starting at line 107

	if ( _fobdistance < _distfob && alive player && vehicle player == player && ( (  [ player, 3 ] call F_fetchPermission ) || ( player == ( [] call F_getCommander ) || [] call F_isAdmin ) ) ) then {
		if ( _idact_build == -1 ) then {
			_idact_build = player addAction ["<t color='#FFFF00'>" + localize "STR_BUILD_ACTION" + "</t> <img size='2' image='res\ui_build.paa'/>","scripts\client\build\open_build_menu.sqf","",-985,false,true,"","build_confirmed == 0"];
		};
	} else {
		if ( _idact_build != -1 ) then {
			player removeAction _idact_build;
			_idact_build = -1;
		};
	};

**Comment by Wyqer** [comment]
It's hardcoded for the action to show up, yeah.
But the building radius is adapted to that. Don't know, why zBug hardcoded it (maybe he forgot to change it afterwards or something). Will be changed.
