### ISSUE TITLE
Identify Features for Buildings

### ISSUE THREAD

**Issue by Wyqer** [Wyqer/kp_liberation#5]
Identify senseful features which could be provided by appropriate buildings.

**Comment by svamp3717** [comment]
Enough living quarters necessary to build AI. (Just tents or probably something more robust that wont get driven over.)
Fuel storage to match up with the fuel cap.
Ammo storage to house the collected ammo.

**Comment by Wyqer** [comment]
I already thought about that kind of storage buildings for the resources. I also don't like that magical storage, which is used at the moment.
So yes, I like that idea.
