### ISSUE TITLE
0.95 Supply crates new removing from mission files

### ISSUE THREAD

**Issue by JamieKG** [Wyqer/kp_liberation#51]
In some of the mission files there are placed supply creates that need remove due to causing problems when loading them into the fob supply storage areas

**Comment by Wyqer** [comment]
Thanks to report it here again.
During the "cleanup" after feature implementation and before release, we'll get through all official provided maps to prevent that.

**Comment by Wyqer** [comment]
Closed now, as they won't break the resource system anymore.
But I'll remove the decorative ones in the future, so it won't confuse someone.
