### ISSUE TITLE
Identify buildable Objects for Sectors

### ISSUE THREAD

**Issue by Wyqer** [Wyqer/kp_liberation#6]
Which buildings or objects should be buildable in sectors?
Why should a certain building or objects be buildable?
Which features should be provided?
Which conditions should be apply on being able to build? (Kind of material truck in the area or something)

**Comment by Applejakerie** [comment]
I'd say, a separate array everyone can modify but the main picks would be sandbag defences, maybe the h-barrier defences and the static array. Those smaller tower posts would be good too I think. Add the sandbag defences and static weapons to this array, "GRLIB_ignore_colisions_when_building = []" and they'll be suitable for setting up static hard-points. Also if you can, being able to place static weapons directly onto structures would be great in many sectors.

Available features I'd hazard an unpopular guess at just the VArsenal. Being able to redeploy to each defensive site would be a bit OP in my mind? It would be cool if we could get a system for "defending AI", where you can pay the constant manpower and those AI will defend the "material truck". Optimally those AI would only simulate during player & enemy local activity.

Maybe the requirement should be that the "material truck" is within say 250m of the sector centre and stays alive. If it is destroyed, the surrounding built defences should despawn eventually if a new one is not put back quick enough. Also maybe the "material truck" should be the Bobcat (vanilla-wise). No one on my server uses the Bobcat and its' role is pretty OP for no reason. By all means let it repair/refuel/rearm still and that'll serve as another use for those defensive sites. I think whatever the truck though it needs to come with a drain to manpower, i.e. the manpower used to "construct and defend" the sites for as long as it is still in use.

**Comment by Wyqer** [comment]
The array etc. is self explanatory, sure.
And I've planned to use the Bobcat as "construction vehicle", because you've already said it: At this moment he hasn't any special role. And I don't plan, that he has to stay there.

I thought about "sector buildings" like a building which provide an arsenal, or increase the supplies output from the sector, maybe give the ability to recycle in the sector, etc.
So more "Buildings with functionalities" not only "defending buildings"

**Comment by ChiefOwens** [comment]
I was thinking along the lines of Apple about being able to put down AI. However, those AI would have to be dynamic somehow and not actually spawn unless someone was around. The idea of it costing manpower, fuel, resources is a nice touch. 

The Sector buildings is also an amazing idea.
