### ISSUE TITLE
Suggestion: eject corpses.

### ISSUE THREAD

**Issue by Applejakerie** [Wyqer/kp_liberation#62]

**Comment by Applejakerie** [comment]
When you're shot inside a vehicle you die there with no chance of a revive. Eject the corpses so a revive is still possible? A vehicle explosion shouldn't eject you however, or shouldn't let you be revived at any rate. It's been done on other missions and I can have a look if that helps?

**Comment by Wyqer** [comment]
kill_manager.sqf
add under line 49:
```
if (vehicle _unit != _unit) then {moveOut _unit};
```
Should work without problems. But I've not tested it yet or something. And it needs to be tested with ACE.

**Comment by Applejakerie** [comment]
Amazing stuff. ^^
