### ISSUE TITLE
Invisible FOBs

### ISSUE THREAD

**Issue by asfsdg** [Wyqer/kp_liberation#66]
When I resume a multiplayer game all the FOBs still exist in game logic but they are not visible (and there is no way to collide with them). But as I said: all the functions are available further ...
Sorry if it was reported already.
Happens without mods too.

It happens every time I resume a saved mission. A FOB I/we built is only visible in the same session.

**Comment by Wyqer** [comment]
Please report which version you play, which map, from where you downloaded the missionfile, which preset you use, which exact edits you've made and it would be also the best if you provide one server.rpt where the issue happen.

With this information it's much easier to help. Without it starts every time with a question and answer game. ;)
