### ISSUE TITLE
0.95dev - Parameter error

### ISSUE THREAD

**Issue by ChiefOwens** [Wyqer/kp_liberation#75]
When I start the game locally and on dedicated server, with a full wipe, I get an error about a parameter already defined and a line number. I will submit more info when I restart the server again.

**Comment by Applejakerie** [comment]
I've seen this, it only happens the once. You leave and come back, the error doesn't continue. It happens once during the wipe, as in. So I figured it's a reference to save data that no longer exists and that moment, because of the wipe. :)) Just my two cents to help where I can.

**Comment by ChiefOwens** [comment]
Indeed on restart it was gone.

**Comment by Wyqer** [comment]
Please provide the exact error message, that would greatly increase the ability to have a look at the behaviour you're experiencing.
Did you changed anything of the mission_params.hpp or kept it maybe from the experimental before?

**Comment by ChiefOwens** [comment]
The error is gone after deleting .var. and restarting the server.  Please close.
