### ISSUE TITLE
Almyra Base causing large amounts of lag | Static gun placement 

### ISSUE THREAD

**Issue by ChiefOwens** [Wyqer/kp_liberation#81]
Almyra Base is causing an unusual amount of lag compared to the rest of the map. I took a look at it thru the editor and there are a lot of placed objects in a small area. I removed the items that serve no purpose like trash, chairs, boxes etc and the lag was mostly gone (except during spawn in of troops).

Static weapons are placed in this base. One was placed ok. The two other I found were not. One was placed inside of a building and the other was outside the bases walls.

**Comment by Applejakerie** [comment]
I've not dealt with any lag issues and I captured the sector three times to be certain. How do you host? Also there's usually a lag spike per sector spawn yes, many AI are being spawned at once. It's only a second or so and cannot be avoided without severe optimisation which comes later and even then, I'd still expect a quick lag spike. We will probably talk about whether or not compositions should be removed, seems even x64 might struggle if you're correct. Static weapons I don't know what to say, they're ZEC compositions, not sure why they'd place unsuitable statics and keep them within the composition on release. Either or, for now they need removing regardless as they serve no AI purpose yet. 

Thanks. :))

**Comment by Applejakerie** [comment]
https://github.com/Wyqer/kp_liberation/pull/82

**Comment by ChiefOwens** [comment]
It's there for sure. Deleting some of the items not needed fixed it on our end. It happened on multiple players screens. We were able to reproduce it by leaving and coming back and after server restart. It doesn't seem to be happening any place else.

We have 330 vehicles on the map so there is a large amount of other items on there as well. Not sure if its connected. Working around the other placed bases on Tanoa doesn't seem to cause an issue when we played that the other day.

Could be the amount of people playing and the amount of other objects as well, but I wouldn't think that was an issue personally.

Our server is dedicated. Checked memory and cpu usage and they are not high with the amount of cores and memory we have on the server. Running multiple HCs.

**Comment by Applejakerie** [comment]
Many thanks for the information - #82 is there to avoid it happening for anyone else in future. Those 330 vehicles are objects and vehicles across the entire map aye. They don't simulate without a player nearby tho so they won't be causing issues unless you're there, near them. If it turns out objects cause lag still, even with the x64 improvements, I'm pretty sure Wyqer might decide to remove the bulk of them.

**Comment by ChiefOwens** [comment]
It looks good though man...really like it.

**Comment by Applejakerie** [comment]
Aye me too, aside from tests I haven't had a real experience there yet. There's a similar (a few extra objects too) base on Sahrani, I'll need to go over that too but it looks a lot of fun also. :))
