### ISSUE TITLE
Suggestion: Build Facility show hint on whats missing or needed to build

### ISSUE THREAD

**Issue by ChiefOwens** [Wyqer/kp_liberation#83]
Build Facility after capturing a sector should show a hint on what is missing or what is needed from/in storage if it fails (or needed) to build.

**Comment by Wyqer** [comment]
It is already.
build_fac_remote_call.sqf
Line 90
hint format [localize "STR_PRODUCTION_FACBUILD_ERROR",_price_s,_price_a,_price_f];

if you can't afford the factory there will be a hint of what is needed to build it.
STR_PRODUCTION_FACBUILD_ERROR:
"Not enough resources.\n\nYou need:\n%1 Supplies\n%2 Ammo\n%3 Fuel"

**Comment by Wyqer** [comment]
Or do you mean something different?

**Comment by ChiefOwens** [comment]
It's not showing up then. I will try it again on the next sector.

**Comment by ChiefOwens** [comment]
I can duplicate no message showing in the hint area top right or anyplace else.

**Comment by Wyqer** [comment]
Oh man, you're so right.
As it runs on the server and the hint won't be "remoteExec" on the client and only runs on the server the client will never see it (or he hosting a local MP).
How could I missed that.
Sorry for that, but many thanks for the heads up.

**Comment by ChiefOwens** [comment]
np trying to test between planting. That's why I didnt make the event today
