### ISSUE TITLE
Different elite vehicle unlocking

### ISSUE THREAD

**Issue by FatRefrigerator** [Wyqer/kp_liberation#84]
Instead of having various military bases unlock vehicles (since you can just target those bases). Have vehicle unlocking be done through progression by taking a percentage of the map or spending of intel or another resource.

**Comment by Wyqer** [comment]
Can you provide some detailed thoughts about it? An Example for some vehicles and how much percentage should be taken for it or which kind of resource and which amount should be necessary to unlock?

**Comment by ChiefOwens** [comment]
Air strips/fields and seaports are how we bring in significant amounts of military equipment that isn't propositioned. 

Your (near them) military bases and large cities are where your largest concentrations of military units will be and where battlegroups should spawn from. If the city or military base is Blue, then that spawn point for battlegroups is gone.
