### ISSUE TITLE
Hummingbird unable to slingload crates that spawn in captured towns

### ISSUE THREAD

**Issue by jappie2** [Wyqer/kp_liberation#86]
The Hummingbird that you start with at Base Chimera is unable to lift supply crates that spawn in towns you capture.
It is able to airlift the crates that drop down when you build the first fob, however the crates that spawn in towns you capture do not appear in the slingload assistant and are not slingloadable!
Verified by me and a mate, as well as somebody else pointing it out on discord.

**Comment by Wyqer** [comment]
Try after release of 0.95 again. I just added a line for storing to disable rope attach and on unstoring enable the rope attach again (it's also done when loading / unloading from a truck)
