### ISSUE TITLE
Logistics Convoy had status "No resources" even there have been enough

### ISSUE THREAD

**Issue by Mike2306** [Wyqer/kp_liberation#87]
Situation:
I had two convoys (Alpha, Bravo).
Alpha was delivering fuel from a factory to FOB Alpha.
Bravo should bring 200 supplies, 100 fammo, 200 fuel to a captured town, so I can build a factory.
After 2 minutes of status "loading" there was "no resources".
At this time I had 500+ of everything.

Not sure if it was some kind of "misusing" or an actual bug.

**Comment by Wyqer** [comment]
How many Trucks are buyed for Bravo?
And the mission for Bravo was only the 200S, 100A, 200F from FOB to the Town or maybe more already?

**Comment by Mike2306** [comment]
1 Truck for Bravo.
No, it was not more.

**Comment by Wyqer** [comment]
replace your `/scripts/server/resources/manage_logistics.sqf` with the following one:
https://github.com/Wyqer/kp_liberation/blob/v0.951/Missionframework/scripts/server/resources/manage_logistics.sqf

Set the debug variable inside the `kp_liberation_config.sqf` to true and send me the serverlog after you encountered that error again. Maybe write a "HERE" or something in the sidechat at the time you experience that.

**Comment by madpat3** [comment]
isn't it like you can't deliver more than 300 resources with one truck at a time. because 300 equals 3 boxes and with 3 boxes the truck is full!?

**Comment by Wyqer** [comment]
No, that will be more explained in the expanded tutorial which will be written in the next days.
Afterwards it shouldn't be confusing or misleading anymore, if the tutorial was read.

Some explanation:
https://forums.bistudio.com/forums/topic/202711-mpcti-coop-liberation-continued/?do=findComment&comment=3193598
