### ISSUE TITLE
Identify Ranks, Conditions and Benefits

### ISSUE THREAD

**Issue by Wyqer** [Wyqer/kp_liberation#9]
Ranks like real world? (expecting yes)
How could you rise in rank?
How you collect XP?
What benefits you could get for a higher rank or on what you could spend XP for?

**Comment by JamieKG** [comment]
**Ranks like real world?**
No I think just levels based on amount of xp
**How could you rise in rank?**
By hitting a x amount xp
**How you collect XP?**
killing enemy ai
killing enemy vehicles
recycling enemy vehicles
loading supplies
storing supplies
capturing prisoners
delivering the prisoners
loss of xp for killing civilians
**What benefits you could get for a higher rank or on what you could spend XP for?**
each level could allow access to more stuff from the virtual arsenal and vehicles

**Comment by Wyqer** [comment]
Yeah, sounds like the same I've thought about.
I could use the normal ArmA rankings for that (as an displayed indicator for others) and link it in some way to the permissions etc.
