### ISSUE TITLE
"Time left" in Production Settings although there is no facility

### ISSUE THREAD

**Issue by Mike2306** [Wyqer/kp_liberation#91]
This happened after capturing a town and openig the production settings, it shows that there are some minutes left althouh there is no facility.
I did not click on "Confirm" or anything.

![image](https://cloud.githubusercontent.com/assets/28824308/26317179/e9b791fc-3f16-11e7-9a60-6efe546887d4.png)

**Comment by FatRefrigerator** [comment]
The timer "runs" but nothing will happen. Yes it's misleading but it has no real gameplay impact. The timer will reset to whatever the production time is set to when you begin production.

**Comment by Wyqer** [comment]
Yes, true.
But a good point, as it's really misleading. I'll change that for the 951 Hotfix.
Many thanks
