### ISSUE TITLE
Feature Suggestion: Add USAF Mod Assets

### ISSUE THREAD

**Issue by amunoz20** [Wyqer/kp_liberation#92]
Hi @Wyqer ! I've been playing this mission in takistan for quite a while now and I was wondering if you guys could integrate USAF Mod (found here http://www.armaholic.com/page.php?id=25512) as an optional mod and add the AC-130 Spectre to the vehicle list.

Currently im only interested in that specific plane, but USAF Mod contains lots of interesting air vehicles that would be nice to have in this mission. (for the right price ofcourse hehe) My idea would be 3000 ammo for AC130 Spectre.

If possible, would be nice to consider adding this other vehicles (I recommend this ammo values).
F-22 Raptor (Fighter) - 2000 ammo
F-35A (Fighter) - 2000 ammo
CV-22 Osprey (Transport) - 100 Fuel
E-3 AWACS (Inteligence plane) - 500 Fuel
MQ-9 Reaper (UAV) - (same as current Greyhawk uav)
RQ-4A Global Hawk (UAV) - (same as current Greyhawk[CAS] uav)

In case this suggestion would not be considered important enought to be added to mission, could you give me some directions on how to add this vehicles myself?

Thanks in advnace!

**Comment by Wyqer** [comment]
Hey there.

First, it's quite easy to implement it by yourself. You can have a look in the `kp_liberation_config.sqf` and select the preset you want. If you playing Takistan, I assume you're using the preset with Project OPFOR.
Then in the presets folder you've the different presets. `rhs_takistan.sqf` is the one which is made for Takistan.
Open it and you can add/delete/edit everything to your likings. Just beware of stick to the commas (everywhere inside, but not after the last element).
Then make it a PBO again and you're done :)
If you don't have a programm to unPBO and PBO I would recommend PBO Manager:
http://www.armaholic.com/page.php?id=16369

Second...
I'll have a look in the mod and it wouldn't be a problem to add it to the presets in one of the next versions then. As it won't interfere with anything if somebody uses that preset and don't have the mod (then the entry get's deleted for him).

**Comment by FatRefrigerator** [comment]
So Wyqer is trying to keep his focus more on developing features since it's fairly easy to add you're own mods/vehicles. 

Are you planning on using RHS for your ground-based units?

**Comment by amunoz20** [comment]
@Wyqer thanks for your advice, im really new to this arma 3 modding stuff so this seems like a nice challenge for me, sure I will try that. o7

@FatRefrigerator Yes I am. It's important to note that Im no planning on make a big change on this mission or anything... This whole idea started since im playing a "campaing" in takistan at the moment, but Im kinda lone-wolf/antisocial/solo player (lol) and I wanted to have more firepower to compensate the dificutly of playing alone... So the idea would be to copy-paste the existing takistan mission, open the correct files, and add the classnames of the vehicles I want ;)

**Comment by ChiefOwens** [comment]
@amunoz20 try adding https://forums.bistudio.com/forums/topic/190793-advanced-ai-command/ to your gameplay as well, if you don't use it. It will help you with your gameplay. The section you are looking to add it to looks like below. Hope that helps.


air_vehicles = [
	["B_UAV_01_F",75,0,25],												//AR-2 Darter
	["RHS_MELB_MH6M",200,0,100],										//AH-6M Little Bird
	["RHS_MELB_AH6M_L",200,100,100],									//AH-6M-L Little Bird
	["RHS_MELB_AH6M_M",200,200,100],									//AH-6M-M Little Bird
	["RHS_MELB_AH6M_H",200,350,100],									//AH-6M-H Little Bird
	["RHS_UH1Y_UNARMED_d",225,0,125],									//UH-1Y (Unarmed)
	["RHS_UH1Y_d_GS",225,200,125],										//UH-1Y (Ground Suppression)
	["RHS_AH1Z",500,500,200],											//AH-1Z (Multi-Role)
	["RHS_AH64D",750,750,250],											//AH-64D (Multi-Role)
	["RHS_UH60M_d",250,80,150],											//UH-60M
	["RHS_UH60M_MEV2_d",300,0,150],										//UH-60M MEV2
	["RHS_CH_47F_10",275,80,175],										//CH-47 Chinook (Armed)
	["rhsusf_CH53E_USMC_D",300,0,175],									//CH-53E Super Stallion
	["B_UAV_02_F",400,300,200],											//MQ-4A Greyhawk
	["B_UAV_02_CAS_F",400,500,200],										//MQ-4A Greyhawk (CAS)
	["B_T_UAV_03_F",450,500,250],										//MQ-12 Falcon
	["B_UAV_05_F",500,500,200],											//UCAV Sentinel
	["RHS_A10",1000,1000,400],											//A-10A (CAS)
	["FIR_F15C",1250,1250,450],											//F-15C Eagle
	["FIR_F15D",1250,1250,450],											//F-15D Eagle
	["FIR_F15E",1250,1500,450],											//F-15E Strike Eagle
	["JS_JC_FA18E",1500,1750,450],										//F/A-18 E Super Hornet
	["JS_JC_FA18F",1500,1750,450],										//F/A-18 F Super Hornet
	["B_Plane_Fighter_01_F",1500,1750,450],								//F/A-181 Black Wasp II
	["B_Plane_Fighter_01_Stealth_F",1500,1750,450]						//F/A-181 Black Wasp II (Stealth)
];

**Comment by amunoz20** [comment]
@ChiefOwens oh yeah, Advanced AI and C2 mods have saved my day since looong ago man! And thanks for the piece of code I will look into it.

I see this piece of code ["B_UAV_01_F",75,0,25] but I was wondering if you know what does the "75,0,25" parameters means? Those come with the classname of the vehicle that I want to add or means something else?

**Comment by Applejakerie** [comment]
75 = Cost in supplies. 0 = Cost in ammunition. 25 = Cost in fuel. :))

**Comment by amunoz20** [comment]
Thank you very much guys!! I will try this :) (if I ever get good at this I will help you develop this mission)
