### ISSUE TITLE
recruitment 

### ISSUE THREAD

**Issue by madpat3** [Wyqer/kp_liberation#93]
the recruitment feature doesn't work correctly.

-when i set it to "0", i cannot spawn any ai (which is correct) 
-when i set it to "1", i cannot spawn any ai, either (which is incorrect) 
-when i set it to "2", i can spawn only 1 ai (which is incorrect)
-and so on... 

!as a commander you can build eternal units as a crew, even if you don't built a vehicle, no matter what setting!

**Comment by Wyqer** [comment]
I'm sorry, but I can't really follow you which "recruitment feature" you're talking about. :(

**Comment by FatRefrigerator** [comment]
I believe he is talking about setting the squad size parameter?

**Comment by Applejakerie** [comment]
We worked out it's squad size too haha.

Those values are all correct, you're missing that you are 1 squad member also. :))
How would you produce a vehicle crew with no vehicle? Are you talking the pre-made squads or?

**Comment by Wyqer** [comment]
If it's the squad size parameter, then yeah.... you also count as 1 squad member. And now I'm wondering why there is a 0 value in the parameters. I've not touched anything of the AI recruitment code until now, so if there is a issue it has to be "always" there. But about the parameter: It's correct but somewhat missleading, yes.
And what's exactly with the "eternal units as a crew"?

**Comment by madpat3** [comment]
@Wyqer 
logged in as a commander, you can spawn as much as units that u like to, no matter what the parameters indicated

**Comment by madpat3** [comment]
@Applejakerie 
How would you produce a vehicle crew with no vehicle? Are you talking the pre-made squads or?

it is possible just log in as a commander and  can build units as "crew" with no vehicle.

**Comment by Wyqer** [comment]
Tested it now to really understand what you exactly mean.
So there is no bug.
The Squad Size is like explained (you have to count yourself in). Maybe I'll change it, to be not that missleading anymore.
You can surely build as many "crew" soldiers as you want (till the unitcap or end of resources is reached). As these you've as soldiers not in your squad, you can use them to send the one soldier for example to an empty vehicle to board it as "crew" instead of having to build a whole squad or a new vehicle with crew.

**Comment by madpat3** [comment]
ah, ok. so the squad size limit is not for the commander. 

but still, the parameters "0" and "1" are equal.

-when i set it to "0", i cannot spawn any ai 
-when i set it to "1", i cannot spawn any ai, either 
when i slot in as a regular soldier.

**Comment by Applejakerie** [comment]
That's the misleading part, there should be no 0.

**Comment by madpat3** [comment]
alright then 
thumbs up!!
