### ISSUE TITLE
Rounding mistake in the Production settings (Time left)

### ISSUE THREAD

**Issue by Mike2306** [Wyqer/kp_liberation#96]
Picture says everything I think

![image](https://cloud.githubusercontent.com/assets/28824308/26364770/b8f41fa2-3fe5-11e7-9cd9-212fba5ab106.png)

**Comment by Wyqer** [comment]
Oh, strange. But yeah, will have a look into that and maybe do some explicit type casting to prevent that to happen. Thanks.
