### ISSUE TITLE
Arsenal/Save File Bug

### ISSUE THREAD

**Issue by FightKnight441** [Wyqer/kp_liberation#969]
### Basic Information
Two bugs, potentially related:
* Setting the arsenal to ace arsenal causes some variable to be undefined (Screenshot provided at bottom).
* I am experiencing a bug part-way thru a KPLib Campaign. After some amount of map completion, it seems the save file gets corrupted and disallows players to access the arsenal and other KPLib functions.

**Mission version:**
Most recent

**Map used:**
Altis (Default Map) and Sumava (Custom)

**Mods used:**
Atleast ace and cba.

There are many more, but I experienced this on the Altis Campaign with less mods and the Sumava Map with more mods.
I am pretty confident it is not mod related (details below) but will check further if deemed necessary.

**Dedicated or local game:**
Dedicated

**Source of the mission file (URL):**
Most recent release from this Github

### Individual Things
**Did you edit anything within the mission files?**
Yes!

**If yes, what did you edit exactly?**
For the Altis mission: Mission Config only

For the Sumava mission: Mission Parameters, KPLib config file, Opfor and Blufor Presets

### Short Issue Description
After the players get thru some portion of the mission campaign (this happened on both maps), it seems that the save file gets corrupted, and KPLib functions (such as accessing the arsenal) fail. I believe it is due to the mots recent arma update, as I did not have this happen before. I think it may be linked to another issue I found while building the mission, which is- setting the arsenal parameter in the mission configs to ace causes a bug able to be seen in the editor.

### Steps to Reproduce the Issue

* Download most recent install of KPLib
* Run CBA and ace
* Set the arsenal to ace arsenal in mission Parameters (missionFrameWork/ui/missionParameters.hpp)
* Put any map into the framework and name folder appropriately to match mission
* Launch mission in editor
* You should see an error that mentions something about an undefined variable in kp_liberation_allowed_items (screenshot provided)

I cannot tell you exactly how to reproduce the corrupted save file error, but I think maybe the two bugs are related?

### Screenshots, Serverlog or any other helpful Information
I have attached the error I received when setting the arsenal to ace and the server logs of the server.
Thanks!

[BN_KP_ServerLogs.txt](https://github.com/user-attachments/files/17476820/BN_KP_ServerLogs.txt)
![KP_AceArsenalError](https://github.com/user-attachments/assets/2112b2f7-7135-489c-9d3d-88037fa37a58)

**Comment by some-evil-kitty** [comment]
This is fixed by https://github.com/KillahPotatoes/KP-Liberation/commit/749e8503ecf57f55477a336e35f062318aed782d

**Comment by FightKnight441** [comment]
How is this fixed? I mentioned that I am running the latest version of KP Lib, and I am receiving these errors.

**Comment by veteran29** [comment]
Upload your mission file

**Comment by FightKnight441** [comment]
I think that I may have solved it, will report in a few days once I am sure.

I was running the [Real Engine](https://steamcommunity.com/workshop/filedetails/?id=2127693591) mod, which creates a dependency in the mission file. I think this was the cause of the errors.

> I am pretty confident it is not mod related

I take back what I originally said lol

**Comment by FightKnight441** [comment]
It seems that Real Engine was indeed the issue.

Thanks for responding @some-evil-kitty @veteran29, I appreciate it!
