### ISSUE TITLE
suggestion: Van can carry 1 crate

### ISSUE THREAD

**Issue by CurePindal** [Wyqer/kp_liberation#97]
Would be really nice if the small van could carry 1 crate. Especially in the beginning it would help to get the first FOB sorted.
Lovely idea? =)

**Comment by Applejakerie** [comment]
The civilian van, truck and covered truck can. ^^

**Comment by CurePindal** [comment]
Yesterday I had the camo truck and I couldnt load crates.

**Comment by Applejakerie** [comment]
Oh the enemy van, I can do that too. Was meant to add a bunch of new options to the lists today but have got stuck at an unplanned outing instead haha.

**Comment by CurePindal** [comment]
The little camoed guerilla van still doesnt load crates in .951

**Comment by Wyqer** [comment]
From which commit state is the 951 which you're testing?

**Comment by Wyqer** [comment]
Replace the config.sqf with the one from just now. I've added the "Opfor Guerilla" van and offroad. That should "catch'em all" ;)
