### ISSUE TITLE
No items can be retrieved from the Arsenal

### ISSUE THREAD

**Issue by AndorasLP** [Wyqer/kp_liberation#971]
### Basic Information

**Mission version:**
v0.96.7a

**Map used:**
Tested with Altis and Al Rayak / pja310

**Mods used:**
CBA, ACE, RHS USAF, RHS AFRF, BWMod, CUP Core, CUP Maps

**Dedicated or local game:**
both

**Source of the mission file (URL):**

This GitHub (Dedi) and Steam Workshop (locally hosted Game)

### Individual Things
**Did you edit anything within the mission files?**
first no, then yes

**If yes, what did you edit exactly?**
Bug occurred with unedited Mission File, then i unpacked the mission PBO and tried tweaking the kp_liberation_config.sqf (arsenal presets and KP_liberation_allowed_items_extension) with no effect.

### Short Issue Description
All items, except for the ones explicitly mentioned in KP_liberation_allowed_items_extension are considered prohibited and don't show up in the Arsenal, but work when picked up in-game. 

### Expected Behaviour

I may be mistaken, but i think i shouldn't have to add all "allowed" items into the config file by Hand. 

### Steps to Reproduce the Issue

Follow normal mod installation.
Since i wasn't able to figure out the specific Problem, i can't provide a reliable way to reproduce this bug.

### Screenshots, Serverlog or any other helpful Information

No Log entries were created anywhere regarding this issue. 
This happened on both Client (locally hosted Game on my Machine) and a fresh Dedi installation on a hosted Root.
This bug is NOT related to #969

![Liberation_bug_1](https://github.com/user-attachments/assets/50d3645b-7120-4516-93c8-014f97130383)
![Liberation_bug_2](https://github.com/user-attachments/assets/edf049c9-1ae1-4b77-b48e-a5493ce36c2e)

**Comment by AndorasLP** [comment]
Figured it out

**Comment by KanaFumei** [comment]
@AndorasLP 

> Figured it out

Hey I haven't been to my Arma server since this post, today I only did mod updates and now I'm facing the exact same problem. Can you tell me how you solved the problem?? Thank you in advance

**Comment by LarryTheMagicDragon** [comment]
@AndorasLP It would be really nice to know how you fixed it right now
